### ISSUE TITLE
[Bug] Widget Scrolling Issues

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#1]
There are currently issues with scrolling between widgets:

- When moving from the last list of widgets, focus returns to group scroller instead of first widget of first page
- When moving from global widget, focus returns to group scroller instead of next widget
- When moving between widget groups, focus moves to last focused position in group instead of top/bottom widget
- Nice to have - ability to exclude certain widget pages from the scroll.

**Comment by drinfernoo** [comment]
I think this probably belongs here? It appears that there isn't any way to "round the bend" on widgets anymore... You can't scroll to the far right, and then back around to the beginning, as pressing right at the end opens the menu again.

Also, it seems that holding to scroll doesn't stop at the end of lists like it used to, and this is skin-wide. The only place where I notice it *does* work like this is in the widgets on the info dialog. I believe everywhere else is affected, however, including context menu, normal views, widgets, etc...

**Comment by jurialmunkey** [comment]
Holding right stops correctly at the end of a list for me.

Yeah the loop back around needs to be put back in - I'm just trying to get it working correctly.

**Comment by jurialmunkey** [comment]
The wrap around should be fixed now. Other issues in OP still persist.

**Comment by drinfernoo** [comment]
It seems on latest (0.1.36c), when a widget is focused rather than a main menu icon, I can't scroll "up" to a different section, only "down".

If I focus the main menu first, it works, but widgets aren't focused, so it won't scroll *through* them, only through the sections.

**Comment by jurialmunkey** [comment]
> 
> 
> It seems on latest (0.1.36c), when a widget is focused rather than a main menu icon, I can't scroll "up" to a different section, only "down".
> 
> If I focus the main menu first, it works, but widgets aren't focused, so it won't scroll _through_ them, only through the sections.

Yep, I've noticed this issue. Not quite sure what caused it to be introduced. 

I do have an idea to improve the scrolling in general, so hopefully that will also fix this up movement issue

**Comment by jurialmunkey** [comment]
Okay I've fixed the scroll up issue (was just a misnamed param).

**Comment by jurialmunkey** [comment]
Also TODO:
Look into possibility to exclude certain pages from the infinite scroll as suggested here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/97

**Comment by jurialmunkey** [comment]
This commit https://github.com/jurialmunkey/skin.arctic.horizon/commit/f0197fded3ab39c63e67b236790866e35452090e fixes the loop around issues.

Remaining issues: 
- Scroll between fullscreen/showcase widget and other widgets. 
- Scroll to last/first position in group rather than just group (not sure if possible to fix).
