### ISSUE TITLE
Can I add language support?

### ISSUE THREAD

**Issue by Secular2020** [jurialmunkey/skin.arctic.horizon#100]
I am a KODI enthusiast from China. I have just used your skin recently. I have never been exposed to how to edit skin.
I found some simple Chinese-language materials, and compared some of them with Chinese characters, but I ca n’t find some words, so I ’m here to help you. If you are not convenient to add language support, can you map all the language positions on the skin to the There are some language libraries, so I can come to Chinese one by one, thank you very much.

**Comment by jurialmunkey** [comment]
Information about translations are here:
https://kodi.wiki/view/Language_support#What_is_strings.po
