### ISSUE TITLE
[Feature] - Switch "Info" button to "Play" when Kodi Default Select action is Info

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/skin.arctic.horizon#101]
I am making this issue as I have a few simple enhancements that can be made to the options that are displayed when browsing movies/shows.

I’m not sure how you would prefer to track this, so I plan on currently making an issue for movies, and an issue for shows. I am more than happy to merge them into one issue and do separate posts for each (movies/shows), or if you prefer a different way, just let me know. 

Movies: These are all done while viewing the “Popular” list in TMDb Helper. 

- Possible to add a Play button, maybe to the left of “Info” in the screenshot below.  
![image](https://user-images.githubusercontent.com/29167580/78335624-d29cbc80-7542-11ea-9a59-81a238b5768b.jpg)

- Possible to swap the actions of clicking on a movie and clicking the “Info” button. I feel
the flow would be better if clicking on a movie’s poster brought you directly to this screen:
![image](https://user-images.githubusercontent.com/29167580/78336312-062c1680-7544-11ea-899e-b63f0fcbf936.jpg)
(speaking of which, possible to add a play button to this screen too?)

Instead of (I feel this feels more natural for the Info button):
![image](https://user-images.githubusercontent.com/29167580/78336374-1ba14080-7544-11ea-84b3-7e8410c3ce3f.jpg)

Note: These are just recommendations based on my experience of the skin so far, and how I feel would improve the flow of the skin. Even without these changes, the skin is still top tier as is everything you do.

**Comment by jurialmunkey** [comment]
You can change default select action in Kodi settings.
`Media Settings > Videos > Default select action (show information)`

In the info dialog the "Browse"  button is shown if the item is a folder, and the "Play" button if the item is playable. It shows "Browse" for TMDbHelper because the item is a folder which opens to the list screen. To change it, you need to change TMDbHelper's select action from "Browse" to "Play".
`TMDbHelper Settings > Navigation > Default select action in addon (Play/Open)`
That option makes TMDbHelper skip the detailed list section and makes items directly playable.

My plan is to have the info button switch to a play button when Kodi's default select action is show information.

**Comment by Demonseeed** [comment]
I had little time to test that, but yes setting TMDbHelper to “Play/Open” did accomplish it. I straight up forgot about that setting lol. 

I’m reluctant to change Kodi’s default select action to Play as I want to get an info screen when selecting a item from a widget (and don’t want to use the context menu or the i key), but I think your solution pretty much solved it. 

I like the additional plan you got, that would likely further increase the user’s flow of the skin. 😄

**Comment by jurialmunkey** [comment]
> I’m reluctant to change Kodi’s default select action to Play as I want to get an info screen when selecting a item from a widget (and don’t want to use the context menu or the i key), but I think your solution pretty much solved it.

No, that's what I was suggesting:
Kodi default select action = Info
TMDBHelper select action = Play/Open

That way you click on the item, the info opens and the play button is in the info dialog.

I just need a way to reliably read the Kodi setting (by default skincan only read boolean True/False system settings - and that one has more options than true/false). Then I should be able to switch the button above the library view to be "Play".

**Comment by Demonseeed** [comment]
Oh okay cool, that’s how I have it now. 

For that last part, I have no idea - I wish I could be of more help there. 

Would it be possible to read the setting and set it to Home.setProperty, then have the skin display what you need based off that property?

**Comment by jurialmunkey** [comment]
Nah, skins can't even read system settings unless they are True/False.

**Comment by drinfernoo** [comment]
@jurialmunkey Could that feature be added to TMDbHelper, and then you use it in AH? That way, it could also be used in other skins as well.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Could @Demonseeed's idea be added to TMDbHelper, and then you use it in AH? That way, it could also be used in other skins as well.

I'm not quite following?

**Comment by drinfernoo** [comment]
What I mean is, could TMDbHelper read the setting and expose it as a window property? That way the skin doesn't have to (since it can't), and you can still get the value.

**Comment by jurialmunkey** [comment]
> 
> 
> What I mean is, could TMDbHelper read the setting and expose it as a window property? That way the skin doesn't have to (since it can't), and you can still get the value.

Oh yeah, okay that makes sense. Yeah that'd be a possibility.
