### ISSUE TITLE
[Bug] Next "new" Episode not selected

### ISSUE THREAD

**Issue by svb91** [jurialmunkey/skin.arctic.horizon#102]
I use the following setting in KODI:

"Select first unwatched TV show season / episode": On first entry

The skin select the correct first unwatched season however there is no episode selected and I have to scroll through the entire season to watch the next unwatched episode.

![bug_2](https://user-images.githubusercontent.com/36643963/78385115-a123ff80-75db-11ea-9485-a9f6c215d362.PNG)

**Comment by jurialmunkey** [comment]
That setting only works in episode view, not seasons view - nothing can be done about it unfortunately.
