### ISSUE TITLE
[Feature] Submenu Idea 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#104]
About two weeks ago you were thinking about where to add submenus.
Can the submenu be added to the library?  Not sure if it is possible because of the limitations of Kodi or add-ons?
<a href="https://imgur.com/FfnVCdE"><img src="https://i.imgur.com/FfnVCdE.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
It's possible but I can see it getting confusing very quickly.

For instance, I have main menu items for Movies, TV, Videos. 
Videos opens the base dir of the library, but from there you can go into Movies/TV. It would only be possible to show the submenu that you entered the library from - so if you went Videos > Movies, then you would have the Videos submenu, but if you just went straight in Movies you would have the Movies submenu even though you are in the exact same section of the library. 

I think I'm pretty happy with the submenu options now - the submenu popup serves the purpose of having a menu available from the icon.

**Comment by Blurayx** [comment]
Great, glad you found a solution 😀

**Comment by Blurayx** [comment]
Is the submenu option  still in progress?

**Comment by jurialmunkey** [comment]
> 
> 
> Is the submenu option still in progress?

No, it is fully working. You can choose it as an action for a main menu item. 
https://github.com/jurialmunkey/skin.arctic.horizon/wiki/Submenus#submenu-popup

**Comment by jurialmunkey** [comment]
Also, I just added the ability to press "info" to open the submenu - i.e. if your remote has an info button, you can press the info button when the main menu is focused to open the submenu popup.

**Comment by Blurayx** [comment]
Great!
Thanks 😀
