### ISSUE TITLE
Animation performance hit with online information enabled

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#105]
Having "online information" on under "Customise info dialog lists" cause a noticeable performance drop of animations in the movie library (this is on by default).
For instance browsing quickly right through all your movies hitches quite often with this on.
This is also a noticeable slow down on the transition animation when you click on a movie to get to the "show information" screen and back again.

The interface is otherwise buttery smooth on my system (ryzen 2600, amd 580) :)

**Comment by drinfernoo** [comment]
This is known, and why there are options to disable features which cause such a performance impact.

**Comment by jurialmunkey** [comment]
Literally in the FAQ:
https://github.com/jurialmunkey/skin.arctic.horizon/wiki/FAQ#q-the-skin-feels-sluggish-how-can-i-improve-performance
