### ISSUE TITLE
Next Aired Library calendar: Can't navigate

### ISSUE THREAD

**Issue by 20mxm** [jurialmunkey/skin.arctic.horizon#11]
Can't navigate to the next screen.

<a href="https://imgur.com/VyHOaFy"><img src="https://i.imgur.com/VyHOaFy.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
Thanks for the bug report. I think this should be fix now in v0.1.3 - Can you test and confirm?
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.3

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/fdbc996e3f42fc2f4a28893c4d9111e2c3d5fd27

**Comment by 20mxm** [comment]
It's working 

Thanks
