### ISSUE TITLE
[Request] Showcase Widget Changes

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#110]
Would it be possible, while using Showcase Hub as a fullscreen widget, let the showcase use the fullscreen widget path, and the widget use the main menu item's Hub Widget?

This is different from the current implementation, because the showcase currently uses the Hub Widget, which means you can't have a widget below *without* having submenu items also defined.

My goal would be a fullscreen showcase widget, without submenu items, but showing the defined hub widget in the bottom row. It would also allow to have a "fallback" row (different from the showcase) in the instance that you *do* have submenu items that *don't* have a hub widget defined.

**Comment by Demonseeed** [comment]
Maybe a toggle that changes the behavior between the two implantations?

**Comment by drinfernoo** [comment]
If that's what he thinks is best, sure. The setup I actually wanted to do was:

|:----|
| Submenu |
| Hub Widget |```

**Comment by jurialmunkey** [comment]
So basically we would just need an additional widget selector for a "Background Widget" on the main menu?

The order of fallbacks would be:
| Widget | Order |
| :--- | :--- |
| Hub Background <br>(Fullscreen Fanart) |  1. Main Menu Background Widget <br>2. Main Menu Hub Widget <br>3. Fullscreen Widget |
| Hub Widgets <br>(Underneath Submenu) | 1. Submenu Hub Widget <br>2. Main Menu Hub Widget |

**Comment by drinfernoo** [comment]
That looks like it makes sense to me!

**Comment by Demonseeed** [comment]
To add my own input on Showcase Widget changes:

Would it be possible if you a fallback widget selected, “use showcase hub for full screen widget” selected - then the behavior is exactly the same as the Arctic Mirage screensaver (minus the animations)?

What I mean is setting the full screen widget to be whatever you want, but as you’d scroll through them, the widget row below it transitions to recommended movies based off the selected one.

**Comment by jurialmunkey** [comment]
@Demonseeed - So it would basically be triggered if you have no submenu items. That sounds like a good idea and I should be able to do that fairly easily.

**Comment by drinfernoo** [comment]
Sounds like it would be when there's no submenu items *or* hub widgets?

**Comment by Demonseeed** [comment]
@drinfernoo correct, when there is no submenu or hub widgets, and the user selects the menu item to display the fallback widget - then it would behave exactly as how the Arctic Mirage screensaver behaves (minus the zooming animation of course)

**Comment by jurialmunkey** [comment]
Ah okay I'm following. 

So these would be the possible scenarios:

**Background Widget w/ Recommendations**
User sets background/fullscreen widget
User deletes all submenu items
User deletes main menu hub widget

**Background Widget w/ User Set Hub Widget**
User sets background/fullscreen widget
User deletes all submenu items
User sets main menu hub widget

**Background Widget w/ Submenu and Hub Widget(s)**
User sets background/fullscreen widget
User sets submenu items
User sets main menu and/or submenu hub widgets

**Comment by Demonseeed** [comment]
Yeah, that sounds fantastic! 😄

**Comment by drinfernoo** [comment]
Sounds like that's all the combos to me @jurialmunkey 😅

**Comment by drinfernoo** [comment]
Sweet! Been waiting for this one so I can upgrade my main setup 👌

**Comment by jurialmunkey** [comment]
@drinfernoo - I'm fairly certain all the discussed scenarios should be possible now. The setup of the hub widget should be a lot clearer now that it is in separate dialog.
