### ISSUE TITLE
[Issue] Video Sources shows Time instead of Title

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#111]
Hey,
If i try to add a TV Show to the Library,  
Video Sources shows the actual Time instead of the Item title.

Same issue if i try to add a Show (exported from Netflix Plugin).

![DSC_0202](https://user-images.githubusercontent.com/17460997/78717240-9c838200-7920-11ea-9087-b5a2caf5c4ed.JPG)
![DSC_0201](https://user-images.githubusercontent.com/17460997/78717267-a5745380-7920-11ea-9a91-ec8e75892322.JPG)

**Comment by jurialmunkey** [comment]
Why are you using Sources instead of the actual Library?

**Comment by jurialmunkey** [comment]
You probably need to set a content type for the source.

**Comment by Andihawke** [comment]
i'm usually export a TV Show from Netflix addon and import it then from Video Sources(Content type is set to TV Shows)  in my Library. 

the issue is as seen from my images that the title shows the "actual time" not the folder title.

**Comment by jurialmunkey** [comment]
Should be fixed now.

**Comment by Andihawke** [comment]
I can partially confirm.
here it is ok now
![DSC_0205](https://user-images.githubusercontent.com/17460997/78723482-c7bf9e80-792b-11ea-8b2b-9c2b7284cc5e.JPG)

it's not ok here
![DSC_0204](https://user-images.githubusercontent.com/17460997/78723498-d312ca00-792b-11ea-9aa7-0bb5c2cc50ee.JPG)

**Comment by jurialmunkey** [comment]
It is supposed to show time in that view.
