### ISSUE TITLE
[Request] Submenu (popup) in Power Menu

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#112]
You can choose the option for a submenu in the Power Menu, but setting the contents hasn't been implemented... Maybe a thought ? I'd like to have that possibility.  Maybe several submenus in the power menu ? I use it now for shortcuts to addons, settings, file manager...

**Comment by jurialmunkey** [comment]
I don't really understand what your asking.

You can set the power menu in miscellaneous options.

It can't have submenu as it is a standalone list
