### ISSUE TITLE
[Bug] Plot Autoscroll sometimes cuts-off last line.

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#113]
Hey, 
it's possible to show the additional information (red colored text) already in the main view?
I currently have to select "Overview" on each item which is not so handy.
or is there no place for the field?

![DSC_0209](https://user-images.githubusercontent.com/17460997/78777416-c462fc00-7999-11ea-85ee-b33afd6522ca.JPG)

show here the additional information:
![DSC_0207](https://user-images.githubusercontent.com/17460997/78775532-a8119000-7996-11ea-84fd-b7b110d4f4be.JPG)

**Comment by jurialmunkey** [comment]
You just need to turn on plot autoscroll in skin settings. Netflix addon just adds that line to the plot field. It's not a separate label.

**Comment by Andihawke** [comment]
aaa great, thank you for your efforts!

**Comment by jurialmunkey** [comment]
Ah I just realised that sometimes the last line of the plot is cut off when scrolling.
