### ISSUE TITLE
Programme Guide Overlay

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#114]
hey jurialmunkey, if there are less then 9 channels on the Guide, the Overlay is bigger than the channel list. its not so important but maybe you wish to fix it.
![DSC_0210](https://user-images.githubusercontent.com/17460997/78841860-c9a66200-79fe-11ea-98c6-e8f2a9aa10cb.JPG)

**Comment by jurialmunkey** [comment]
Yep can confirm.

I'm not sure if it is possible to fix actually. Kodi just allows for setting an image as progress overlay - there aren't any controls for how it is displayed. I might be able to use a variable to change to a different height image based on number of channels - though I'm not even sure if I can get number of channels from the container or not. 

I'll have a look but I'm doubtful that it will be able to be fixed.

**Comment by jurialmunkey** [comment]
Unfortunately I can't fix it.  The texture doesn't accept a variable.
