### ISSUE TITLE
[Bug] No Next up Home Screen widgets

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#119]
Not sure if it's a skin or plugin.video.themoviedb.helper issue
when staring up Kodi. There is no Next up/themoviedb.helper widgets. I have to reload the skin to get it back.

<a href="https://imgur.com/YXDSQAK"><img src="https://i.imgur.com/YXDSQAK.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/3XFyJ4r"><img src="https://i.imgur.com/3XFyJ4r.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/BWxUehG"><img src="https://i.imgur.com/BWxUehG.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Hmm, very odd. I think it must either be a Kodi or TMDbHelper issue (not the skin). My only guess is that timezone data is available immediately on startup. I'll look into it some more and see if I can figure out the cause.

**Comment by Blurayx** [comment]
Not sure if it's related. TMDbHelper: "Get additional details from the local Kodi library database" stop working

**Comment by Blurayx** [comment]
> Hmm, very odd. I think it must either be a Kodi or TMDbHelper issue (not the skin). My only guess is that timezone data isn't available immediately on startup. I'll look into it some more and see if I can figure out the cause.
UPDATE:
Definitely Artic Horizon. No issues with AZ2

**Comment by jurialmunkey** [comment]
Ah, okay - if it is only happening here with the same widgets, then it must be a skin issue. I have no idea what the cause is though - really odd that it is only happening with these widgets.

**Comment by jurialmunkey** [comment]
@Blurayx - It was an issue with TMDbHelper (well sort of). The Kodi library isn't ready at startup, so when the plugin tries to get info about the DB it just gets an empty list and it looks like there aren't any shows in the library. I've fixed it by adding a retry attempt - plugin will now try to connect to Kodi DB up to five times before giving up.

Can you test v2.4.10 of TMDbHelper? It should fix this issue. If it doesn't can you let me know, and I'll tweak the retry interval a bit to be longer.

**Comment by Blurayx** [comment]
Working perfectly!
Thanks 😀

**Comment by jurialmunkey** [comment]
Ah! I'm so glad that it's working! Took a bit of digging to figure out what the issue was.

**Comment by Blurayx** [comment]
I was thinking it must have been a nightmare to fix
