### ISSUE TITLE
[Question] How do you get to submenu ?

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#12]
Skin looks really nice. I love the use of clearart.

I remember you discussing your design on the Kodi Forum and it was logical, but I can't reach the submenu...

By the way, it's early days for your skin, do you really want this type of feedback now allready ? :p

**Comment by drinfernoo** [comment]
https://forum.kodi.tv/showthread.php?tid=351756&pid=2932137#pid2932137

**Comment by DaisyF8** [comment]
Thx Doc
