### ISSUE TITLE
Transition Issue showcase/submenu hub with background video enabled

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#120]
Hi jurialmunkey, many thanks for your efforts!!!
have found a little issue/bug on showcase/submenu hub. 

with "Display now playing video in background" enabled, the transition between submenu and widget below is interrupted/not smooth.

I think it's not that easy to create a fluid transition here.

I don't use that anyway, but maybe you want to check it out.

**Comment by jurialmunkey** [comment]
Ah yep I see the issue. Should be fixed now. Thanks for the report - I wouldn't have noticed since I usually have background video disabled.
