### ISSUE TITLE
TV Guide channel icons

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon#122]
Hi. Not sure if this is an issue with my .png tv channel icons, but many of them are oversized in the TV guide and overlap channel names. Those same oversized icons look fine in the osd when flicking through channels. Thanks.
![DE01FAEF-E77F-40E5-BC86-8FAAF54C8E57](https://user-images.githubusercontent.com/62660160/79027326-b83a9280-7b83-11ea-9dca-2b7f73851ebb.jpeg) 
![48303801-F55E-4176-98CA-DD637E58CF3E](https://user-images.githubusercontent.com/62660160/79027097-e2d81b80-7b82-11ea-9a8a-6ebd2c2f5168.jpeg)

![FD3F8293-BD72-4FEB-AA99-865C89225F10](https://user-images.githubusercontent.com/62660160/79027093-dd7ad100-7b82-11ea-8692-8bdbb8a8deda.jpeg)

**Comment by jurialmunkey** [comment]
In v0.2.0 I've added an option to hide channel names if the channel icon is visible. 
`Skin Settings > Live TV / PVR > Hide channel name if icon is available`


If you want both text name and icon to be visible and not overlap, then you will need to use channel icons that are less wide.

**Comment by Tee77** [comment]
Understood. Thanks man.

**Comment by sammy2142** [comment]
I have created a pack of transparent uk channel icons here if your interested:
https://forum.kodi.tv/showthread.php?tid=352988
They have all been padded and resized to match the recommended Kodi specs

**Comment by Tee77** [comment]
Hey, thanks Sammy. I actually already use Jasmeet’s logos but will give these a try. Cheers.
