### ISSUE TITLE
Info window empty for locally scrapped movies

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/skin.arctic.horizon#123]
For locally scraped movies (.nfo) the movie information window is almost empty. Only the Title and the plot is shown. Sometimes even the plot is not shown and there is just empty space.
The actors for that movies are not shown at all if they not exists in TMDB. If they exists when you click over the actor it not show the actual movies that you have with this actor in your local library, instead it show what is present in TMDB.
I think that is wrong since it prevent all people with locally scrapped libraries to use that skin.

**Comment by jurialmunkey** [comment]
No it's not. Fix your library. This is with TMDbHelper completely disabled and just using my library info.

![Honeyview_screenshot732](https://user-images.githubusercontent.com/4618719/79040924-4d469580-7c2f-11ea-8d08-54c292eaf7c9.jpg)
![Honeyview_screenshot733](https://user-images.githubusercontent.com/4618719/79040926-4e77c280-7c2f-11ea-98f3-493ab30b3996.jpg)
![Honeyview_screenshot729](https://user-images.githubusercontent.com/4618719/79040930-50418600-7c2f-11ea-9c30-a1df99f464d7.jpg)

**Comment by DimitarCC** [comment]
OK. For you seems everything is user problem or local library problem. My local movies are east asian movies and they ARE NOT in tmdb. In that case your plugin returns nothing for plot and actors.
Even if it return something when click on actor it doesnt show the movies i had with this actor since there is no info in tmdb. I dont get it how can i fix something that doesnt exist. :(

**Comment by jurialmunkey** [comment]
The screenshots above are WITHOUT tmdbhelper. If you have your library setup properly with info, then the skin will show that info.

**Comment by jurialmunkey** [comment]
The skin doesn't use TMDbHelper to get actors or plot - it uses local library info.
