### ISSUE TITLE
[Request] Offline mirage screensaver (limit omdb api requests etc)

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#124]
Hi using the basic slideshow for arctic mirage screensaver it loads the omdb ratings (if you have entered an api key) automatically.
Is it possible to have an offline screensaver option? As omdb currently has a limit on the number of requests, which could be reached on always on devices such as the raspberry pi etc

Regards

**Comment by jurialmunkey** [comment]
OMDb details are cached for a minimum of 14 days once the ratings are retrieved. So you should only have as many requests as there are items in the list that haven't previously been cached.

Unless you are using an online list with 1000s of items or that is constantly changing, then you shouldn't hit the limit (unless you are using some tool to delete simplecache - which I really strongly recommend AGAINST).

**Comment by sammy2142** [comment]
Awesome - I wasn't aware of the cache.
There still seems to be a small delay of a second or so when it loads cached data - so I assumed it was making a new query each time (after opening and closing the movies section and revisiting the same movie).

**Comment by jurialmunkey** [comment]
There's a little bit of delay for the service monitor to kick in. Basically when you focus a widget, there's a property set which tells the service monitor which control ID to look at - so there's a bit of a delay whilst that property is set.

Once you're in the list, the cached details should show up fairly quickly most of the time. Though the service monitor does set quite a few properties, so it can take a moment depending on the system. If you look at the wiki you can see just how many properties it sets:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#properties-returned
