### ISSUE TITLE
[Request] Timer/Record series option

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#125]
Hi is it possible to add the timer/record series button when you click on a show in the tvguide.
This is useful because it auto populates all the fields (show name, channel etc) when setting up a series recording.
![timer](https://user-images.githubusercontent.com/5837771/79045394-c7acf080-7c02-11ea-9b14-9545a4a10d6b.png)
![recording timer](https://user-images.githubusercontent.com/5837771/79045423-ec08cd00-7c02-11ea-84f4-916093e21a53.png)

**Comment by jurialmunkey** [comment]
Ah not sure how I missed that one. Should be added now.

**Comment by sammy2142** [comment]
Thanks - that was fast
