### ISSUE TITLE
[Issue] No more option to deactivate a single widget

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#126]
hey, as the title says.
I think this function already existed.
![DSC_0215](https://user-images.githubusercontent.com/17460997/79055926-3f097100-7c51-11ea-86d9-a2f67c026646.JPG)

**Comment by drinfernoo** [comment]
This skin doesn't support disabling widgets. If you don't need them any longer, delete them.

**Comment by Andihawke** [comment]
ahhh ok thanks for the info

**Comment by jurialmunkey** [comment]
Yeah it was an oversight to even have the option in there at all since disabling the widgets breaks things. If I can find a way to make it work, I'll re-add it back - but for the time being you'll just have to delete unused widgets.
