### ISSUE TITLE
[Question] Move to groups from channels list

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#127]
Is there any way to move to groups in PVR other than moving to the start or end of the list? Currently moving left and right in the list just moves to current/next EPG entry for the channel. Could moving left/right once already at the edge be configured to move to groups? Apart from that, is there any key in the keyboard that does it?

**Comment by jurialmunkey** [comment]
Not currently but it should be fairly easy to implement.

There is a default button in PVR EPG Guide to change channel group (it's "g" on keyboard)
https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml#L251

However, no default button for PVR Channels view (which is what you're talking about). You could map the command though:
https://kodi.wiki/view/Keymap

**Comment by juanma-cvega** [comment]
Ok, I'll take a look at the mapping function. Thanks.

**Comment by juanma-cvega** [comment]
I just tested the function and it works fine. Any chance the skin can remember the position in the list the cursor was at when moving back from groups?

**Comment by jurialmunkey** [comment]
Should be fixed now.

**Comment by juanma-cvega** [comment]
Yes, it works perfectly. Thanks!
