### ISSUE TITLE
[Question] Accessing submenus

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#128]
In other skins you can access submenus by going left/up in the menu, depending on whether the menu is in vertical or horizontal mode. In Horizon it doesn't work, I guess because of the way the layout is created. So, is through widgets the only way to get to submenus?
I was thinking if it could be possible to add the submenus as a sliding vertical bar that slides from the left? The current menu does it already when it disappears after moving to widgets so it could be a way to provide submenus without being very intrusive with the current layout.

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/skin.arctic.horizon/wiki/Submenus

**Comment by juanma-cvega** [comment]
Ok, thanks! I guess I should visit more often the wiki. I'll take a look to see which one fits better my needs. In any case, is the option I described even possible? Just in case @jurialmunkey may consider it if it fits with the current structure.

**Comment by jurialmunkey** [comment]
The problem with left press is that it is used to wrap around the widgets.

If you have an Info button on your remote (or "i" on keyboard) - you can press info on a main menu item and it will popup the submenu.
