### ISSUE TITLE
[Issue] Similar button

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#129]
Similar button on movies doesn't work when the user has "use online information unticked" under custom info dialog lists.
Should this search be allowed (since its a manual search) - or should the similar button be hidden when this option is disabled?

**Comment by jurialmunkey** [comment]
Hmm, that's a really good question - I completely didn't think about the effect of that setting on the similar button. 

Maybe it should still work but only do local lookups (I should be able to do Director, Studio and Year with local info but maybe not Similar and Recommended). I think that's probably what is expected with online lookups disabled.
