### ISSUE TITLE
[Feature] Option to disable episode thumbs

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#13]
An option to disable episode thumbs is needed to prevent spoilers. Should replace with fanart/landscape when enabled.

**Comment by drinfernoo** [comment]
This should already be controlled by Kodi's "spoiler" settings, shouldn't it?

**Comment by jurialmunkey** [comment]
> 
> 
> This should already be controlled by Kodi's "spoiler" settings, shouldn't it?

Good point. Though I think I still need to check for the spoiler setting to determine what image to show.

**Comment by rijs43** [comment]
When can we expect this? :)

Thanks

**Comment by jurialmunkey** [comment]
Pretty sure that this already works
`Settings > Media > Videos > Show information for unwatched items`
