### ISSUE TITLE
[Question/Feature]Episode Thumbnails

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#130]
is there any way to hide episode thumbnails?
There was one episode a character that left the show but made a one-off appearance. This spoiled it for me.

<a href="https://imgur.com/IoMUZt6"><img src="https://i.imgur.com/IoMUZt6.png" title="source: imgur.com" /></a>

Concetp: using fanart instead, if possible.
<a href="https://imgur.com/RiWklqm"><img src="https://i.imgur.com/RiWklqm.jpg" title="source: imgur.com" /></a>
Did you see the Random positions:Navigating Up/Down #118 bug?
Thanks

**Comment by drinfernoo** [comment]
Hide episode thumb for unwatched items:

![Screenshot_20200414-102221](https://user-images.githubusercontent.com/2319508/79254665-ecd77400-7e39-11ea-9ca2-b9535e681ba1.jpg)

**Comment by Blurayx** [comment]
Thanks. I do like the idea of fanart or customized thumbnail if possible.

**Comment by drinfernoo** [comment]
@Blurayx When using the option I pointed out, fanart is used instead.

**Comment by Blurayx** [comment]
Ok

**Comment by jurialmunkey** [comment]
Should be fixed now.

**Comment by Blurayx** [comment]
working now, Didn't realise it was a bug 😀

<a href="https://imgur.com/jZxPTma"><img src="https://i.imgur.com/jZxPTma.png" title="source: imgur.com" /></a>
Thanks
