### ISSUE TITLE
Trailer button not showing

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#132]
The trailer button for movies/tv shows I haven't seen before doesn't show. After Kodi has seen the movie/tv show, the trailer button shows up but only after refreshing the list and not always. I guess the issue is related to needing to scrap the information first? 
EDIT: forgot to say, this is while navigating through TheMovieDB Helper

**Comment by jurialmunkey** [comment]
Yeah it's just a TMDbHelper thing - the Trailer is part of the detailed info. When you open a list, the service monitor caches the details when an item is highlighted.

The commit I just pushed will make the trailer button fall back to the service monitor trailer.

**Comment by juanma-cvega** [comment]
Just tested it and it works. The trailer button shows up after a second or two. There are still some where it doesn't work though. Are those just because a trailer couldn't be found? Is it clever enough to know when a trailer is available?

**Comment by jurialmunkey** [comment]
> 
> 
> Just tested it and it works. The trailer button shows up after a second or two. There are still some where it doesn't work though. Are those just because a trailer couldn't be found? Is it clever enough to know when a trailer is available?

Yeah if it doesn't show then that means no trailer found by TMDbHelper. (it just means the TMDB API didn't return any youtube videos for that item).
