### ISSUE TITLE
Play Button Showcase Hub

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#134]
hey jurialmunkey, today i've played arround with the showcase hub and noticed the following.

the play button only works if i add a hub widget of the type e.g. Recently Added Episodes but not with e.g. Recently Added TV Shows.
(Shouldn't it open the season view with Recently Added TV Shows?!)

![DSC_0223](https://user-images.githubusercontent.com/17460997/79619243-a4a3a480-810c-11ea-8669-042b12a66e66.JPG)

**Comment by jurialmunkey** [comment]
Ah, yep I'll need to add something to switch to a "Browse" button if it's a folder.
