### ISSUE TITLE
[Issue] Show context menu

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#135]
hi, a longpress on the "next aired" entry from channel list doesn't open the context menu. 

thanks again for this great skin.

![DSC_0223](https://user-images.githubusercontent.com/17460997/79671413-6371ca00-81ca-11ea-9944-9f15f444948b.JPG)

**Comment by jurialmunkey** [comment]
Can't do anything about it unfortunately. It's a fake list item that displays the next properties of the first item. If you opened context menu, it would be for the left side which could be confusing.
