### ISSUE TITLE
[Bug] Episode position in combined view resets after watching.

### ISSUE THREAD

**Issue by Frusciantism** [jurialmunkey/skin.arctic.horizon#139]
Hey,
Fantastic skin, congratulations and thanks.

The problem is when I’m watching series, when the episode ends it automatically returns to the season selection session, this forced me to scrool through all the episodes again until the next one, normally I should go back to the finished episode being faster to move on to the next.

I made a short video showing the problem

https://streamable.com/cfkxbl

**Comment by jurialmunkey** [comment]
I haven't forgotten about this issue - I can confirm it happens but I'm still searching for a solution. Unfortunately it is proving quite difficult to fix...

**Comment by jurialmunkey** [comment]
Unfortunately I don't think that this is possible to fix without some excessively complex workaround. The only "solution" is to disable the integrated view unfortunately.
