### ISSUE TITLE
[Request] Alphabet strip

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#14]
Any plans on adding Alphabet strip?

Thanks

**Comment by jurialmunkey** [comment]
Yeah I've got the code there. I was testing some different navigation ondown but it didn't work out and I forgot to reimplement the alphabet strip. I'll look at readding it.

**Comment by jurialmunkey** [comment]
Re-added in v0.1.9
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.9

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/a3825bccc757165cd1d4edc2d4b9e9bc9395ad3a
