### ISSUE TITLE
[Feature Request] Clearlogo on "Icon" Widgets

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#141]
As the title, would it be possible to show clearlogo on the "icon" widget aspect, if it's available?

**Comment by jurialmunkey** [comment]
It should already do this... I might've regressed something somewhere, let me double check as I definitely already implemented this feature.

**Comment by jurialmunkey** [comment]
Yep, working fine for me...

![Honeyview_screenshot747](https://user-images.githubusercontent.com/4618719/80263457-0c8d5880-86d4-11ea-9f0d-f1d0d7495abc.jpg)

**Comment by drinfernoo** [comment]
@jurialmunkey Oh, maybe it shows it only if `icon` is empty?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Oh, maybe it shows it only if `icon` is empty?

Icon is set for every item. Also, Icon and Art(thumb) need to be set for an item to have other artwork types.

**Comment by jurialmunkey** [comment]
The only reason it wouldn't show is if both Art(poster) and Art(fanart) are empty (then it shows default icon). However, it would be very strange for an item to have Art(clearlogo) and not Art(poster).

**Comment by drinfernoo** [comment]
@jurialmunkey I have made a shortcut group with AutoWidget, and assigned clearlogo to the items, but icon is shown instead.

**Comment by jurialmunkey** [comment]
@drinfernoo - Can you try also setting Art(poster) to something and see if that works? If Art(poster) and Art(fanart) are both empty, the skin thinks that the item has a default icon

**Comment by drinfernoo** [comment]
@jurialmunkey Ah, it could be that! I'll have to give it a shot, but I bet you're right. I'm looking through your files and see that it should just be `$VAR[Image_Clearlogo] 🤔

**Comment by jurialmunkey** [comment]
If you look at `Object_Artwork` you will see that there are three different images with different conditions. Default icon is show if $EXP[Exp_DefaultIcon] or $EXP[Exp_SpecialIcon] conditions are met.

You can see the rules for these expressions here:
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/shortcuts/skinvariables.json#L60-L71

**Comment by jurialmunkey** [comment]
Also, note that if you haven't setArt for thumb, then you can't set any other artwork types.

**Comment by drinfernoo** [comment]
Ok, you're right :ok_hand: I was able to get the clearlogo to show by setting poster :sweat_smile:
