### ISSUE TITLE
TV channels showing channel name when EPG is empty

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#142]
I just realised in TV channels, when there is no EPG for a channel, instead of showing an empty label it shows the name of the channel. In Guide this doesn't happen, it just shows an empty space.

**Comment by jurialmunkey** [comment]
It's intentional. I found it looked weird if there was no label. EPG it isn' as much a concern because the items are different sizes and position. However, with channels I found it looked like the actual channel  was blank and unplayable rather than just missing epg data.
