### ISSUE TITLE
[Request] Video Progress Bar

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#143]
hey jurialmunkey, 
is it possible to implement the video progress bar in the same way as in the estuary skin. there you can rewind and fast forward directly on the bar (even when the video is paused). i think that would be another improvement for the skin. what do you think about it?

![DSC_0235](https://user-images.githubusercontent.com/17460997/80314217-8a468680-87f0-11ea-8cf3-56e0c6fa2b5d.png)

by the way, thanks for your awesome work on the wall view. it's amazing!!!

**Comment by drinfernoo** [comment]
You can already do this... By scrubbing on the bar that is currently there.

**Comment by jurialmunkey** [comment]
Do you mean using the mouse? You should already be able click on the seek bar to seek to that position.

**Comment by Andihawke** [comment]
hi, no i mean using the remote control.

**Comment by jurialmunkey** [comment]
I just press left/right or up/down on my remote to skip forwards/backwards...

**Comment by Andihawke** [comment]
hey, ok thanks for the explanation.
