### ISSUE TITLE
'Title' subwidgets are labeled as 'recommendations'.

### ISSUE THREAD

**Issue by Omnomanor** [jurialmunkey/skin.arctic.horizon#147]
I have set my movies and tv shows subwidgets to title (and I use submenu hubs). The label above the horizontal list shows the label 'recommendations'. I did not test other types of listings.

**Comment by jurialmunkey** [comment]
It works fine for me - I can't replicate. Recommendations are only shown if there is no widget set.

![Honeyview_screenshot752](https://user-images.githubusercontent.com/4618719/80546064-137bda00-89f8-11ea-94ab-f713e6841846.jpg)

**Comment by jurialmunkey** [comment]
Ah I see you said "Submenu Hub" not "Showcase Hub"... Yeah I can see the problem. Working on a fix.

**Comment by Omnomanor** [comment]
On the current version (0.2.38?)/load of the skin the labels read 'spotlight'.

**Comment by jurialmunkey** [comment]
Yeah I just changed that to the fallback label until I fix it properly.
