### ISSUE TITLE
[Bug] Background fanart / widgets on home not autoscrolling.

### ISSUE THREAD

**Issue by baruchin** [jurialmunkey/skin.arctic.horizon#148]
On home screen, while using a single spotlight widget, and focus on side menu, widget start autoscrolling, but with no background fanart, nor ratings. This, while using Overlay as a background setting. I need to change background setting to Blur to get it working again. Sometimes, even on Blur, and I don't know if randomly or while navigating up and down through different homescreen sections, this behavior replicates, and need to change background to Overlay, and then to Blur, to get fanart scrolling again on single widget in home screen.

**Comment by jurialmunkey** [comment]
Pretty sure this is fixed now.
