### ISSUE TITLE
[Bug] info/Movie

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#149]
Movie Info not working all I get is the busy loader icon. this only happens with movies. TV info works fine. No issues with AZ2.
<a href="https://imgur.com/2Wgbfmp"><img src="https://i.imgur.com/2Wgbfmp.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/6Bc3NNf"><img src="https://i.imgur.com/6Bc3NNf.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Have you tried with the latest version of tmdb helper from github? I think it might be the same bug as the person info one which I fixed.

**Comment by Blurayx** [comment]
Yes, I'm using the latest tmdb helper.

**Comment by jurialmunkey** [comment]
> 
> 
> Yes, I'm using the latest tmdb helper.

Got a debug log? It is working fine for me:

![Honeyview_screenshot758](https://user-images.githubusercontent.com/4618719/80896113-3b3bac80-8d2e-11ea-8330-556817e86830.jpg)
![Honeyview_screenshot759](https://user-images.githubusercontent.com/4618719/80896114-3c6cd980-8d2e-11ea-8c76-e4f1000d4e17.jpg)

**Comment by Blurayx** [comment]
it's been a long time since done a debug log. I will try 🙂

**Comment by Blurayx** [comment]
I hope this is right

https://paste.kodi.tv/emelicunev

**Comment by jurialmunkey** [comment]
I can see the issue -- the library scraper you are using is putting the TMDb ID in the IMDbNumber field. Obviously that is the wrong IMDb ID so there's nothing to lookup.

I've added a work around in the skin that will hopefully capture these instances -- luckily IMDb puts a `tt` at the front of all their IDs, so I can check to see if it starts with `tt` to confirm it is actually an IMDb ID.

Can you test latest version of the skin (v0.2.36) and confirm if it is now working properly for you?

**Comment by Blurayx** [comment]
working 😀

Thank you
