### ISSUE TITLE
[Bug] Artist Slideshow 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#15]
Artist Slideshow update Alert when playing music.

<a href="https://imgur.com/TSpsvIj"><img src="https://i.imgur.com/TSpsvIj.png" title="source: imgur.com" /></a>

working on AZ2
<a href="https://imgur.com/gaAk6Lv"><img src="https://i.imgur.com/gaAk6Lv.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Ah I forgot about that change. Should be fixed as of 0.1.7
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.7

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/90f528bcbd19ed425108676d21bb28f146574b39

**Comment by Blurayx** [comment]
woking now

Thanks
