### ISSUE TITLE
Access to android apps

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#150]
Is there any way to access android apps when on an android device? Right now I change to Estuary when I need one and then add it as a favorite.

**Comment by drinfernoo** [comment]
You can have a widget of them: `Add-on -> Android apps`

**Comment by juanma-cvega** [comment]
I may be blind but I couldn't find the `Android apps` option under `Add-on`. I'll check again tomorrow and I'll just close it if it's there.

**Comment by drinfernoo** [comment]
> I may be blind but I couldn't find the `Android apps` option under `Add-on`. I'll check again tomorrow and I'll just close it if it's there.

You can only see it when you're picking a widget, but not a menu item.

**Comment by jurialmunkey** [comment]
Can you test latest? Should have a shortcut under `Action > Add-ons > Programs > Android Apps`

Unfortunately looks like there isn't any way to browse Android Apps in skinshortcuts, so only option is to favourite them first - but at least this will make it so you can add the menu shortcut to the folder.

**Comment by drinfernoo** [comment]
@jurialmunkey A suggestion: Many other skins just put it in `Add-ons -> Android Apps`... that's why I suggested it there 😅 Just might be a good move to put it there for consistency with other skins.

**Comment by jurialmunkey** [comment]
Done.
