### ISSUE TITLE
noop action in menu item doesn't let you move through the menu when selected

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#151]
I have set the 'Settings' menu option with a noop action as the options show up as widgets anyway. But if I press the button I then have to press 'Back' so I can change to a different option as I cannot navigate otherwise.

**Comment by drinfernoo** [comment]
Well, then don't use `noop` 😅 Maybe just let it open Settings or a submenu?

**Comment by juanma-cvega** [comment]
Yes, in this case it would be as simple as that, I agree 😄 . In my case, I have another menu item where it's just a placeholder to a widget with different shortcuts so the button doesn't match to any specific thing. It's a small thing, really. I just reported it in case it's a simple thing to fix.

**Comment by jurialmunkey** [comment]
Noop is technically not supported in Kodi anymore - but that's beside the point. 

Maybe map the action to `Right` so that clicking will focus the widgets? The other action you could do is `Setfocus(3992)` to refocus the menu.

**Comment by drinfernoo** [comment]
> Noop is technically not supported in Kodi anymore - but that's beside the point.
> 
> Maybe map the action to `Right` so that clicking will focus the widgets? The other action you could do is `Setfocus(3992)` to refocus the menu.

Both of those are great suggestions! I wouldn't have ever thought of that, and I even have a `noop` item on my menu 😅

**Comment by juanma-cvega** [comment]
I ended up using the `Setfocus(3992)` solution. Just adding `Right` didn't fix it so I guess the command must be named something else.

**Comment by jurialmunkey** [comment]
Ah, actually now that I think about it `Right` won't work because you would need to return focus to 3992 first and you can't stack two commands using skinshortcuts dialog (you can do it with overrides, but not directly from the UI).
