### ISSUE TITLE
[Question] Next Aired GUI

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#154]
Have you thought of a concept for Next Aired GUI?

Thanks

**Comment by jurialmunkey** [comment]
Do you mean for the Next Aired addon? I thought that didn't work properly anymore?

What's the advantage of using that over the implementation using TMDbHelper? I'd rather add any missing features to TMDbHelper if posssible instead.

**Comment by Blurayx** [comment]
sorry to confuse you.
<a href="https://imgur.com/CJPM6np"><img src="https://i.imgur.com/CJPM6np.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Yeah I know it is using the default. 

My question is what is the advantage of using that over the one using TMDbHelper? 
What feature do you use from Next Aired that TMDbHelper doesn't have?
Or is the issue more about loading times?

I'm trying to get away from scripted windows as much as possible (e.g. Next Aired, Global Search, Extended Info). These scripted windows are really inflexible and are a pain to maintain, so where possible I'm trying to replace them using custom native windows and features in TMDbHelper.

If there's a feature I can't replicate, then I'm happy to skin Next Aired - but I'd like to have a go at including it natively first.

**Comment by Blurayx** [comment]
When I asked you a question regarding the Next Aired GUI, You jumped straight to another question without answering the first question, which got me confused because Next Aired works perfectly.
Now that's cleared up, let's start from the beginning. 
First of all I didn't know TMDbHelper can be used instead of Next Aired. so I wouldn't know the advantages of using TMDbHelper. How do I enable it?

**Comment by jurialmunkey** [comment]
> 
> 
> When I asked you a question regarding the Next Aired GUI, You jumped straight to another question without answering the first question, which got me confused because Next Aired works perfectly.
> Now that's cleared up, let's start from the beginning.
> First of all I didn't know TMDbHelper can be used instead of Next Aired. so I wouldn't know the advantages of using TMDbHelper. How do I enable it?

Ah! I see the confusion now! I was under the impression that there was an issue with timezones not working correctly in Next Aired -- and so I was confused myself why you'd want a skin for a broken addon.

You can add a shortcut for the TMDbHelper version of Next Aired in the home customisation dialog.
`Choose shortcut > Common > Next Aired (Library)`

It is definitely in it's infancy, so I'm expecting plenty of issues with it - which is why it would be great to get some feedback about what works and what is missing from people who would normally use NextAired.

**Comment by Blurayx** [comment]
Thanks, I've got it up and running!!! 😀
Great job so far considering it's in its infancy👍
I'll report back and create a new feature request.

**Comment by jurialmunkey** [comment]
> I'll report back and create a new feature request.

Yes please do!
