### ISSUE TITLE
Hide channel name if icon is available leaves too much space when enabled

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#156]
Could the space left for the channel icon when the option `Hide channel name if icon is available` is enabled be reduced? The option leaves a gap when enabled. 
Maybe another approach to the way name and icon are handled could be used? There are some channels which names are too long and they are cut by the icon when they are present but then, if too much space is reserved to fix this problem, the space left is unused when the names are hidden. 
<img width="1440" alt="Screenshot 2020-05-06 at 10 37 50" src="https://user-images.githubusercontent.com/6765894/81157095-ec3c8400-8f86-11ea-83d5-ccd3aee7d1d9.png">

**Comment by jurialmunkey** [comment]
That option was added specifically for icon packs that are very wide. See this issue: https://github.com/jurialmunkey/skin.arctic.horizon/issues/122

So if I reduce the gap then it defeats the purpose of that setting. 

Also, I had experimented with an icon only version of the EPG in AZ2. The problem is that by shortening the width, it also shortens the date so you can't read it. I only want options that work across both EPG and Channels windows.

**Comment by juanma-cvega** [comment]
Ok, I guess that depends on the size of the icons you use then. In my case, all the icons have the same size to make it more consistent but the name of the channel is something that depends on the channel itself so showing the channel name for some of them is useless because they all start with the same word (for instance Movistar Liga de campeones, Movistar Liga de campeones 1, Movistar La liga, Movistar Drama, etc). 
Would it work making a fourth column to separate icon from name? So if you hide the name it would hide the whole column. There is always the information at the top left that shows the name of the channel in case the icon is not available and the name of the channel is hidden.

**Comment by jurialmunkey** [comment]
> Would it work making a fourth column to separate icon from name?  So if you hide the name it would hide the whole column.

You can't do that in the EPG Guide unfortunately - at least not without also reducing the width of the date below the group selector which will cause it to be cut-off. See this screenshot from AZ2

![](https://i.imgur.com/w1tIuQ2.png)
