### ISSUE TITLE
[Bug] Movie fails to play (wrong path/ Window Translator error) 

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#159]
Hi
I'm getting an odd issue using this skin.
One movie path is causing errors on the show info screen. When attempting to push the play button on the showinfo screen it produces these errors:
>1145041792   ERROR: CVideoPlayer::OpenInputStream - error opening [smb://192.168.0.4/Movies III/Harry Potter and the Deathly Hallows]
> 1936914880   ERROR: Window Translator: Can't find window Part 1 (2010)/Harry Potter and the Deathly Hallows

The correct path is: \\MEDIA-SERVER\Movies III\Harry Potter and the Deathly Hallows, Part 1 (2010)\Harry Potter and the Deathly Hallows, Part 1 (2010).mkv

The comma in the path name seems to be causing issues.

The movie plays fine from the showinfo screen in estuary and it plays fine in arctic horizon if I just push the play button on my remote instead of going through the showinfo screen.

Regards

**Comment by jurialmunkey** [comment]
Comma in a file/path name is a bad idea.

It's because the filename is passed to TMDbHelper using the RunScript() command. Scripts use the comma character to separate arguments.

There's not a lot that can be done other than say that even though you _can_ use commas in filenames, it's a bad idea since commas are frequently considered a special character.

**Comment by sammy2142** [comment]
I found this here - does it help?

> $ESCINFO[] should be used when passing an infolabel to a built-in function, when this infolabel is likely to contain commas (,) and/or quotes (").
> 
> eg: PlayMedia($INFO[ListItem.Path]) might return: PlayMedia(/some/path/with_a_file_that_includes,a_comma.avi)
> 
> This will be read by the builtin function generator as PlayMedia called with 2 parameters: "/some/path/with_a_file_that_includes" and "a_comma.avi".
> 
> If you use PlayMedia($ESCINFO[ListItem.Path]) however, it will make sure that whatever is returned by the infolabel is sent on to the builtin as a single parameter.

https://kodi.wiki/view/Label_Parsing

Regards

**Comment by jurialmunkey** [comment]
Already tried with ESCINFO - it doesn't appear to pass anything to the script.

**Comment by jurialmunkey** [comment]
@sammy2142 - Can you test latest? Need new version of TMDbHelper also.

**Comment by sammy2142** [comment]
Hi unfortunately I'm still getting it with the latest version of each:

> 2020-05-07 14:45:06.812 T:10244   ERROR: Window Translator: Can't find window Part 1 (2010)/Harry Potter and the Deathly Hallows
> 2020-05-07 14:45:09.774 T:10244  NOTICE: VideoPlayer::OpenFile: smb://media-server/Movies III/Harry Potter and the Deathly Hallows
> 2020-05-07 14:45:09.774 T:8512  NOTICE: Creating InputStream
> 2020-05-07 14:45:09.777 T:8512   ERROR: CVideoPlayer::OpenInputStream - error opening [smb://media-server/Movies III/Harry Potter and the Deathly Hallows]
> 2020-05-07 14:45:09.777 T:8512  NOTICE: CVideoPlayer::OnExit()

Regards

**Comment by jurialmunkey** [comment]
@sammy2142 - Ah I forgot to re-escape it on the other end. Can you try again with latest TMDbHelper and see if it is working now?

**Comment by sammy2142** [comment]
Its working great now thanks :)
