### ISSUE TITLE
[Bug] overview & options

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#16]
Nothing happens when I click on overview or options

<a href="https://imgur.com/4hmeSo3"><img src="https://i.imgur.com/4hmeSo3.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Duplicate of this issue: https://github.com/jurialmunkey/skin.arctic.horizon/issues/10

**Comment by jurialmunkey** [comment]
Fixed in v0.1.10 - https://github.com/jurialmunkey/skin.arctic.horizon/commit/27ab0d933c57ef4fb639ebd5673adcf09fa41b5b
