### ISSUE TITLE
[Bug]Menu after selecting video to play does not always work for TV Shows

### ISSUE THREAD

**Issue by xen0m0rph2020** [jurialmunkey/skin.arctic.horizon#161]
In Kodi settings I have it set to display menu when selecting a video to play rather then playing the video automatically. 
This works on movies but in TV shows it does not show the menu.

**Comment by drinfernoo** [comment]
What menu are you hoping for it to display? Considering that TV Shows aren't playable items, this so far sounds like the proper behavior.

**Comment by xen0m0rph2020** [comment]
> What menu are you hoping for it to display? Considering that TV Shows aren't playable items, this so far sounds like the proper behavior.

The standard context menu which says Play, Show Information and More.
This works on all other skins on TV Show Episodes and Movies as its a setting in Kodi under Settings > Media > Videos and default select action. I have Choose selected which means on all other skins I see that menu on selection.
Only on this skin does it not show the menu.

**Comment by xen0m0rph2020** [comment]
it started to happen on Movies now also
:(

**Comment by drinfernoo** [comment]
I do still get the menu on movies, if my default action is set to "Choose". I don't get it on shows, seasons, or episodes, though.

**Comment by xen0m0rph2020** [comment]
> I do still get the menu on movies _and_, if my default action is set to "Choose".
> 
> It does appear that it doesn't want to show up on episode items in the "combined" season/episode view, but by entering the season or using the separated view, I do get the correct menu.

ah can that be fixed?
it also does not always show in latest movies widget. so if you select movie there sometimes is shows menu other times it does not

**Comment by jurialmunkey** [comment]
There is no context menu item available on episodes in the combined season/episode view due to Kodi limitations. If you need to use context menu, then you have to disable that view and use normal season posters. 
`Skin Settings > Library > Integrate season/episode view (uncheck this option)`

All widgets should work normally. 

I don't know what you mean by "Latest Movies" widget. From where? From what add-on? That's not a default widget.

**Comment by drinfernoo** [comment]
@jurialmunkey The issue he's having is that the "default action", as set by Kodi, doesn't seem to be being respected I'm the "combined" view.

**Comment by jurialmunkey** [comment]
@drinfernoo - Yeah because he's using "Choose action" which provides the choice via the context menu.

**Comment by jurialmunkey** [comment]
Show information also won't work in the combined view - but that's because of a different reason.

I could make "Show information" work but it would cause other issues. "Choose", on the other hand, is impossible to make work because the context menu doesn't work for dynamic lists in the library.

**Comment by xen0m0rph2020** [comment]
@jurialmunkey by recent movies I mean the recently added movie widget.
Choose context does not always work there either. So there is a bug please re open

**Comment by jurialmunkey** [comment]
You'll need to give specifics about what doesn't work because it works fine for me.

**Comment by jurialmunkey** [comment]
Also, note that Kodi treats `.strm` files differently to local files. Kodi will only give you the choose action option for local files. It defaults to play for strm.

**Comment by xen0m0rph2020** [comment]
@jurialmunkey So in the home screen the widget I have is Recently Added for Movies section.
When I select a movie in the widget sometimes it shows the menu and other times just plays the movie. All my movies are via NFS and none are .strm.

**Comment by jurialmunkey** [comment]
The most important thing is does it work in Estuary from the recently added widget? There's not really any reason why it would behave differently here.

**Comment by xen0m0rph2020** [comment]
> The most important thing is does it work in Estuary from the recently added widget? There's not really any reason why it would behave differently here.

Yes it works on Estuary. 
On this skin like I said it sometimes works and then does not.
While on Estuary never had problem with menu appearing.

**Comment by jurialmunkey** [comment]
The skin doesn't override onclick actions for widgets, so there's not really any reason why it would behave differently. You need to determine what the pattern of specific steps is to reproduce the issue consistently. It's difficult for me to fix a "bug" if you can't provide exact steps to replicate it.

A proper debug log showing the issue would also be useful.

**Comment by xen0m0rph2020** [comment]
ok
