### ISSUE TITLE
YouTube: accessNotConfigure

### ISSUE THREAD

**Issue by vitadome** [jurialmunkey/skin.arctic.horizon#164]
Each time I search, I'm presented with the you tube error message.  If I choose not to setup my my own api is there a way to disable the message?

**Comment by drinfernoo** [comment]
No, there isn't. Set up an API key, or deal with the messages.

**Comment by jurialmunkey** [comment]
If you don't have YouTube installed, then why don't you remove it from the search options?
`Skin Settings > Miscellaneous > Customise search lists`

I probably should remove YouTube from the default configuration considering it now requires an API key.

**Comment by vitadome** [comment]
Thank you.  I’ll try and remove it from my search Option as you suggest!
