### ISSUE TITLE
[Bug] Subtitles 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#166]
Subtitle icon none responsive
log file:https://paste.kodi.tv/yatubijiho

<a href="https://imgur.com/VEdolk4"><img src="https://i.imgur.com/VEdolk4.png" title="source: imgur.com" /></a>

My Settings
<a href="https://imgur.com/DNdNR1H"><img src="https://i.imgur.com/DNdNR1H.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
That's not the subtitle button. That's the audio channels button.
Subtitle button is the speech bubble with three dots to the right of that one.

**Comment by Blurayx** [comment]
Sorry, I think I was half asleep 😂
