### ISSUE TITLE
[Feature] Next Aired Library Widget opens Library (not TMDbHelper play).

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#167]
I can't access the library from the home screen. This was possible. with Next Aired(6.0.18)
<a href="https://imgur.com/pnsDBHe"><img src="https://i.imgur.com/pnsDBHe.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
I'm just deciding on what the best way to handle this is -- whether it's better to handle from the plugin or the skin.

**Comment by jurialmunkey** [comment]
Okay I think it should work now. You'll need new version of both skin and plugin.

Opted to handle it in the plugin - so there's an option in TMDbHelper Navigation settings to disable and revert back to the old behaviour.

**Comment by Blurayx** [comment]
Working perfectly 😀

Now Next Aired Library behaves exactly like Next Aired(6.0.18) but much better!!! 
TMDbHelper is like a Swiss Army Knife for Kodi. You should give TMDbHelper a bit more exposure to the amazing things it can do. At the moment it's a hidden gem💎 

Thanks
