### ISSUE TITLE
[Feature Request] Submenu

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#168]
Sometimes it's not always convenient to use the keyboard remote. To be honest I mainly use the Nvidia tv remote. would it be possible to add a long-press option to access the submenu instead of pressing  "i" on the remote?

<a href="https://imgur.com/xIGVBZX"><img src="https://i.imgur.com/xIGVBZX.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
Skins cant define context action (which is what long press is bound to).
Only actions that can be defined are onclick oninfo onback.

What I do is set the main menu to open the submenu (Action > Common > Submenu popup). Then I set the first item in the submenu to be what I would normally set as the main menu item -- that way one click opens submenu and second click opens what the main menu would normally open.
