### ISSUE TITLE
[Bug] Extra Fanart Slideshow

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#169]
I'm trying to use the "Vignette" background style, along with items that have extra fanart, to get the "fanart slideshow" background that was possible in AZ2. I've installed Artwork Helper, turned on "Extra Fanart" from the options menu, set a delay (10 seconds), and verified that I am getting multiple fanarts set on the items.

Any idea what I'm missing here?

**Comment by jurialmunkey** [comment]
It's working for me following those steps: Artwork Helper installed, Extra Fanart enabled in Options menu, and Artwork Beef used to add multiple fanarts to video items. It should really work exactly the same as in AZ2 as the code is the same (except I've removed Skin Helper, so only Artwork Helper will work in Arctic Horizon whereas in AZ2 it worked with either installed).

It's possible that Kodi hasn't downloaded and cached the artwork yet -- if the next image can't load in a multiimage control then the last image that was loaded will stay visible until it loads. I think there is a pre-cache option in Artwork Beef to help manage this type of thing.

Selected multiple fanarts for fanart using Artwork Beef:
![Honeyview_screenshot805](https://user-images.githubusercontent.com/4618719/81520446-a537ff80-9387-11ea-8e89-614e5f998649.jpg)

Default fanart:
![Honeyview_screenshot806](https://user-images.githubusercontent.com/4618719/81520449-a701c300-9387-11ea-983e-02e5c9715d67.jpg)

Then after delay changes to a different fanart:
![Honeyview_screenshot807](https://user-images.githubusercontent.com/4618719/81520448-a6692c80-9387-11ea-9068-65695de56347.jpg)
