### ISSUE TITLE
[Bug] Submenu hub icons

### ISSUE THREAD

**Issue by ricksrod** [jurialmunkey/skin.arctic.horizon#17]
When setting custom icons for sub menu items, they are not shown in the submenu hub. It shows the default icon for the menu item instead.

**Comment by jurialmunkey** [comment]
I originally thought you meant the submenu widget and I couldn't replicate. Now I see that you said hub and yeah I can replicate and confirm the bug. I'll look into it.

**Comment by jurialmunkey** [comment]
Okay I think I've fixed it (way easier than I thought it was going to be). Please test v0.1.12
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.12

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/818eea5697309c0985af7edca62171802fac5da0

**Comment by ricksrod** [comment]
Confirmed working, thanks!
