### ISSUE TITLE
[Feature Request ] more Icons

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#171]
Can you please add gym and documentary icons to the list
These are only examples
<a href="https://imgur.com/SuXTmj2"><img src="https://i.imgur.com/SuXTmj2.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/jAbHhBC"><img src="https://i.imgur.com/jAbHhBC.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/rqruq9u"><img src="https://i.imgur.com/rqruq9u.png" title="source: imgur.com" /></a>

Thanks for the advice regarding the submenus, it works great. 

<a href="https://imgur.com/W2ksnNM"><img src="https://i.imgur.com/W2ksnNM.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
They have to be from a source with a license that is free to distribute and modify without attribution. I usually use icons from iconmonstr.com since it has no licensing restrictions. If there's a suitable icon on iconmonstr then I can include it.

**Comment by Blurayx** [comment]
Here is one I found not ideal but a compromise. iconmonstr is very limited.
https://iconmonstr.com/video-camera-7-svg/

Thanks
