### ISSUE TITLE
[Request] Mouse support

### ISSUE THREAD

**Issue by zeeyaullah** [jurialmunkey/skin.arctic.horizon#172]
Just asking... Don't feel bad 😊
Is there any harm/limitations/hindrance to add mouse support to these beautiful skins including Arctic Zephyr 2?

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/skin.arctic.horizon/issues/32

**Comment by jurialmunkey** [comment]
Mouse for the most part works in this skin. What doesn't work? Be specific.
