### ISSUE TITLE
Vignette / Overlay background 

### ISSUE THREAD

**Issue by hacky4real** [jurialmunkey/skin.arctic.horizon#173]
If Vignette or Overlay background style is active; a black background replaces the fallback image when a file or trailer starts to play. This isn’t the case with Blur background style (it retains the fallback image).

**Comment by jurialmunkey** [comment]
I can't replicate this issue.

If show video in background is on I get the video:
![Honeyview_screenshot808](https://user-images.githubusercontent.com/4618719/81760937-efe28480-950b-11ea-9e52-c7aa51b5fec8.jpg)

And if show video is turned off I get the fanart
![Honeyview_screenshot809](https://user-images.githubusercontent.com/4618719/81760955-fbce4680-950b-11ea-8033-35f419b881b0.jpg)

**Comment by jurialmunkey** [comment]
Ah, I think you must be talking about the fade out when the busy loader is visible -- I'm guessing you have the waves animation disabled. 

Latest changes will fix this as much as is possible. Fanart might still dissappear for a moment, not much I can do about that -- happens in Estuary too.. but this fix will improve it somewhat.

**Comment by drinfernoo** [comment]
While we're here, I think the waves animation still shows in "File Manager", even when disabled.

**Comment by jurialmunkey** [comment]
@drinfernoo - Are you sure? It shouldn't do since it uses the same include as the other windows. I can't make it appear in the File Manager if disabled.

**Comment by drinfernoo** [comment]
I'll have to double check.
