### ISSUE TITLE
Season List Menu

### ISSUE THREAD

**Issue by Ireneta84** [jurialmunkey/skin.arctic.horizon#175]
Hello,

I am having trouble getting my meny fo any tv show to show the season list. I shows all of the episodes in landscape mode. 
I tried checking the flatten seasons option on all the apps and the skin settings but nothing changes.

Any help?

Thank you!!

**Comment by drinfernoo** [comment]
https://imgur.com/UZbMTGO

**Comment by Ireneta84** [comment]
It doesn't work either.

**Comment by drinfernoo** [comment]
Make sure that when that setting is on, that you're *not* using the relevant "flatten seasons" settings.
