### ISSUE TITLE
Add script.toolbox as a dependency

### ISSUE THREAD

**Issue by piejanssens** [jurialmunkey/skin.arctic.horizon#181]
I was wondering how I would achieve seeing all the different ratings as can be seen in the beautiful skin sample screenshots. I found out by accident that it was script.toolbox that makes this possible. IMO it seems to be a key element of this skin and maybe worth considering adding it as a mandatory dependency so that beginner/new users can fully benefit.

**Comment by jurialmunkey** [comment]
No it's not. Toolbox has nothing to do with that.

TheMovieDb Helper is what provides the ratings. It already is a dependency. You need to add an OMDb API key to its settings to have the ratings work.
