### ISSUE TITLE
[Request] Search option button - Info Dialogue

### ISSUE THREAD

**Issue by starmanrf** [jurialmunkey/skin.arctic.horizon#184]
Hey JM,

Stellar work on the Horizon skin so far. Could I request that a search button be added to the TMDB Helper  menu within the info dialog for video content within video add-ons. 

I'm a user of Plex Kodi connect(PKC) and only sync movies to my library database (syncing a large amount of TV shows lags the file system, so I tend to just use the integrated PKC add-on browser for TV content). 

Perhaps a stand-alone button wouldn't be required as It would be a nifty little feature if the skin could automatically  identify non-library / video addon content and substitute the browse button for a Search button, when clicked would trigger skin.setstring(Title search term).

PKC aside, I hope it would be a powerful function for most video add-ons, especially when combined with the ability to trigger the auto search term in the skins's in-built customised search lists (which is an awesome feature btw !!).

Thanks for reading and any consideration you give to the idea.
Keep up the great work!

Ryan

**Comment by jurialmunkey** [comment]
I think I already had this feature previously. I'm not quite sure why I removed it -- might've been for space reasons.

**Comment by starmanrf** [comment]
I can see how real estate could be a problem in the info dialogue, maybe an icon with no text?  Or the current browse button in to a submenu pop-up with browse TMDB and a search option perhaps?
