### ISSUE TITLE
[Bug?] Music/Watched

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#19]
When music has finished playing watched is highlighted  

<a href="https://imgur.com/rsnoWWk"><img src="https://i.imgur.com/rsnoWWk.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Ah I think it is because playcount is more than zero. Can you test v0.1.14? I think it should be fixed now: https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.14

**Comment by Blurayx** [comment]
working!!

Thanks
