### ISSUE TITLE
Allow 'Poster' view in 'genres' instead of just 'seasons' or 'tags' view

### ISSUE THREAD

**Issue by GOvEy1nw** [jurialmunkey/skin.arctic.horizon#193]
Currently you can only have 'Seasons' or 'Tags' View in the 'genres' section. But it would be great if we could have the 'Posters' view too. You can get to the posters view of a genre by using the 'Tags' view and then clicking on the genre you want, but it just feels like more clicks than necessary to then go between genres quickly.

If we could have the 'Posters' view while also being able to have the buttons in the 'Seasons' view that would be great.

Seasons view in Genres
![image](https://user-images.githubusercontent.com/45126527/84020504-d43b9400-a97a-11ea-8b11-340d2ee12a33.png)

Posters view within a Genre
![image](https://user-images.githubusercontent.com/45126527/84020809-57f58080-a97b-11ea-8331-b93941c42fe9.png)

**Comment by jurialmunkey** [comment]
This was fixed a while ago.
