### ISSUE TITLE
Show digits pressed on Live TV/Guide windows

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#196]
Currently, when on the Live TV/Guide windows, digits can be pressed and they move the cursor to the selected number but the keys are not shown. This behaviour differs from the channels window were the numbers pressed are shown on the up right corner. Could the same behaviour be added to all PVR windows?
Thanks.

**Comment by jurialmunkey** [comment]
Do you know of any skins that do this? I think it might be a fullscreen video window only thing.

**Comment by juanma-cvega** [comment]
I just tried on Estuary and it works there. You see the digits pressed in the middle of the screen.
