### ISSUE TITLE
Add Genre to information about movie/series

### ISSUE THREAD

**Issue by brtani** [jurialmunkey/skin.arctic.horizon#197]
It would be great to have option to show Genres info in the section movie/series as you can see it in the picture. Thanks.

![Lhk5Xqj~2](https://user-images.githubusercontent.com/37026549/84587478-e9536f80-ae1f-11ea-9587-2b47db4e1e4c.jpg)

**Comment by drinfernoo** [comment]
You need to have content which has ratings attached in order for it show.

**Comment by brtani** [comment]
What do you mean? I do not understand, what I have to do. Can you explain it to me?

**Comment by jurialmunkey** [comment]
I think drinfernoo misunderstood and thought you were asking how to turn the ratings on.

Unfortunately, genre is too long to show in the info line. Many movies have multiple genres - e.g. "Action / Adventure / Comedy / Family" which will push the info too far to the right.
