### ISSUE TITLE
[Feature] Library Calendar 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#20]
Would it be possible to have an option to have Library Calendar on the home screen?
The reason for this request is because Next Aired 6.0.17 (now maintained by Hitcher
https://github.com/XBMC-Addons/script.tv.show.next.aired) displays the correct air dates according to the region where you live[UK]. A few years ago the skin helper widget was updated and the time zone stopped working. 
I requested the time zone issue numerous times but was never fixed. I think skin helper is no longer being maintained. For me, this would be a great alternative.

Thanks

**Comment by jurialmunkey** [comment]
Yeah you can add it as a widget through TMDBHelper
`Add-on > Video Add-on > TheMovieDb Helper > TV Shows > Next Aired Library > This Week > Use as Widget`

There are options for Last Fortnight, Last Week, This Week, This Fortnight, All Items, or Any Specific Day.

**Comment by Blurayx** [comment]
Hi jurialmunkey
Can't see the Use as Widget
 <a href="https://imgur.com/JyKm9N4"><img src="https://i.imgur.com/JyKm9N4.png" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
Not working on Arctic Horizon but works on AZ2

Arctic Horizon
<a href="https://imgur.com/vE5dPWK"><img src="https://i.imgur.com/vE5dPWK.png" title="source: imgur.com" /></a>
AZ2
<a href="https://imgur.com/Aw4AR7z"><img src="https://i.imgur.com/Aw4AR7z.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
There shouldn't be any reason why it works in one skin and not the other.

**Comment by jurialmunkey** [comment]
Should be fixed in v0.1.16
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.16

Previously widgets with 1 item were getting hidden.

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/5a9441e744d4357e158ddb4e8ed1597f94b809bf

**Comment by Blurayx** [comment]
Working!!  \0/
<a href="https://imgur.com/1iO6PUb"><img src="https://i.imgur.com/1iO6PUb.png" title="source: imgur.com" /></a>
Thank You

**Comment by Blurayx** [comment]
I'm really putting your new skin to the test lol

**Comment by Blurayx** [comment]
There's one TV Show missing from the home screen widget
<a href="https://imgur.com/SIvGw0m"><img src="https://i.imgur.com/SIvGw0m.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Hmm. It's showing for me:

![Honeyview_screenshot635](https://user-images.githubusercontent.com/4618719/76954076-df76b900-6963-11ea-85aa-c445638b0371.jpg)

That would mean that either there is a mismatch between the title in your library and the title on trakt/tmdb, or it has been bumped into a different day - but I doubt it is bumped to a different day as it looks like the time/date shift is working correctly for you. Project Blue Book is showing the same time in both TMDBHelper and Next Aired so I would expect the other shows are being shifted correctly too -- unless there's a difference in the data Trakt has (where I get my next aired data from) over TVDb (where next aired gets its data from).

**Comment by Blurayx** [comment]
OK, Thanks

**Comment by Blurayx** [comment]
Update: Fixed 
My folder Is correctly named but for some reason it's been renamed Empire (2015) <a href="https://imgur.com/AqprA1m"><img src="https://i.imgur.com/AqprA1m.png" title="source: imgur.com" /></a>
context menu->edit title, to removed (2015)
<a href="https://imgur.com/dxMjP84"><img src="https://i.imgur.com/dxMjP84.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/8qHSCpT"><img src="https://i.imgur.com/8qHSCpT.png" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
Hi, jurialmunkey
 I don't want to reopen this feature request but I have a question.
 I have noticed all my tv shows with brackets eg(2015), Don't show on my TV Shows Airing Today(TMDBHelper) home screen. Is there a setting in Kodi to ignore brackets? 
Alternately if possible, add an option setting in TMDBHelper to ignore brackets.
If I use the Skinhelper option my TV shows with brackets display the widgets.

Thanks
