### ISSUE TITLE
[Feature Request]'Similar Movies' button

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#202]
Can we have a 'Similar Movies' button in the same panel where we have Play, Trailer etc.? I have highlighted in the image.
Conscious that there is a "similar" list down below on that screen but need to scroll a bit to reach there...so was thinking having that button will be easier 🙂

![image](https://user-images.githubusercontent.com/48493659/85778527-8ebcec00-b71a-11ea-9d50-da8eaaf484f4.png)

**Comment by jurialmunkey** [comment]
It won't fit if there's also a Manage button or if a language with longer labels is used.
