### ISSUE TITLE
[Request] Play Using in Info Dialog

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#205]
Would it be possible to have a setting for the "Play" button in the info dialog for TMDbHelper items to force player selection?

The situation I run into is in spots like the showcase hub or screensaver, where you can't open the context menu, and only have the option of going into the info dialog. In that instance I can't do Trakt operations (kind of a bummer, I keep seeing movies on the screensaver I wanna watch 😅), choose a player, etc...

My default player will simply play the file, but if I could use a "search" player here, then I would end up in a media window and able to interact with the item.

**Comment by jurialmunkey** [comment]
Do you think this search option https://github.com/jurialmunkey/skin.arctic.horizon/issues/184 would solve this issue?

I'm a bit wary of adding too many buttons as the real estate is fairly limited. The other thing might be a generic "Actions" button that would pop-up a menu of options (similar to "Manage" button).

**Comment by drinfernoo** [comment]
Yeah, a "Search" or "Actions" (maybe better) button would be workable, I think. Would it be feasible for an "Actions" menu to mimic the standard context menu for the item?

**Comment by jurialmunkey** [comment]
Nope, no way to get the context menu items from the skin. All the "Actions" would need to be hard coded into the skin using builtin commands.

**Comment by drinfernoo** [comment]
The new "Search" option is perfect for this 👍

**Comment by drinfernoo** [comment]
@jurialmunkey, would this knowledge of how they work internally help in any way? https://github.com/xbmc/xbmc/pull/18106#issuecomment-651660727

**Comment by jurialmunkey** [comment]
That's only for attaching a specific context menu item to a specific list item in a plugin directory via python - most context menu items don't use this method and instead come from built-ins or context menu addons.

Those properties will only be there for context items specifically added by the python method - the others won't display as those properties. And still, even then I would need a script to retrieve the items - there's nothing in the skinning engine which will expose them.

**Comment by drinfernoo** [comment]
@jurialmunkey For what it's worth (and taking into account those only exist for items added via `xbmcgui.ListItem.addContextMenuItems(...)`), you *can* retrieve those actions and labels via `ListItem.Property(ContextMenuAction(...))` and `ListItem.Property(ContextMenuLabel(...))`, respectively, and using the index as a parameter.

I'm not sure how well you can handle an indeterminate number of items on the skin side, but these properties *should* be accessible to you there as well. I can read them via DevHelper Web, just by focusing an item.

**Comment by jurialmunkey** [comment]
Ah of course! I completely didn't even think about actually just using $INFO[ListItem.Property(Context...)] - I wonder if it would actually execute the command if it was put in an `<onclick>` though...

> I'm not sure how well you can handle an indeterminate number of items on the skin side

Not easily... It's basically a case hard-coding X number of entries and having `!String.IsEmpty(foo)` visibility conditions to check if there's a value.

**Comment by drinfernoo** [comment]
@jurialmunkey Well, just thought I'd show you my findings 😁
