### ISSUE TITLE
[Bug] Hang on Install

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#208]
Anytime the skin is installed (either fresh or on an update), there is a long hang with a black screen. Sometimes a "back" action will get out of it, sometimes not, but afterwards, everything in the skin is a bit wonky as well, until it reloads.

**Comment by jurialmunkey** [comment]
^^ Pretty sure that will fix the crash issue. Nothing can be done about the black screen - it's just because Kodi is reloading the skin files so nothing for GUI to display until they load.
