### ISSUE TITLE
[Feature Request]Subs button to display subtitle language

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#211]
Please see this video
https://imgur.com/a/WWOcWVt

I used a4ksub to download an external English subtitle as the video did not come with an embedded one.

The speaker icon displayed ENG on top of it implying language of the movie which is great.
The subtitle icon should do similar as in display ENG or whatever language subtitle I am using.

This is available in AZ2 skin, please enable it for AH skin too.

**Comment by drinfernoo** [comment]
The relevant PR that added this feature to AZ2: https://github.com/jurialmunkey/skin.arctic.zephyr.2/pull/156

**Comment by jurialmunkey** [comment]
Not sure why I didn't add this alongside the audio language... Fixed.

**Comment by onlytanmoy** [comment]
> Not sure why I didn't add this alongside the audio language... Fixed.

Thanks mate.
