### ISSUE TITLE
[Feature Request]Ends at time...to display when pulling up player OSD

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#212]
When the player OSD shows up, it will be nice to see...Current time and Ends at time on top right just like AZ2 displays.. screenshot below
https://imgur.com/a/GJYkIts
Currently that shows as Finishes at...only when you pause the video.

**Comment by jurialmunkey** [comment]
I don't like moving the position of things. Clock should always be in the same location - adding the end time shifts the clock position and necessitates the addition of a "Time" label. There is a clear delineation between information at the bottom of the screen (displays information about what's on screen) and the system notification area in the top right of screen - putting finish time in the top right breaks that delineation.

This was one of the compromises I made in AZ2 which I really really dislike, so unfortunately it's a No for this one. You can press "info" on remote or "i" on keyboard to see finish time without needing to pause.

**Comment by onlytanmoy** [comment]
@jurialmunkey correct me if wrong but there is no info button on the shield remote, right?
