### ISSUE TITLE
[Bug] Plotbox Text Cut Off In a Couple Instances When Ratings Are Disabled

### ISSUE THREAD

**Issue by pkscout** [jurialmunkey/skin.arctic.horizon#213]
I stumbled on a couple places (I think they're actually the same code) where the plotbox text is cutoff when the ratings are disabled.  If the text goes to a third line, the third line is partially cut off.  I have been playing with font sizes, so I confirmed this with a clean install of the skin.  It shows up in the dialog info box for TV shows (I didn't check movies) and if you are using landscape mode for a video addon (like Disney+).  Here's a couple screen shots.
<img width="1390" alt="addonlandscape" src="https://user-images.githubusercontent.com/1402018/86883939-88216380-c08e-11ea-8e66-67271c6f59a2.png">
<img width="1390" alt="tvshowinfodialog" src="https://user-images.githubusercontent.com/1402018/86883947-8a83bd80-c08e-11ea-844f-60f907e09dd7.png">

**Comment by jurialmunkey** [comment]
Can confirm. Should be fixed now.
