### ISSUE TITLE
Widgets refreshing every 2 second on 0.2.96, fine on 0.2.91

### ISSUE THREAD

**Issue by GOvEy1nw** [jurialmunkey/skin.arctic.horizon#216]
Hey, apologies, I didn't export a log as it was late at night and just wanted to sorted. But basically, as soon as I upgraded to the new 0.2.96 update all my widgets started refreshing every 2 seconds.

I tried rebooting, re-installing the same update etc but nothing worked, once I downloaded the older 0.2.91 version from here and installed it, it was all fine again, no more constant refreshes.

I'm on Kodi Leia 18.7.2 on an Nvidia Shield.

Also, just as a side note, could you include one or two versions back in your repository for this skin? That way if there are issues it's easier for users to revert back.

Cheers!

**Comment by jurialmunkey** [comment]
Skins don't control when widgets refresh. 

Sounds like you have something bugged with either skinshortcuts or skinvariables setup. Both those scripts reload the skin, so if there is some issue you can get stuck in a reload loop. Need a debug log to know what is happening as I can't recreate this issue myself.
