### ISSUE TITLE
Can't mark single episodes as watched. 

### ISSUE THREAD

**Issue by NeverExists07** [jurialmunkey/skin.arctic.horizon#219]
I got one to display the menu to mark it has watched only once, but haven't been able to get the menu pop up on episodes. I am on Nvidia Shield, and the am pressing and holding the button to bring up the menu to mark as watched but nothing happens. It worked fine a few months ago.

**Comment by drinfernoo** [comment]
If you're talking about the integrated season/episode view, and that you can't open the context menu on episode items, that is because of a limitation in Kodi's skinning engine. You'll have to open the season first.

**Comment by jurialmunkey** [comment]
As stated by drinfernoo, context menu doesn't work in the view combining seasons and episodes due to a limitation in the kodi skinning engine. There's nothing I can do about it.
