### ISSUE TITLE
[Bug] Force "search for addon updates" 

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#22]
In the addons-submenu "available updates" the overview and option button isn't working, so you can't search for addon updates (I expect it's in option view)

**Comment by jurialmunkey** [comment]
I already fixed this bug in v0.1.13
Most recent version is v0.1.16
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.16
