### ISSUE TITLE
Submenu Hub-On Remote Down key press

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#223]
Using latest Arctic Horizon skin and got Submenu Hub.
Please notice 15 secs in the video when I press the down key of the shield remote.
https://imgur.com/a/Vzujnr4
Is it supposed to display like that?

**Comment by drinfernoo** [comment]
That's the "wall view", and you can actually disable it in the views of your choice in Skin Settings.

**Comment by jurialmunkey** [comment]
Yes, it is meant to display that way. As drinfernoo mentions, there's an option in skin settings to disable the wall view.

**Comment by onlytanmoy** [comment]
> Yes, it is meant to display that way. As drinfernoo mentions, there's an option in skin settings to disable the wall view.
Discussed with doc yday on this, no such option exists!

**Comment by drinfernoo** [comment]
@jurialmunkey, I did say that, but neither of us were actually able to find it anymore?

**Comment by jurialmunkey** [comment]
@onlytanmoy @drinfernoo 

![Honeyview_screenshot076](https://user-images.githubusercontent.com/4618719/88895829-574add80-d28c-11ea-930e-816c1fff3ac5.jpg)

I've really got to re-organise the skin settings - it's getting difficult to find some things and I've also found certain options where I'd expect them to be grouped together but they're not (e.g. divider line and clearart options are in different sections).

**Comment by onlytanmoy** [comment]
@jurialmunkey Thanks mate, un-checking that option did the job 💯
