### ISSUE TITLE
Request: Modification or addition to Music views

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon#227]
Is it possible that there could be a bit of improvement to the music library view, specifically the years view

My library has music for pretty much every year from 1960 to 2020 and I use it a lot as a quick way to find things. At the moment however the two views for music>years are not ideal.

View one - "season" view

![080320012841](https://user-images.githubusercontent.com/25871666/89201889-10b9f380-d5aa-11ea-8a10-e09326876635.png)

This view is quite nice, its easy to zap the slider across to the year and then auto populate with the albums but it has one major problem. Albums are replaced by landscape images which is a nightmare. Certainly when you are used to the album covers

View two - 

![080320012911](https://user-images.githubusercontent.com/25871666/89201979-33e4a300-d5aa-11ea-996e-a09ffc16804e.png)

This is ok, but is quite hard to see the years as the icon is the predominant thing which is obviously not particular relevant.

Is it possible to:

+ Add list view to years so that years can just be a simple scrollable list

and/or

+ change the image view in "season" for music libraries to be the album art. 

cheers

(i use kodi as my main music player in the house and with 2.5k albums years is a common route i take to play stuff)

**Comment by jurialmunkey** [comment]
I've been meaning to get to this for a while now - this was a good prod to get it done.

See latest git version. Should now be able to select an "Artists" and a "Collections" viewtype. These viewtypes are the same as Seasons but will use Square and Poster aspects for the items. "Artists" is available for Artists/MusicYears/MusicGenres and Collections is available for Sets/TVShows/VideoGenres/VideoYears/Tags/Studios/Actors/Directors/Countries.

Also, MusicYears and MusicGenres are now considered separate from VideoGenres and VideoYears. Before you could only set one viewtype of all Genres/Years views, but now you can choose separate ones for Videos and Music sections.

Let me know how it goes. Everything looks to be working to me but it's possible I've missed something.

**Comment by dm2912** [comment]
Many thanks.. looks perfect here in both years view and artist view

![080720154735](https://user-images.githubusercontent.com/25871666/89657975-dc09ad00-d8c5-11ea-8fc2-bd226133d7cb.png)
![080720154916](https://user-images.githubusercontent.com/25871666/89657982-dd3ada00-d8c5-11ea-8b8e-74a78b14020c.png)

easier for genres to have list as well. many thanks
