### ISSUE TITLE
Context Menu Doesn't Work on Episode in Season View

### ISSUE THREAD

**Issue by pkscout** [jurialmunkey/skin.arctic.horizon#228]
I'm not sure if this is a bug, feature, or just something incomplete, but if you are season view mode and arrow down to the shows for the highlighted season, trying to bring up the context menu on a particular episode does nothing.  If you select the season (which bumps you to episode view), then the context menu works fine.

Here's the screen where the context menu **doesn't** work.

<img width="1390" alt="Screen Shot 2020-08-06 at 7 12 50 AM" src="https://user-images.githubusercontent.com/1402018/89561676-8db8b900-d7b4-11ea-9c65-d3587c583bbd.png">

And one where the context menu **does** work.

<img width="1390" alt="Screen Shot 2020-08-06 at 7 13 13 AM" src="https://user-images.githubusercontent.com/1402018/89561737-a75a0080-d7b4-11ea-9dc3-9c44a1a76e96.png">

**Comment by drinfernoo** [comment]
It's a limitation of the Kodi skinning engine, and has been covered a handful of times.

**Comment by pkscout** [comment]
Thanks for the info, and apologies for not doing a better job searching the issues and forum thread. I'll close this.
