### ISSUE TITLE
[Bug] "Panels behind text" not Respected in Wall View

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#229]
Just as the title. This occurs with both "Square" and "Landscape" views.

**Comment by jurialmunkey** [comment]
I've got a fix for this in the works - it is just tied up with the new indicator code so I can't merge it until that's ready.

**Comment by drinfernoo** [comment]
I only noticed today because I was exploring the new settings flow and testing out settings I don't use often 😅

**Comment by jurialmunkey** [comment]
> I only noticed today because I was exploring the new settings flow and testing out settings I don't use often.

Well that's pretty much how the fix ended up getting mixed in to the wrong branch -- noticed it while working on the new indicator style for no panels and forgot to switch branches before fixing it!

![Honeyview_screenshot084](https://user-images.githubusercontent.com/4618719/89724758-a5a96a80-da4a-11ea-9318-7e1e61ce74c9.jpg)

**Comment by drinfernoo** [comment]
Oh, those are sick! I can't wait!

**Comment by jurialmunkey** [comment]
You can test it out using the "indicator-testing" branch.
https://github.com/jurialmunkey/skin.arctic.horizon/tree/indicator-testing

Currently only works with text panels disabled (i.e. text panels on uses corners, text panels off uses circles). Trying to figure out a way to make it look nice with panels turned on - that's the main roadblock stopping me from merging at the moment.
