### ISSUE TITLE
[Feature] Widgets

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#23]
I've been trying to work this out but I don't think it's possible.
I have created the move DB widget, I would now like to set it up when I click on the Icon, Next Aired would appear

Example

<a href="https://imgur.com/RtQ9Dxg"><img src="https://i.imgur.com/RtQ9Dxg.png" title="source: imgur.com" /></a>

Click on move DB icon
<a href="https://imgur.com/Vs92LlI"><img src="https://i.imgur.com/Vs92LlI.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Why can't you just add the shortcut to the main menu item? It's usually under Addons > Programs

**Comment by Blurayx** [comment]
Ah, Thank you!!!
I'm learning a lot from you today.
