### ISSUE TITLE
[Feature Request] Ability to customize infobar

### ISSUE THREAD

**Issue by terpsarlington** [jurialmunkey/skin.arctic.horizon#232]
Can you please make it so the user has the ability to customize the infobar.

Below are some options.

Movie: Quality, Studio, release date, release year, length, end time, Audio, Country, etc...

**Comment by jurialmunkey** [comment]
Sorry this is just not something that is feasible in the skinning engine. It would need a system of incredibly complex skin variables and settings to achieve in the skin (or it would require writing an addon script). Basically way too much work for very limited benefit - much simpler for users just to edit the InfoLine variables in the Includes_Labels.xml to achieve whatever they want.
