### ISSUE TITLE
Multi Widget View

### ISSUE THREAD

**Issue by rijsab** [jurialmunkey/skin.arctic.horizon#233]
hi JM,

I really like the look in home page if there is only one widget available for a menu.

Is it possible to have this for multi widget also, so the top movie/TV show information stays but able to scroll down to other widgets or have this as an option in settings?

Cheers for the great work!

**Comment by jurialmunkey** [comment]
Unfortunately not possible with the way the widgets work currently - it would require quite a big rewrite of the widget system to achieve.
