### ISSUE TITLE
[bug] Selecting a collection from wallview shows a simple view first time only.

### ISSUE THREAD

**Issue by ricksrod** [jurialmunkey/skin.arctic.horizon#235]
Steps to recreate:

1. Enable wallview for movies.
2. Enable the 'show movie sets' (settings > media > video)
3. Browse movies in wallview and select a collection.

The collection opens with only the movie posters and no movie information. Pressing 'back' once will bring up the correct menu view with all of the movie information etc. 

After doing the above, if you reselect the collection from wallview again it opens correctly.

**Comment by jurialmunkey** [comment]
Can you test latest git master?

I'm fairly certain it should be fixed now. However, I was only able to recreate the issue about half the time, so it would be good to have some confirmation.

**Comment by ricksrod** [comment]
Yep, works perfectly now. Thank you!
