### ISSUE TITLE
[Bug] List view not applied in some addons (FoxyStreams)

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#24]
Maybe devs needs to change their code to supply more tags, but when you open certain addons the viewtype defaults to Icon.

Title below the Icon gets displayed okay in FoxyStreams, but not in all addons.  Then you need to click Overview to see the name of the Icon

![screenshot001](https://user-images.githubusercontent.com/10348988/76959208-74a09000-6919-11ea-9ffc-6e957581e2c2.png)

![screenshot002](https://user-images.githubusercontent.com/10348988/76959235-808c5200-6919-11ea-9e64-3a806f8a6779.png)

**Comment by jurialmunkey** [comment]
Content type in those screenshots is "Videos". Looks like that is the wrong content type for what is being displayed (at least in the first screen). Addons need to set the correct content type.

In the first screenshot, a content type of "Addons" "Files" or nothing would all be more suitable. The addon is saying that's a container of videos but it clearly isn't. 

The second screenshot looks like it is videos but just lacks any metadata. If there's no metadata, the more appropriate content type is "Files". 

Addon author will need to fix their addon to use the correct content type.
