### ISSUE TITLE
Horizontal centred menu, not quite centred

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon#240]
Using the latest git version i noticed you did a commit to center the menu when less than 9 items

im sure you are already on it, but its not quite centred (its about 2" off centre on my tv)

![082020014501](https://user-images.githubusercontent.com/25871666/90703950-0d4f8900-e287-11ea-9c9b-652f0f267ae6.png)

thats triggering the hell out of my ocd :') :')

**Comment by jurialmunkey** [comment]
It's centered according to the middle of the list (see movies icon in your screenshot) not the middle of the bar. I guess it would make sense to center the bar instead though.
