### ISSUE TITLE
[Bug] Seekbar remains active when leaving Information screen.

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#25]
When playing a movie, press the Information-icon, Info screen opens.
Leave Info screen with back, Movie reappears fullscreen.

You can't close the seekbar by waiting, arrow down...

When pressing back, and then tab, the seek bar is normal again.

![screenshot004](https://user-images.githubusercontent.com/10348988/76961476-b3384980-691d-11ea-9baa-f301989ba743.png)

**Comment by DaisyF8** [comment]
This bug still remains for me on 0.1.17

**Comment by jurialmunkey** [comment]
Ah yep can replicate. Looks like a bug in TMDbHelper.
Should now be fixed. You'll need to update both the skin and TMDbHelper to the latest versions.

**Comment by DaisyF8** [comment]
Solved
Thx
