### ISSUE TITLE
Fullscreen widget 

### ISSUE THREAD

**Issue by rijsab** [jurialmunkey/skin.arctic.horizon#251]
Have an option to have different fullscreen widget content for home menus. So I am trying to have trending TV shows for my menu TV Shows and have Trending Movies for Movies menu. Now both are showing same content because I can set only 1 Fullscreen widget path.

**Comment by drinfernoo** [comment]
The 0.5.0 update actually does this, I'm working in pushing it to the repo now.

**Comment by jurialmunkey** [comment]
Jut to clarify, the fullscreen widget uses the paths set in the main menu item's hub widget section

The order it draws from is:
1. Background widget
2. Hub widget
3. Fullscreen widget

e.g. In the below screenshot, my fullscreen widget for Movies will use "Random Movies" not "Movie Sets".

![Honeyview_screenshot172](https://user-images.githubusercontent.com/4618719/90994116-ff896300-e5fa-11ea-9dc1-af96706d88ff.jpg)

**Comment by rijsab** [comment]
Makes more sense now! Cheers mate!
