### ISSUE TITLE
[Question] Home Screen 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#252]
I want to keep the random movie home screen but how do I stop AH from changing everytime I scroll to the next icon.
Basically I want it to continue from the previous fanart. 

![1](https://user-images.githubusercontent.com/2873112/91023462-79671f80-e5ee-11ea-815b-6e80b4a4b6f2.jpg)

![2](https://user-images.githubusercontent.com/2873112/91023477-7d933d00-e5ee-11ea-89d9-56763fc0f03d.jpg)

Thanks

**Comment by drinfernoo** [comment]
You basically want a single showcase across **all** home sections?

**Comment by jurialmunkey** [comment]
> 
> 
> You basically want a single showcase across **all** home sections?

That's how the fullscreen widget used to work pre-0.5.0 if you didn't set a hub widget. It basically acted as a "global" widget that sat behind all the other widgets and was visible if there were no widgets for a particular page. The recent changes got rid of this global widget and instead generate a separate fullscreen widget for every page.

I'd like to bring that functionality back, just a matter of figuring out the best way to accommodate it in the recent changes.

**Comment by Blurayx** [comment]
> You basically want a single showcase across **all** home sections?

Yes😃

**Comment by jurialmunkey** [comment]
Oops, had to revert that, caused another issue.

**Comment by jurialmunkey** [comment]
Okay fixed now.
