### ISSUE TITLE
[Request] Indicator for "Orphaned" Dependencies

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#253]
It is currently displayed in the infoline, but a small indicator would be much appreciated ;)

**Comment by jurialmunkey** [comment]
Do you know what ListItem label shows this information? Is it `ListItem.Label2` or `ListItem.AddonDisclaimer` or `ListItem.AddonBroken` or `ListItem.Property(Addon.Status)` ?
Also what is the exact text when orphaned?

I don't think I've got any orphaned addons currently (or at least not that I'm aware of), so I'm not sure what the info label is to check against or what the value is to check. Happy to add an indicator, just not quite sure what to base it off.

Also do you have any suggestions for what type of icon it should be?
I was thinking either of these:
https://iconmonstr.com/warning-7-svg/
https://iconmonstr.com/link-11-svg/
