### ISSUE TITLE
[Bug]  Disabled widgets are selectable in main menu

### ISSUE THREAD

**Issue by scapix** [jurialmunkey/skin.arctic.horizon#256]
Version 0.5.1
Reproduction steps:
- Setup at least 3 widgets for some menu item.
- Disable middle one
- Goto main menu and select first row widget
- press down to select second visible row
- invisible control (disabled widget - 2nd one in main menu customizer) is selected instead

User must press down one more to select second row widget.

**Comment by jurialmunkey** [comment]
How are you disabling the widget? You shouldn't be able to disable widgets.

**Comment by scapix** [comment]
Yea, you are right. My bad,
I didn't wrote those repro steps correctly - got them disabled in Arctic Zephyr 2. And as Horizon is sharing setup from Zephyr they were disabled in Horizon too

**Comment by jurialmunkey** [comment]
Yeah, you can't disable any widgets in the setup as it will break things. Just delete the widget if you don't want to use it.

**Comment by scapix** [comment]
Ok. I keep them for future use/reference, moved them to the bottom of liist
