### ISSUE TITLE
[Bug] TV Shows Airing Today(TMDBHelper)

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#26]
No response.
If I click on the poster icon should it open the Project Blue Book folder?
or is it a limitation of Kodi. The same issue with AZ2 
<a href="https://imgur.com/vJeD6DB"><img src="https://i.imgur.com/vJeD6DB.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
No. Clicking an item from TMDbHelper will run it's player action  - if you're getting no action then maybe you didn't set the content type of the widget to videos.

You can browse seasons for a show from the context menu.

**Comment by Blurayx** [comment]
it's set to video
<a href="https://imgur.com/Qvp3yCt"><img src="https://i.imgur.com/Qvp3yCt.png" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
Update:
This is so wired, only project blue Book works
<a href="https://imgur.com/8qHSCpT"><img src="https://i.imgur.com/8qHSCpT.png" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
working now
