### ISSUE TITLE
[Bug] TV & Movie actor info

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#264]
When I click on actor info It returns back to the movie info

![1](https://user-images.githubusercontent.com/2873112/91634362-c03a8800-e9e7-11ea-9aab-c095214389ce.jpg)

After clicking actor info, returns back to the movie info 
![2](https://user-images.githubusercontent.com/2873112/91634396-ff68d900-e9e7-11ea-895d-26c9bd7e7b37.jpg)

**Comment by jurialmunkey** [comment]
What version are you using? I think I may have already fixed this issue.

**Comment by Blurayx** [comment]
v0.5.21

**Comment by Blurayx** [comment]
Update:
v0.5.22 same issue

**Comment by jurialmunkey** [comment]
Hmmm. I can't replicate the issue - I even tried with the exact same movie and it works fine for me.

**Comment by Blurayx** [comment]
This is the only way I can access actor info
![Screenshot 2020-08-29 at 14 59 37](https://user-images.githubusercontent.com/2873112/91638609-99d91480-ea08-11ea-9b2f-508eb0079ce7.jpg)

**Comment by jurialmunkey** [comment]
Can you try latest master and see if that helps?

**Comment by Blurayx** [comment]
> Can you try the latest master and see if that helps?

unfortunately, it didn't work. something must be corrupted. Going to do a fresh install.

**Comment by Blurayx** [comment]
Update:
After a fresh install, I still have the same issue

**Comment by jurialmunkey** [comment]
Hmm, not sure why it's not working. Working fine for me on two different machines. Must be some weird android quirk.

I'll just keep trying a few different things - can you try latest version and see if that helps.

**Comment by Blurayx** [comment]
You're a genius!!!

The actor info is working again on my mac & Nvidia TV 😀

Thank you

**Comment by jurialmunkey** [comment]
So weird that way worked and the other way didn't! Glad it's working now.

**Comment by Blurayx** [comment]
First I updated my mac but before I installed v0.5.25 on the Nvidia, I tested the Actor info to make sure it still wasn't working just to make sure nothing wired was going on. what did you change?
