### ISSUE TITLE
[Bug]Overview & Search

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#266]
Hiya @jurialmunkey please see below video and image.

Video showing Information & Movies overlay and Search: https://imgur.com/a/pGrKE27
Am I supposed to get any Search pop-up box or something on clicking Search in above video?

Information & Movies overlay screenshot: https://imgur.com/a/XAMLBfa

**Comment by jurialmunkey** [comment]
Overview fixed.

Search button passes the title of the movie/episode to the search window - there's no pop-up. You're getting a blank screen because you're getting no search results for that search term in whatever search lists you've got configured.
