### ISSUE TITLE
[Bug] unable to Browse Seasons of TmdbHelper widget of TV Shows (non-library)

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#27]
(for example Trending TV Shows or Garys New Shows-Trakt list)

The widget is filled with different shows.

If you short-click a show, you can't browse for seasons.  You can only add to watchlist (good feature btw).

If you long-click, there neither is a context-menu to browse the seasons.

For library TV Shows there is a browse button in the information screen.

**Comment by jurialmunkey** [comment]
I'm assuming that you have "Show Information" as your action when clicking an item and not Kodi's default "Play/Browse" action? And so you're talking about "Browse" missing from the info dialog and not just normal clicking on an item?

**Comment by DaisyF8** [comment]
Setting/Video/Default select action is set to Show Information yes.

... Eum... and now I see the Browse button without problem.

I only upgraded two hours ago from 0.1.12 to 0.1.17 and probably that fixed everything ...

Sorry about all these issues I opened. I'll look into the other ones to see if everything I mentioned is resolved now.

**Comment by jurialmunkey** [comment]
Yeah I think I fixed the browse button in one of the previous releases. Best to download the most recent release on github when encountering bugs as the repo version does lag behind if I'm pushing frequent updates since drinfernoo has to update it manually.

**Comment by drinfernoo** [comment]
Trying to keep up as fast as I can 😁
