### ISSUE TITLE
[Feature] - Submenu itemlayout backgrounds

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#270]
As requested by @SerpentDrago here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/269#issuecomment-686084229

**Comment by SerpentDrago** [comment]
to be clear ,  i would request it can be user set backgrounds . so you wouldn't need to supply them . 

Thanks

**Comment by jurialmunkey** [comment]
Oh yeah definitely user set backgrounds for submenu.

**Comment by drinfernoo** [comment]
As long as the "icon only" submenu doesn't get lost... I prefer a more minimal approach 😅

**Comment by jurialmunkey** [comment]
Definitely - Keeping the submenu background set to none will keep it as it currently is. Only will change if you set a background

**Comment by SerpentDrago** [comment]
and option to set NO icon also so it would only show label + background ? 

the way this is done in auramod is the user sets it to the icon called "none" , but i dont' know if there is prob a better way

**Comment by jurialmunkey** [comment]
^^^ Done and done.

Set single image background for submenu to use. Set to None to remove. Don't use multi-image because it won't work since controls are not persistent between itemlayout and focusedlayout (i.e. it would show a different image as soon as focused).

First icon in the icons folder is called `_none.png`. Set this icon to clear the icon and center text.

Also works in showcase hub.

**Comment by SerpentDrago** [comment]
bad ass ! thanks

![image](https://user-images.githubusercontent.com/21133858/92247910-e6ec3900-ee95-11ea-8391-0c8de7058989.png)

**Comment by drinfernoo** [comment]
I definitely prefer icons lol
