### ISSUE TITLE
[Bug] TV & Movie actor info 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#274]
The TV & Movie actor info issue is back but this time I get a poster option.  
https://github.com/jurialmunkey/skin.arctic.horizon/issues/264

Downgraded back to v0.5.25(Actor info working)

**OS iMac & Nvidia Shield TV**
After selecting actor info
![1](https://user-images.githubusercontent.com/2873112/92099904-ffdfe600-edd2-11ea-9b08-910939e4167b.jpg)

**Comment by jurialmunkey** [comment]
Check that you have "Use online information" turned on:
`Skin Settings > Lists and other > Customise info dialog lists > Use online information`

**Comment by Blurayx** [comment]
> Check that you have "Use online information" turned on:
> `Skin Settings > Lists and other > Customise info dialog lists > Use online information`

Ah, it was turned off. Actor info working again. is the "Use online information" a new feature?

**Comment by jurialmunkey** [comment]
> 
> 
> > Check that you have "Use online information" turned on:
> > `Skin Settings > Lists and other > Customise info dialog lists > Use online information`
> 
> Ah, it was turned off. Actor info working again. is the "Use online information" a new feature?

No it's always been there - it's just with 0.5.0 I switched the default settings to be more performance orientated - e.g. online lists, ratings and waves animation turned off by default. Eventually I'll have a skin initialisation dialog that on first run will ask the user whether they want to enable these performance impacting features or not.
