### ISSUE TITLE
[Fix] Custom_1111_NextAired_Library.xml

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#277]
1080i/Custom_1111_NextAired_Library.xml
replace
>     <onload>SetProperty(Header_Left_Text,$LOCALIZE[31155])</onload>
to
>     <onload>SetProperty(Header_Left_Text,$LOCALIZE[31046])</onload>

**Comment by jurialmunkey** [comment]
Good spotting! Not sure how that happened. Fixed now. Thanks! 😁
