### ISSUE TITLE
[Feature] - Lovefilm widget aspect to connect with submenu

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#278]
As requested by SerpentDrago here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/269#issuecomment-686084229

**Comment by jurialmunkey** [comment]
@SerpentDrago - Lovefilm aspect widget added

![Honeyview_screenshot248](https://user-images.githubusercontent.com/4618719/92318198-22306880-f04c-11ea-9df2-7862ad91c61a.jpg)

![Honeyview_screenshot249](https://user-images.githubusercontent.com/4618719/92318199-23fa2c00-f04c-11ea-933c-96d24af9a198.jpg)

**Comment by drinfernoo** [comment]
Does it not go with other widgets?

**Comment by SerpentDrago** [comment]
Omg thank you!

**Comment by jurialmunkey** [comment]
@drinfernoo - Obviously not as neatly as standard height widgets, but yeah it plays nicely with other widgets. Only recommendation is to not put it near other info widgets because the double up of info looks weird (i.e. don't put it directly under fullscreen widget or directly above a display info widget) 

![Honeyview_screenshot251](https://user-images.githubusercontent.com/4618719/92318399-46da0f80-f04f-11ea-8940-d46111160157.jpg)
![Honeyview_screenshot253](https://user-images.githubusercontent.com/4618719/92318400-480b3c80-f04f-11ea-837b-65762fdee326.jpg)
![Honeyview_screenshot252](https://user-images.githubusercontent.com/4618719/92318404-4b062d00-f04f-11ea-8a96-6c3d7db993cc.jpg)
![Uploading Honeyview_screenshot254.jpg…]()

**Comment by drinfernoo** [comment]
I just want to highlight a particular quirk here:

I've replicated something similar to your screenshots above, but scrolling *up* through the widgets... when the Lovefilm widget is highlighted, it becomes cut off (even though still focused and interactable), as it looks in your first image.

Is that fixable?

**Comment by jurialmunkey** [comment]
The widget in slot 2 has special positioning which forces it into the second row so that it works properly with the fullscreen widget. If I could just figure out a way to get properties of the first widget in the second widget template then I'd be able to solve it.

Most of the time I can use a trick of referencing hidden list id="3700" which contains all the properties of widgets in the group. The problem in this instance that lists only fill _after_ include conditions evaluate and I need something that works for includes.
