### ISSUE TITLE
It is not possible to use Kodi's Play using (External Player) feature in the context menu

### ISSUE THREAD

**Issue by Bateman34** [jurialmunkey/skin.arctic.horizon#282]

**Comment by jurialmunkey** [comment]
Skins don't control context menu items.

**Comment by Bateman34** [comment]
> Skins don't control context menu items.

Are you going to fix it or is it unfixable?

**Comment by drinfernoo** [comment]
@Bateman34 It isn't his issue to fix, as it's not something the skin even has *control* over.

You have some other non-skin-related issue.
