### ISSUE TITLE
[Feature] pressing back while a video is playing closes the video

### ISSUE THREAD

**Issue by daking1512** [jurialmunkey/skin.arctic.horizon#286]
would it be possible to have the option to close whatever is playing when we press back (when OSD is not visible)?

**Comment by drinfernoo** [comment]
You can do this yourself by mapping the back button to "Stop".

**Comment by jurialmunkey** [comment]
Yeah I think this one is better solved using the keymap rather than via a skin setting.
https://kodi.wiki/view/Keymap

Keymap editor addon is a useful GUI option:
https://kodi.wiki/view/Add-on:Keymap_Editor
