### ISSUE TITLE
[Feature] close video playing by clicking back

### ISSUE THREAD

**Issue by daking1512** [jurialmunkey/skin.arctic.horizon#289]
would it be possible to have the option to close whatever is playing by pressing back (no background playback) when the OSD is not visible? 

OSD visible > Press Back > Hides OSD > Press Back > Closes currently playing content and goes back to previous screen

**Comment by jurialmunkey** [comment]
Question was already answered here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/286

**Comment by jurialmunkey** [comment]
You can do this with a keymap. Keymap allows you to set specific actions for buttons based upon which window is visible/active. Set keymap to close for back in videoosd, set keymap to stop for back in fullscreenvideo

**Comment by daking1512** [comment]
didnt know about this, thank you I really appreciate it
