### ISSUE TITLE
[Bug] Widgets of Movie library aren't shown

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#29]
These widgets aren't shown :

ActivateWindow(Videos,"/folder/location/*",return)                                  (maybe by design).
ActivateWindow(Videos,library://video/movies/titles.xml/,return)
/home/myname/.kodi/addons/skin.arctic.horizon/extras/playlists/NewMovies.xsp

**Comment by DaisyF8** [comment]
I don't know what happened, but all 3 are loading now.

**Comment by jurialmunkey** [comment]
Haha! I was literally just about to comment that these work fine for me:

![Honeyview_screenshot636](https://user-images.githubusercontent.com/4618719/77013689-a884bf80-69c4-11ea-8682-695d3e5f3f88.jpg)

**Comment by DaisyF8** [comment]
I feel bad :) So stupid... And probably because I was still on 0.1.12

**Comment by jurialmunkey** [comment]
> 
> 
> I feel bad :) So stupid... And probably because I was still on 0.1.12

Don't worry about it!

It's weird that it was happening at all. I use the NewMovies playlist widget in my default setup and it has worked the whole time for me right from the first release. Something odd was definitely happening in your setup and I'm not sure what would have caused/resolved it.
