### ISSUE TITLE
[BUG] PVR Playback Fast Forwards when returning from Menu

### ISSUE THREAD

**Issue by Peelige** [jurialmunkey/skin.arctic.horizon#291]
Hi @jurialmunkey,

Second bug (not just arctic horizon, but many skins) 

- skin option to show now playing video is set to off
- TV channel is playing
- menu opened and navigated for a while, eg. tv guide, but nothing chosen and got back to current channel
- when return to the current TV channel it will fast forward for a few seconds.

I add this to fix in  Includes_Dialog.xml
```

<include name="Dialog_Notification_Group">
<!-- more code -->

<control type="videowindow">
<visible>Player.HasVideo + !Skin.HasSetting(global.showvideo)</visible>
	<height>1</height>
	<width>1</width>
</control>

<!-- more code --->

```
I can send a video of what the problem is if you like...

**Comment by jurialmunkey** [comment]
Can you test latest master and see if that fixes things for you?

**Comment by Peelige** [comment]
Tested just now; confirmed resolves the problem... thankyou!
