### ISSUE TITLE
[Request] - Hide widget hint text for offscreen widgets

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#293]
when I set Display info to "TRUE". is there an option for the widget text info(bottom) to only appear when in use?
personally I know that "Recently added" is there.

<img width="1338" alt="1" src="https://user-images.githubusercontent.com/2873112/95578517-e8c49180-0a2b-11eb-86b7-1c8984cdad80.png">

![2](https://user-images.githubusercontent.com/2873112/95578688-33460e00-0a2c-11eb-8397-d7603a677a96.jpg)

Example
![3](https://user-images.githubusercontent.com/2873112/95578565-fe39bb80-0a2b-11eb-9c7b-23c6d5fd5113.jpg)

Thanks

**Comment by jurialmunkey** [comment]
Sorry I've taken so long to respond to this - just been busy with the TMDbHelper rewrite plus work so I've barely looked at the skin for a while!!

I like the idea, just not quite sure how to implement it yet -- I'll have a think about it and get back to you.

**Comment by Blurayx** [comment]
No worries, I'm just glad you're ok😀
Thank you for considering implementing the feature. I assume you were rewritingTMDbHelper for Kodi 19, sounds like a nightmare.

**Comment by jurialmunkey** [comment]
I've tried a few different things but I don't think this is going to be possible unfortunately (well it's possible but will cause other issues!).

I'll keep this issue open for the time being in-case I think of something but sadly not looking promising.

**Comment by Blurayx** [comment]
No worries. Thanks for trying😀
