### ISSUE TITLE
Option to pick different any view type

### ISSUE THREAD

**Issue by RandomGithubUsername** [jurialmunkey/skin.arctic.horizon#294]
First of all thanks for such amazing skin! This is going to be my Kodi skin for next few years (or until you come up with new one that looks better than this :D)

One small nit - Some of the addons I use don't set the content type (correctly) so Arctic Horizon only lists "Tags" and "List" as view type. Other skins aren't as restrictive and hence we can force different view type irrespective of what the addon describes the content as. 

Can you please update the skin so that we can pick any of the available view type? If you don't want to make that change, I would be glad if you can point me to the code that needs to be changed and I will edit for myself in my local copy :)

Thanks again!

**Comment by jurialmunkey** [comment]
You can change which viewtypes are available for which sections by changing the rules in this file:
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/shortcuts/skinviewtypes.json

It should be fairly self-explanatory:

For instance:
```json
"addons": {
            "rule": "Container.Content(addons)",
            "viewtypes": ["51", "501", "58", "50", "500"],
            "library": "51",
            "plugins": "500"
        },
```
So for any container with a content type addons you can select from the the viewtypes 51, 501, 58, 50 and 500. The default view for library will be 51 and for plugins it will be 500 (i.e. if you haven't chosen a view or if you reset back to defaults). Just add the other IDs to each rule in the viewtypes list. The corresponding names for each ID are listed at the top of the file.
This rule is for if the container content type is "addons" and so for any such container the viewtypes with IDs 51, 501, 58, 50 & 500 can be selected (The names the IDs correspond to are listed at the top of the file). For the library views, ID 51 is the default ID and for plugin views the default will be 500 (these are the viewtypes that will be used if the user hasn't yet selected a view type or if you reset all views back to defaults).
