### ISSUE TITLE
How do I get something to display on this part of the screen?

### ISSUE THREAD

**Issue by Jeremy0734** [jurialmunkey/skin.arctic.horizon#295]
![7358BD26-5705-458F-893F-2794A5A15F02](https://user-images.githubusercontent.com/40923902/95666450-5998a600-0b1f-11eb-8ff4-7b8a9a00d0ba.jpeg)

**Comment by drinfernoo** [comment]
Make sure that those items are having "clearart" filled (probably by adding a Fanart.tv API key).

**Comment by Jeremy0734** [comment]
> Make sure that those items are having "clearart" filled (probably by adding a Fanart.tv API key).

I actually just added a Fanart key. I have the 3 boxes check mark but no luck on it working.

**Comment by DaisyF8** [comment]
This is applicable toTmdbHelper right? Not a setting in Arctic Horizon.

Anyway in TmdbHelper you need to specify OMDb api key for that art I seem to remember.

**Comment by jurialmunkey** [comment]
@Jeremy0734 -Make sure you have clearart enabled in skin settings:
`Skin Settings > Appearance > Clearart`
