### ISSUE TITLE
[Feature] Disable lists in info dialog

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#3]
Options for disabling lists in info dialog need to be added.

**Comment by jurialmunkey** [comment]
---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/ba3ca4b887d4e23a554ee63bf6c39da6bccc540c

**Comment by jweinreich** [comment]
Hello JM,
Noticed a bug.
Enable all info dialog lists, **except crew**.
Can't scroll down on info dialog.

**Comment by jurialmunkey** [comment]
Ah yep, can confirm. Should be fixed now.

**Comment by jweinreich** [comment]
Confirmed, great work!
