### ISSUE TITLE
[Bug] Context Menu

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#300]
when there is more than one season context menu does not work. No issues with the Kodi default skin

One Season: context menu working
![screenshot005](https://user-images.githubusercontent.com/2873112/96333424-c7822780-1061-11eb-9b56-c0b0af0be888.png)

Two seasons: context menu not working when I press the enter button on the remote.
![screenshot004](https://user-images.githubusercontent.com/2873112/96333318-0794da80-1061-11eb-88cd-4a01c1351f2a.png)

Thanks

**Comment by drinfernoo** [comment]
The context menu doesn't work there. Browse into the season.

**Comment by Blurayx** [comment]
Thanks
