### ISSUE TITLE
Default home menu items and widgets differ from screenshots

### ISSUE THREAD

**Issue by otaviomad** [jurialmunkey/skin.arctic.horizon#301]
I am not sure whether this is a bug, something I'm forgetting to do or an intended feature and I'm dumb. I really like the layout on the screenshots and I wanted to replicate that without having to manually set up widgets and such. Also, the search isn't searching in TMDB, only locally. Is there any way I can get that?

**Comment by otaviomad** [comment]
I intended to include a screenshot in the original post but ended up forgetting about it. 
![image](https://user-images.githubusercontent.com/6334573/96639939-cfa7c480-12f8-11eb-9a0c-3789763399de.png)
It's weird because in the menu editor I can see the entries and widgets for Movies and TV Shows but they're not there.

**Comment by drinfernoo** [comment]
You don't have anything in your library, so they don't show up. Either point them somewhere else, or add something to your library

**Comment by jurialmunkey** [comment]
What screenshots? If you're referring to the first page of the Kodi forum thread, there's been changes in the skin since those were taken. I need to update all the screenshots.
