### ISSUE TITLE
[Bug] Submenu home widget links focus not working

### ISSUE THREAD

**Issue by azakaria** [jurialmunkey/skin.arctic.horizon#303]
Created multiple submenu hubs. For example - popular, top rated, and trending movies.

Then created created the submenu widget on the home. The widget correctly shows the 3 submenu hub links.

But when I click on any of the submenu links on the home widget, the first hub gets focus. One would expect the focus for the links on the home submenu widget to be respective to the submenu hubs. 

Seems to be a bug or am I missing something?

**Comment by jurialmunkey** [comment]
What do you mean by submenu hubs? I think there is some confusion about terminology here. You can only have one submenu hub per main menu item.

Some screenshots showing the issue you are having would be helpful.

**Comment by azakaria** [comment]
Here is a screen capture video of what I was trying to do - https://youtu.be/lEccnKbT62Y

The homepage has a submenu widget. Creating new submenus appears in that widget. If only one submenu can go to a hub, then the user experience would not be consistent. Except for just one submenu item, the other menu items would go to a different interface. Was hoping that each submenu would go to its own tab in the hub. How can this be achieved?

![image](https://user-images.githubusercontent.com/10538779/97659121-8b2ccf00-1a44-11eb-9e6c-d821b52a03ca.png)

**Comment by jurialmunkey** [comment]
Sorry, it doesn't work like that.  The submenu hub and the submenu widget are just two different ways to display the submenu for the main menu item. You can't link it back to itself or have a submenu of a submenu.
