### ISSUE TITLE
Widgets not loading, error in "plugin.video.themoviedb.helper"

### ISSUE THREAD

**Issue by vermope** [jurialmunkey/skin.arctic.horizon#307]
Hi, and apologies in advance if this is not the right place for my issue... Since a couple of days  when booting Kodi, 8 out of 10 times the widgets or addons wont load. The last entry  in the log shows following:

2020-11-09 15:47:24.498 T:140494791862016  NOTICE: [plugin.video.themoviedb.helper]
                                            Failed to import _strptime because the import lockis held by another thread.

I don't know if it's related to themoviedbhelper plugin or something else. I had the same issue with "Artwork Beef".
I've did a reinstall but same issue started quickly with only a few addons.

Here's a full debug log: https://paste.ubuntu.com/p/D3Nwxnwg7J/

**Comment by jurialmunkey** [comment]
Can you try with latest version of TMDbHelper from github (v4.0.41) and see if you still have the issue?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/master.zip

**Comment by vermope** [comment]
Works perfect now! Thank you very much.

**Comment by jurialmunkey** [comment]
Excellent! Let me know if you have any further issues. It's related to a long standing Python2 bug in the built-in datetime module, so I can't actually fix it per se and can only try to work around it -- so I wouldn't be surprised if it pops up again, but hopefully this change will at least minimise it's occurrence.

**Comment by vermope** [comment]
Yes, I had a feeling this was something that occured in more than one situation when I was googling... Hopefully this bug is resolved in Python3.
