### ISSUE TITLE
[Feature] - Display Info Widget on top

### ISSUE THREAD

**Issue by Prahlis** [jurialmunkey/skin.arctic.horizon#308]
The Display Info widget looks great on the homescreen. Especially when used on the top widget. I think it would be even better if there was an option to always use the Display info widget on the top widget, which isn't possible today if you have widgets that are time sensitive and sometimes empty (example: Movies added in the last 30 days).

Therefor I think it would be nice if the info box would stick to the top no matter what widget is currently at the top. Perhaps optionally it could even be static so only the row below the info box would change when scrolling instead of the entire thing.

**Comment by jurialmunkey** [comment]
It'd be nice but unfortunately not possible. Kodi skinning engine doesn't really give any control over where focused items are positioned in the grouplist.
