### ISSUE TITLE
[Feature] Lock home menu position

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#31]
Would it be possible to add an option to lock the side menu?
<a href="https://imgur.com/Okio7Cl"><img src="https://i.imgur.com/Okio7Cl.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Yeah I've been considering having that as an option. Might be useful for mouse/touch users.
I'll add it to my todo list.

**Comment by Blurayx** [comment]
Great!!

**Comment by drinfernoo** [comment]
Alongside this, what about "forced menu position"? I used this in Aura to define what the "default" main menu focus would be.

**Comment by jurialmunkey** [comment]
> 
> 
> Alongside this, what about "forced menu position"? I used this in Aura to define what the "default" main menu focus would be.

Yeah, that would be a good feature. Can you put it in a separate issue so that I don't forget about it.

**Comment by jurialmunkey** [comment]
Added in v0.1.56
---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/2d99cb3f466a0a56da50f7c4cb334f7d91595ac7
