### ISSUE TITLE
[Feature Request] Play A Different Trailer

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/skin.arctic.horizon#311]
Hey jurial, hope you are doing well!

I have a quick feature request if possible - the ability to either pull up a list of videos the Trailer button found so you can select one, or pull a different trailer. 

I’m not sure how this could be accomplished though, besides a context menu on the Trailer button or maybe a setting that swaps the Trailer button to always do a selectable list. 

Use case is occasionally it will pull a bad trailer (more like a teaser instead of a trailer) or the much more rare - something related but not a trailer. 

Thanks man and I really appreciate all the work you’ve done on this skin!

**Comment by jurialmunkey** [comment]
Not really possible. The trailer button just plays the path stored in `ListItem.Trailer`. It's something that the source of the item fills not the skin itself (e.g. If it is a library item, the library scraper will put the trailer in the library database, and if it is a plugin that plugin will fill it).

If you are talking about for inside TMDbHelper there are actually already two ways you can do this:

1. `Context Menu > Browse lists > Videos`
2. Play the item and use the Search with Youtube player.

Also, if you install the latest version of TMDbHelper and its accompanying context menu addon you can get the Browse Lists context menu item for non-TMDbHelper items (adds an extra context menu option called TMDbHelper Options)
https://github.com/jurialmunkey/context.themoviedb.helper
https://github.com/jurialmunkey/plugin.video.themoviedb.helper

**Comment by Demonseeed** [comment]
Good to know, thanks for detailed response!

I will check out the update and context menu, thank you for the tip.
