### ISSUE TITLE
Initialising Skin

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon#312]
Hi. Installed Arctic Horizon on a fresh install of osmc on a Vero 4k. I keep getting a 'Initialising Skin' message on the splash screen, which does not let me back into the skin. The circular loading icon just keeps spinning. I've tried this on a few fresh osmc installs and the same thing keeps happening. Installed skin from your repo. Wondering if there is a known issue, or if this is possibly an osmc issue. Thanks.

**Comment by Tee77** [comment]
apologies - network issues were causing the problem.

**Comment by Tee77** [comment]
Osmc team can reproduce the issue so looks like it’s a problem on their side.

**Comment by jurialmunkey** [comment]
If it is stuck on Iniitialising it generally means that SkinShortcuts either wasn't installed or didn't run correctly.
