### ISSUE TITLE
Initialising skin

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon#313]
Hi. OSMC team resolved an issue on Vero 4K relating to switching skins which I thought was the reason behind the AH ‘initialising skin’ splash screen message, which hangs and doesn’t let me back in the skin. However, since their update the same behaviour has happened again. Generally occurs when either adding tmdbhelper widgets to Home Screen (skin goes to update then goes straight to splash screen) or sometimes when cleaning media library. Wondering if this is a skin issue? I noticed another user on the forum has experienced this behaviour but not sure on what device.
Logs if useful: https://paste.osmc.tv/ejefoxaqay

**Comment by Tee77** [comment]
Sorry to have hassled you about this again! I ended up deleting skin.shortcuts cache and it seems to be behaving now.

**Comment by jurialmunkey** [comment]
> 
> 
> Sorry to have hassled you about this again! I ended up deleting skin.shortcuts cache and it seems to be behaving now.

Literally just came on here to suggest exactly that!

Occasionally skinshortcuts settings get corrupted and then it won't load, which means no home menu for AH.

**Comment by Tee77** [comment]
Thanks man, appreciate that!
