### ISSUE TITLE
Adjust PVR info shown in the fullscreen widget

### ISSUE THREAD

**Issue by kalle2000** [jurialmunkey/skin.arctic.horizon#315]
Dear @jurialmunkey 

I recently have installed this screen (coming from Zephyr 2) and I am thrilled.
Still I'd like to ask for an adjustment: I am using a PVR and configured the home screen to show the latest played channel. As I am using pvr artwork this looks really nice, however there is some info I am missing.

This is how it looks for my Shows library: [Screenshot](https://ibb.co/HC4crfM)
Below the show name, there is additional info (like year, MPAA rating and watched progress for shows / duration, end time for movies). For PVR some internal info is shown (Systemname of Kodi and version of the skin).

Can you adjust that row to show: Name of the PVR Channel, Year and start/end time? Basically same information as shown in the programme information screen. By the way, on the full screen widget the button "more information" does not work (I expected it fwd to programme information).

Thank you so much.

**Comment by jurialmunkey** [comment]
I can't recreate this issue. How are you setting this PVR widget because it works perfectly fine for me using the All Channels widget from `Default Widgets > PVR > All Channels`

![Honeyview_screenshot00001](https://user-images.githubusercontent.com/4618719/108943143-5d7f2c00-76ac-11eb-96c2-b11e585381f0.jpg)

![Honeyview_screenshot00000](https://user-images.githubusercontent.com/4618719/108943148-5fe18600-76ac-11eb-8094-e165fc7e1f25.jpg)

**Comment by kalle2000** [comment]
I just checked my setup. I am using a different widget instead: Additional Widgets --> Skin Helper Service Widgets --> PVR --> TV channels: <channel group provided by PVR>
So probably this issue is not related to the skin itself, right?

**Comment by jurialmunkey** [comment]
Yeah that's an issue with Skin Helper not providing full details.

Just use the default widgets supplied under the PVR section because they are direct Kodi paths and so will likely also perform better in general.

**Comment by kalle2000** [comment]
Thx for clarification.
I prefer Skin Helper as I can select on channel group and its displaying PVR artwork which I do not see when using the default PVR widgets

**Comment by kalle2000** [comment]
@jurialmunkey looks like this is a skin issue after all: [skin.helper.widget issue](https://github.com/kodi-community-addons/script.skin.helper.widgets/issues/44#issuecomment-808348070)

**Comment by jurialmunkey** [comment]
Angelinas is saying that the info is provided via skin helper service - which is not the widget plugin but an extra service monitor layer on top. I don't want to use skin helper service.

So I am correct. The widget is not providing that info. Relying on yet another service monitor to pull the info is not a solution, particularly when Kodi's native pvr paths provide the full info directly. A service monitor provides info as window properties which cannot be used inside the list.

**Comment by jurialmunkey** [comment]
Angelinas is saying that the info is provided via skin helper service - which is not the widget plugin but an extra service monitor layer on top. I don't want to use skin helper service.

So I am correct. The widget is not providing that info. Relying on yet another service monitor to pull the info is not a solution, particularly when Kodi's native pvr paths provide the full info directly. A service monitor provides info as window properties which cannot be used inside the list.
