### ISSUE TITLE
[Request] Add toggle in settings to remove osd while player is paused 

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#316]
Hi

I don't like the seekbar showing while I pause.  

I used to remove "|Player.Paused" in the visible-tag (line 6) of DialogSeekBar.xml and that would work.

But something changed the last couple of months ? Doesn't work anymore.

Would a setting be possible?

**Comment by DaisyF8** [comment]
EDIT : Making this a request

**Comment by jurialmunkey** [comment]
What would show when the movie is paused? Nothing at all or would it be that there is still time/clock displayed on screen?

**Comment by DaisyF8** [comment]
I actually prefer nothing showing at all.

**Comment by DaisyF8** [comment]
I don't know if you watch anime but when they also translate all the written text on-screen I need a moment and pauze and read. The bottom ui sometimes blurs text. 

Also for when they are talking fast the subs are very long and gone in a second. But the ui is in front of the text on pauze.

edit : spelling

**Comment by DaisyF8** [comment]
Even just a pointer from you to where in the files I could disable the osd while paused would be greately appreciated.  I used to do it by removing "Player.Paused |" from DialogSeekBar.xml in 1080i, but that doesn't work anymore.  Probably another condition is TRUE making the osd visible while paused that I'm missing.

**Comment by DaisyF8** [comment]
Nevermind :D 

I looked at it again and removed
` | Player.Paused `
and hey presto, no more osd on Pause.  I don't know what went wrong more than a year ago to make me think something about the condition had changed.
