### ISSUE TITLE
Kaito Addon Not opening with AH Skin

### ISSUE THREAD

**Issue by sathish804** [jurialmunkey/skin.arctic.horizon#321]
Hi,
When trying to open the Addon Kaito I am getting blank screen with AH skin where as with the default kodi skin I don't see any issue. 

Log : https://controlc.com/d77ea6b4
![Screenshot_20210104-080203](https://user-images.githubusercontent.com/14090242/103509707-0905c000-4e64-11eb-96d4-58ff0e8e21a5.jpg)

Kodi version 18.9
AH Version 0.5.55
Os Android 10

Update: On my Sony Android tv with Android version 8 and kodi version 18.9, i don't see this issue with same version of AH skin. 

Thanks and Regards, 
Sathish.

**Comment by sathish804** [comment]
Issue solved after changing the content type to addons in Kaito settings.

**Comment by jurialmunkey** [comment]
@sathish804 - Glad you got it to work. Do you know what the content type was before you changed it? Sounds like I'm missing a viewtype definition for whatever content type it was previously, so that would be good to fix nonetheless.

**Comment by sathish804** [comment]
@jurialmunkey  by default that addon not setting any content type. In settings that addon developer gave a check box to set content type, after enabling it gave options for content type, in which I choose content type as Addons.

**Comment by jurialmunkey** [comment]
@sathish804 - Thanks for the reply/info - it is really useful! I'm going to have a bit more of dig around in the skin code because if no content type is set the list and tags viewtypes are still meant to be available -- it sounds like there's a bug in one of the visibility conditions somewhere that I've missed.
