### ISSUE TITLE
Add Color inversion for settings menu

### ISSUE THREAD

**Issue by coldspark29** [jurialmunkey/skin.arctic.horizon#323]
I was looking for a dark mode yesterday and found the color inversion for the left bar of the main menu. Haven't found this for the settings menu though. Can you implement that?

**Comment by jurialmunkey** [comment]
You can change the colour scheme in kodi appearance settings (where you change skin) - you need to have expert settings level on to see the option.

**Comment by coldspark29** [comment]
Thanks! Really great skin by the way. Best one I've stumbled over
