### ISSUE TITLE
[Bug] Widget background becomes opaque when "Display info" is checked

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#327]
See picture

![screenshot005](https://user-images.githubusercontent.com/10348988/104232026-03a20a00-5450-11eb-9f5f-81397c0854f8.png)

**Comment by jurialmunkey** [comment]
Are you sure you don't have opaque divider enabled in `Skin Settings > Appearance > Divider style` ?

**Comment by DaisyF8** [comment]
Correct and that solved it.

I never knew what that setting did. And even now, after seeing it's effect I'm still puzzeled. Only the background behind that one widget got opaque...

What is it that gets divided that that setting makes opaque?

(I've played with it now for a while again and can't figure it out.)

**Comment by jurialmunkey** [comment]
Divider is used when there is info with content - mostly to give a hard bottom edge for the clearart to sit on. It is also used in info dialog to separate content from the poster

**Comment by DaisyF8** [comment]
Thanks for explaining.
