### ISSUE TITLE
[BUG] Endless Busy Spinning Wheel and NOT returning to previous Information Tab

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon#328]
Okay, so when you jump into "Information" clicking on a title from a home widget in my example a Seren Widget and you scroll down to "Similar, Genre, From Studio, Recommended" titles based on the one you're looking at, we know those are being shown by Tmdbhelper and once you click on one of them you're being transferred from Seren title Information Tab to TMDbHelper's Information Tab in order to access the title you clicked. 

**Bug Description**

So, from homescreen Seren widget when I click on a title to look at the Info, then I scroll down a bit I see one title in the "Similar, Similar Genre, From Studio" row or any other which are being presented from the tmdbhelper Addon. I click on one of the titles, now I'm being transferred to tmdbhelper to look at the information of that title. Great, now I want to see the Trailer, once I stop the trailer if for some reason I didn't liked. Now I get a Busy spinning wheel which won't stop until I completely reboot Kodi. Or hit the back button a couple of times until it brings me back to the Kodi homepage. However, it won't take me back to the information tab of that title I that just watch and stopped the trailer.

I understand my explanation of the bug might seem a bit confusing to understand, which is why I got a small clip here which will show you the BUG being reproduced in action.

[Reproducing the Bug](https://imgur.com/a/AfYipuf)

**Comment by jurialmunkey** [comment]
Are you still having this issue? I'm unable to recreate it.

**Comment by Nuklear92** [comment]
> Are you still having this issue? I'm unable to recreate it.

I'm currently in Matrix and waiting for AH to be available. I believe you have released a version for it, I'll try out and report back if the issue still persist.

**Comment by Nuklear92** [comment]
@jurialmunkey Trying out AH In Matrix right now and the issue seems to be resolved! It doesn't hang endlessly anymore on the busy spinning wheel after a trailer is stopped. 

Idk if you actually did something with AH in the transition to Matrix or if it's just the Python 3 code working more reliable and responsive overall in Kodi, but this issue is no longer apparent in 19. By the way, I gotta thank you for bringing AH to Matrix. Honestly, I was using K19 with Estuary because I couldn't find any other supported skin to click with me and been always a AH fan. It's literally the best skin I have ever stick with when using Kodi, and I'm very pleased you didn't abandoned I hope you can keep making it even better and in the future. There's many of your skins that didn't got the same luck as this one. 

Keep the great work! 👍

Closing this issue now.

**Comment by jurialmunkey** [comment]
Awesome! Glad it is working - I remember slightly changing a few things with how the trailer window was handled in the info dialog and I think it fixed this issue in the process.

> It's literally the best skin I have ever stick with when using Kodi, and I'm very pleased you didn't abandoned I hope you can keep making it even better and in the future. There's many of your skins that didn't got the same luck as this one.

It's my daily driver so definitely not going anywhere.
