### ISSUE TITLE
[Bug] TMDbHelper matching in Library Calendar

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#33]
Hi, jurialmunkey

I have noticed all my tv shows with brackets eg(2015), Don't show on my TV Shows Airing Today(TMDBHelper) home screen. Is there a setting in Kodi to ignore brackets?
Alternatively if possible, add an option setting in TMDBHelper to ignore brackets.
If I use the Skinhelper option my TV shows with brackets display the widgets.

Update: just found out, The brackets I removed from my TV Shows are non-responsive
<a href="https://imgur.com/dwhswqT"><img src="https://i.imgur.com/dwhswqT.png" title="source: imgur.com" /></a>
https://github.com/jurialmunkey/skin.arctic.horizon/issues/20#issuecomment-600817013

**Comment by jurialmunkey** [comment]
I'm working on some better matching methods in TMDbHelper for TVShows to try to avoid these types of issues (i.e. by matching with IDs and some other approaches).

Currently the best way to ensure proper matching is to use the TMDb scraper for TVshows.

**Comment by Blurayx** [comment]
Ok, Thanks 😃

**Comment by Blurayx** [comment]
TMDbHelper(using the latest release) not recognising The Walking Dead

<a href="https://imgur.com/ilUtL9m"><img src="https://i.imgur.com/ilUtL9m.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/cFM1Yv4"><img src="https://i.imgur.com/cFM1Yv4.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/jesf7mC"><img src="https://i.imgur.com/jesf7mC.png" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
You’re a star 🌟 
Works perfectly , Thank you 😀

**Comment by Blurayx** [comment]
Was it a nightmare to fix?

**Comment by jurialmunkey** [comment]
I think it might still be an issue in some spots, actually... Still need to work on getting the ID matching to work better.

**Comment by Blurayx** [comment]
it's working great so far. If I encounter any issues do you want me to report it here(TMDbHelper matching in Library Calendar) or start a new bug report?

**Comment by jurialmunkey** [comment]
> 
> 
> it's working great so far. If I encounter any issues do you want me to report it here(TMDbHelper matching in Library Calendar) or start a new bug report?

I just added a few a more tweaks that I think should improve the matching by ID a bit more. So hopefully it all works properly now!

If you do encounter any other issues with the matching just open a new issue thread on the TMDbHelper github so that I notice it.

**Comment by Blurayx** [comment]
Ok 😀
