### ISSUE TITLE
Debug Info does not show gridlines

### ISSUE THREAD

**Issue by mechevarria** [jurialmunkey/skin.arctic.horizon#331]
Showing Debug Info does not have any gridlines. Might not be an issue for you but without gridlines I probably will have no idea if I am screwing up the alignment of media in any changes I plan on making for AEL. Attached a screenshot

![no-grid-lines](https://user-images.githubusercontent.com/2657771/104642802-63c7c480-5679-11eb-9f0b-5b8f09bee390.jpg)

**Comment by jurialmunkey** [comment]
`Skin.ToggleSetting(DebugGrid)`

**Comment by mechevarria** [comment]
Yes, this is correct, lol. For dummies like me you can enable all the debugging information with the following. In the kodi settings directory add the following file (Linux example).

`~/.kodi/userdata/keymaps/keyboard.xml`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<keymap> 
    <global> 
        <keyboard> 
            <F5>ReloadSkin()</F5> 
            <F6>Skin.ToggleSetting(DebugInfo)</F6>
            <F7>Skin.ToggleSetting(DebugGrid)</F7>
        </keyboard> 
    </global> 
</keymap>
```
