### ISSUE TITLE
Ratings don't show up

### ISSUE THREAD

**Issue by vidje** [jurialmunkey/skin.arctic.horizon#332]
For some reason only default ratings show up (tmdb, trakt), but no RT, metacritic or anything. The ratings are enabled in skin options and I've checked my TMDB Helper, I have both FanartTV and OMDB api keys there, as well as in Arctic Horizon settings.

edit:

Arctic Horizon: 0.5.57
TheMovieDB Helper: 4.2.10

edit2: 

I've downgraded to 2.4.36 and when I opened TMDB Helper I got a dialog saying "401 not authorized", which is weird as my API token is authorized. I've then proceeded to restart Kodi and delete my simplecache in between. I've gotten the 401 error again, but then on some movies RT, IMDB, and other ratings started showing up. Decided to upgrade back to 4.2.10 in hopes it would fix the api calls, but nothing. Same thing over and over again, some movies show all the ratings I've selected, some show only default ones that OMDB api key is not needed for. 

Here's the kodi debug log: https://pastebin.com/ZwwJdh8V

edit3: I've just noticed I posted this on the wrong tracker, should I repost to your tmdb helper issue tracker and close this?

**Comment by jurialmunkey** [comment]
You're getting a 401 error for OMDb which means unauthorised - either you've input your key incorrectly or you've hit your 1000 request limit for the day (but more likely you input key incorrectly).
