### ISSUE TITLE
[Bug] Focus missing for Showcase Hub buttons (Play and More Information)

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#333]
The main menu item-Action points to Showcase Hub (ActivateWindow(1150)).
My fullscreen widget is TmdbHelper-Popular movies, and the Hub widget is Netflix-Popular on Netflix (setting Hub widget is optional to recreate this bug).

While I'm in the main menu I can go to the buttons Play and More Information.
[Bug :] If I click and go in the main menu item (Action - Showcase Hub) I can't get the same buttons to focus by pressing down. I also can't reacht the Hub widgets.

This gets solved if you add a submenu item.  It gets focus when you open the main menu item, and then you can go up to reach Play and More Information.

**Comment by jurialmunkey** [comment]
The hubs are specifically designed around having submenu items. That's why they are called "Submenu Hubs". It is the very first line of the wiki on Hubs:

>Hubs are special windows that display the submenu items with attached hub widgets underneath.

https://github.com/jurialmunkey/skin.arctic.horizon/wiki/Hubs

If you don't have submenu items then the hubs will not work correctly.
