### ISSUE TITLE
Widget - Display info , be able to display above or below

### ISSUE THREAD

**Issue by sabre6** [jurialmunkey/skin.arctic.horizon#334]
Hello,

Would it be possible for this great feature (Display info on the widget), to be a able to "show above" "show below"  "or "no".  I use a submenu widget on top for all screens, and in this case have recently added movies.  It would be great to be able to fully show the line of movie poster/landscape, and then if interested, click down which then moves the submenu screen up and the display info will show fully under the movie poster/landscape.  Thank you.

**Comment by jurialmunkey** [comment]
Sorry, unfortunately not really possible with how the widgets are setup and how the skinning engine works - widget system is already overly complex in this skin and it'd just add way too much extra complexity to get it to work well.

**Comment by sabre6** [comment]
No worries at all. Not a big deal. Simple is best!
 
Thank you.
