### ISSUE TITLE
[Bug] Up Next support stopped working

### ISSUE THREAD

**Issue by cboswald95** [jurialmunkey/skin.arctic.horizon#335]
Hi, for several months I've been getting a "Playlist: can't find a next item to play" error when I attempt to use Up Next. I've tried adjusting the addon's settings, reinstalling, and even a clean install of Kodi, but the error persists.  Thanks in advance if you could find time to look into it.

**Comment by drinfernoo** [comment]
This doesn't seem like it would have anything to do with the skin. Up Next is a completely separate add-on, that works with library items, or with streaming add-ons which implement it... of which there are very few.

**Comment by cboswald95** [comment]
> This doesn't seem like it would have anything to do with the skin. Up Next is a completely separate add-on, that works with library items, or with streaming add-ons which implement it... of which there are very few, to my knowledge.

Hey thanks for the response, I thought it could possibly have to do with the skin since an earlier request on this github for compatibility seemed to have been addressed by @jurialmunkey.  I'll raise the same issue on the Up Next github and see what their take is.  

I'm attempting to use it for .strm files in my library if that's relevant. It worked flawlessly for months up until this point.

**Comment by unkn0wn234** [comment]
> > This doesn't seem like it would have anything to do with the skin. Up Next is a completely separate add-on, that works with library items, or with streaming add-ons which implement it... of which there are very few, to my knowledge.
> 
> Hey thanks for the response, I thought it could possibly have to do with the skin since an earlier request on this github for compatibility seemed to have been addressed by @jurialmunkey. I'll raise the same issue on the Up Next github and see what their take is.
> 
> I'm attempting to use it for .strm files in my library if that's relevant. It worked flawlessly for months up until this point.

From what I hear, UpNext addon's often is incosistent with the updates. I gave up on it and just used the built in addons UpNext features. Big S and Big F which are imo the best addons currently both have their own version of Up Next and it works with library .strms made through TMDBH too

**Comment by jurialmunkey** [comment]
I'm assuming this is an addon error and nothing to do with the skin.
