### ISSUE TITLE
Resume Indicators

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon#338]
when viewing a list from inside tmbdhelper, the watched indicators display the exact time I am currently on. This is shown in the image below. 

![inside-tmdb](https://user-images.githubusercontent.com/76912707/106000688-03884800-60a7-11eb-90c0-9106b2db08e8.PNG)

However, on the homescreen widgets, watched indicators are not displayed at all when viewing through tmdbhelper's 'In progress' section. 

![tmdbhelperwidget](https://user-images.githubusercontent.com/76912707/106001646-1cddc400-60a8-11eb-95c8-18068ffec9a3.PNG)

Using seren, I can get the watched indicators to show, but they don't display the exact time I am currently on (as displayed in the first picture) 

![serenwidget-min](https://user-images.githubusercontent.com/76912707/106002179-bb6a2500-60a8-11eb-85a2-fa0e3b73e141.PNG)

Is this a bug or am I doing something wrong? It would be nice to see my exact watch-time from my homescreen widgets, the same way it is inside the tmdbhelper addon. Any help will be appreciated. Thanks for your time.

**Comment by jurialmunkey** [comment]
This is an addon issue. It has nothing to do with the skin. In progress indicators work perfectly fine on widgets:
![Honeyview_screenshot300](https://user-images.githubusercontent.com/4618719/106150512-8a384480-61cf-11eb-83ca-656eec2fe68e.jpg)

It's all to do with the addons you are using. Open the addon in via Video Addons at the same place as you have the widget and you will see you don't have in progress indicators there either.

TMDbH only shows the resume point if you either played that item directly via that path in TMDbH or if you have the item in your library with a resume point set.

**Comment by rizreflects** [comment]
Thanks for you help. That makes sense. Since I have you here, there is another issue you could help me with. It seems that when I delete an item from my Trakt liked list, tmdbhelper does update and still shows those lists as liked. Seren doesn't have this issue. Is there a way to force refresh my liked list?

Thanks for you time.
