### ISSUE TITLE
[Request] Add theme selection to skin wizard

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#340]
Just like that 😁 We can choose the color scheme, but not between light/dark... Could that be added?

**Comment by jurialmunkey** [comment]
I would love to but afaik there isn't actually any built-in command to switch colour scheme definition. Kodi has a command to change texture themes but that's something different.

In the skin wizard all the colour selection does is set the highlight colour variables to a different value, it doesn't actually change the colour scheme itself.
