### ISSUE TITLE
[Dependency] Skin Shortcuts context menu "Add to my Lists"

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#341]
Not all of the targets that command generates are valid anymore I think.  But can they mess up my setup ?

Just wondering.

**Comment by jurialmunkey** [comment]
I have no idea honestly. I've never used the SkinShortcuts context menu addon. I tried installing it just before but I wasn't able to get the context menu item to display.

**Comment by DaisyF8** [comment]
Okay thanks
