### ISSUE TITLE
[Bug] installing from zip file

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#342]
I decided to do a fresh install but I can't get the latest zip files to install
SkinVariables
TMDBHelper
Arctic Horizon

repository.jurialmunkey-2.0.zip installs but only SkinVariables installs

https://user-images.githubusercontent.com/2873112/106371208-9c45ee80-6359-11eb-8e40-2578c101ce73.mp4

Update: I think it's a problem with Kodi.

**Comment by jurialmunkey** [comment]
Yeah that's an official Kodi Repo issue where it isn't fulfilling one of the module dependencies. I'm sure it will be fixed soon but in the meantime you can manually install that module dependency and then try reinstall TMDbH.
https://mirrors.kodi.tv/addons/leia/script.module.idna/

**Comment by Blurayx** [comment]
> Yeah that's an official Kodi Repo issue where it isn't fulfilling one of the module dependencies. I'm sure it will be fixed soon but in the meantime you can manually install that module dependency and then try reinstall TMDbH.
> https://mirrors.kodi.tv/addons/leia/script.module.idna/

Thank You 😀
