### ISSUE TITLE
[Request] Easy access to "Manage" option for vidoes.

### ISSUE THREAD

**Issue by ConnorS-P** [jurialmunkey/skin.arctic.horizon#343]
In some other skins I've used there has been an option to edit things like title, plot, etc. by opening a context menu option called "manage" while hovering over a movie. In some skins, this could even be done through widgets within a home menu tab ("Random Movies" in the "Movies" home menu tab for example), rather than having to find the movie in the source folder. Would it be possible to add this functionality to this skin?

(My use case is when I have a 2-disk DVD that I have as an iso file, I like being able to append something like "Bonus Disk" to the title of the second disk while retaining all the scraped metadata for the primary film.)

**Comment by jurialmunkey** [comment]
Skins don't determine what is in the context menu. The entries in the context menu are determined by Kodi.
