### ISSUE TITLE
PosterRow viewtype, but vertical view

### ISSUE THREAD

**Issue by fatshotty** [jurialmunkey/skin.arctic.horizon#344]
Hello there,
first of all very good job, I love this skin.

Just a question:
Is it possibile to make PosterRow viewtype (for movie and tvshows) also in vertical?

I mean:
posterrow is very good viewtype, for me, because I can have an instantly overview information about movie/tvshow. Moreover, at the bottom, I have the alphabetical strip. Love it!
But all posters can be scroll only via horizontal view and this is a little strange.
So, I changed viewtype in PosterWall, but no overview abount movie/tvshows info and no alphabetical strip :(

Thank in advance

**Comment by jurialmunkey** [comment]
This skin focuses on horizontal views - it purposefully doesn't have vertical views other than list.
