### ISSUE TITLE
[Question] backup skin settings

### ISSUE THREAD

**Issue by fatshotty** [jurialmunkey/skin.arctic.horizon#345]
Hello there,
can I backup skin settings? I can't find the "backup/restore" section

thanks

**Comment by jurialmunkey** [comment]
There's issues with the Skin Helper backup so I don't use it anymore.

It's easy to make a manual backup. Just make a copy of the `script.skinshortcuts` (for home/widget layout) and `skin.arctic.horizon` (for other skin settings) folders found in the `addon_data` directory

`.kodi/userdata/addon_data/script.skinshortcuts`
`.kodi/userdata/addon_data/skin.arctic.horizon`

**Comment by fatshotty** [comment]
many thanks, I'll try soon ;)
