### ISSUE TITLE
New Kodi Update - Matix

### ISSUE THREAD

**Issue by Jackp7173** [jurialmunkey/skin.arctic.horizon#349]
Will you be updating Arctic Horizon to be compatible with the new Kodi update?
Thanks

**Comment by drinfernoo** [comment]
https://forum.kodi.tv/showthread.php?tid=351756&pid=3013231#pid3013231

**Comment by Jackp7173** [comment]
Much appreciated

**Comment by jurialmunkey** [comment]
Hopefully should have something ready in the next week.
