### ISSUE TITLE
[Bug] Sub menus disappearing 

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#35]
Hi thanks for the great skin -
I have added a sub menu widget to the live tv section. It displays and works fine however if I press down and change to the add-ons section and then change back to the live tv section the sub menu widget has disappeared. 
I can get it to come back by loading the settings menu and returning to the main menu - but they keep disappearing.

Regards

**Comment by jurialmunkey** [comment]
Can you post your `script-skinshortcuts-includes.xml` file from the 1080i folder of the skin? I'm wondering if there is some weird visibility condition that skinshortcuts is introducing that shouldn't be there.

**Comment by sammy2142** [comment]
Hi here it is:
[script-skinshortcuts-includes.zip](https://github.com/jurialmunkey/skin.arctic.horizon/files/4357074/script-skinshortcuts-includes.zip)

**Comment by jurialmunkey** [comment]
Thanks. Okay I've manage to replicate the issue. Not quite sure what is causing it but I'm looking into it. I'll keep you updated once I have a fix to test.

**Comment by sammy2142** [comment]
Awesome thanks 👍

**Comment by jurialmunkey** [comment]
I think I might have fixed the issue. Can you test v0.1.22?
https://github.com/jurialmunkey/skin.arctic.horizon/archive/v0.1.22.zip

**Comment by sammy2142** [comment]
Hi I can confirm it works - thanks :)
I've got a new bug in this version though (it was not present in the previous one).
In the sidebar (which you use to change between movies, tv shows etc) - If you push left on one if the icons it stays on the icon but to get back to the widgets you have to push right twice (instead of just once).

**Comment by jurialmunkey** [comment]
Ah yep you're right. I've got a couple of navigation changes coming which will allow wraparound of the widgets (e.g. press left from mainmenu will take you to end of widget row), so it will get fixed once I add that.
