### ISSUE TITLE
[Bug] IMDB Top 250 requires to re-focus on a movie

### ISSUE THREAD

**Issue by pchristod** [jurialmunkey/skin.arctic.horizon#350]
Hi,

maybe I very minor Bug I noticed is that it requires always two focus on a movie for the IMDB Top 250 Rating to be displayed on a movie. Steps to reproduce are pretty easy:

1) Focus on a movie you know is in the Top 250 (e.g. Lord of the Rings, Inception etc.)
2) Top 250 Rating (# xxx) will not show
3) Go to the next/previous movie and back again
4) Rating will be shown

Please let me know if anything needs to be provided additionally. Or if anything is unclear.

**Comment by jurialmunkey** [comment]
TMDbH issue - should be fixed with v4.2.19 of TMDbH
