### ISSUE TITLE
when I stop a show or movie Kodi crashes

### ISSUE THREAD

**Issue by nammminn2** [jurialmunkey/skin.arctic.horizon#356]
here is the log https://paste.kodi.tv/nodequnafa.kodi

**Comment by jurialmunkey** [comment]
Hi can you test latest version from the Matrix branch and see if that fixes your issue?

@pkscout - I think this might be the same issue you were having with Netflix. Can you test and see if it fixes for you? It worked to fix the Netflix crash I was having.

**Comment by pkscout** [comment]
@jurialmunkey, unfortunately, this did not fix my crash (with Netflix or Disney+).  I'll open a separate issue.

**Comment by nammminn2** [comment]
it still crashes when I stop a show with Netflix add-on but its fine with other add-ons im on a Mac

**Comment by nammminn2** [comment]
> Hi can you test latest version from the Matrix branch and see if that fixes your issue?
> 
> @pkscout - I think this might be the same issue you were having with Netflix. Can you test and see if it fixes for you? It worked to fix the Netflix crash I was having.

it still crashes when I stop a show with Netflix add-on but its fine with other add-ons im on a Mac

**Comment by Nuklear92** [comment]
> > Hi can you test latest version from the Matrix branch and see if that fixes your issue?
> 
> > 
> 
> > @pkscout - I think this might be the same issue you were having with Netflix. Can you test and see if it fixes for you? It worked to fix the Netflix crash I was having.
> 
> 
> 
> it still crashes when I stop a show with Netflix add-on but its fine with other add-ons im on a Mac

+1 on this comment, I'm also noticing and having the same exact issue with Netflix add-on. When I stop a show or movie it Kodi crashes.

**Comment by jurialmunkey** [comment]
Are you also on osx/mac?

**Comment by pkscout** [comment]
It might not matter. Someone commented on issue I opened that they are seeing the same thing on Windows.

https://github.com/jurialmunkey/skin.arctic.horizon/issues/358

**Comment by Nuklear92** [comment]
I'm on Android TV, Nvidia Shield.

**Comment by jurialmunkey** [comment]
Discussion continued in https://github.com/jurialmunkey/skin.arctic.horizon/issues/358

Closing this one since I'm fairly confident they are the same issue.

**Comment by nammminn2** [comment]
> Discussion continued in https://github.com/jurialmunkey/skin.arctic.horizon/issues/358
> 
> 
> 
> Closing this one since I'm fairly confident they are the same issue.

Okay thank I saw a link to fix it will update it when I wake up ☺️
