### ISSUE TITLE
[BUG][MATRIX] Black screen after startup video plays

### ISSUE THREAD

**Issue by Fatal-Errol** [jurialmunkey/skin.arctic.horizon#357]
Right after the startup video plays, the screen goes black until I press the back button as if there is a black page blocking the home screen. On my android 9 tv, this is consistent no matter what video I add. It's not consistent in windows 10.

**Comment by Fatal-Errol** [comment]
Just learned about your skin debug switch. I turned that on and saw that in Windows, the screen loops through id 9002 <-> 9001 whereas my TV is stuck on 9000.

I have fixed this by increasing the delay of the AlarmClock from 1 second to 5 seconds in Custom_1113_Autoplaylist.xml.

```
<onfocus>AlarmClock(tryagain,SetFocus(9002),00:05,silent)</onfocus>
```

My guess is that it took more than 1 second to initialize the player so the loop checks didn't kicked in. Not sure if it will only fix my setup or my solution is just covering the root cause. Either way, let me know if I'm on the right track and I can send you the PR.

Thanks!

**Comment by jurialmunkey** [comment]
Good detective work! 

Interesting that the loop is not kicking in. Do you have some type of mouse/pointer device enabled? That's the only thing I can think of - that the pointer refocuses when the video playback starts and so kicks you out of the loop.

Adding a 5 second delay could be a bit of an issue as some startup videos might be shorter (e.g. only a couple of seconds). I've got an idea of a different approach that I'm going to try out.

**Comment by jurialmunkey** [comment]
Can you try latest git version? I think I've got a simpler approach for startup playlist which should work.

**Comment by Fatal-Errol** [comment]
Hi @jurialmunkey, the update works, no more black screen. I can see the arctic horizon splash for a brief moment before seeing the custom video but I think that is intended. Thanks!
