### ISSUE TITLE
[MATRIX] Skin Variables throwing JSON decode error after installing Arctic Horizon

### ISSUE THREAD

**Issue by meesterexx** [jurialmunkey/skin.arctic.horizon#359]
Noticed on my test build after installing Arctic Horizon that I kept getting errors on screen from Skin Variables. So I did a test install in a new clean Kodi 19 and got error immediately on install. (Win10 20H2, 64 bit on VM, Arctic Horizon 0.5.6.1, Skin Variables 0.0.3):

Error Type: <class 'json.decoder.JSONDecodeError'>
Error Contents: Expecting value: line 1 column 1 (char 0)

The error appears even on Kodi startup. Full log attached.
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6044602/kodi.log)

**Comment by Soulplayer** [comment]
I’m having the same problems.

**Comment by DFDC** [comment]
Thirded, my log looks the same.

**Comment by jurialmunkey** [comment]
Outdated version of skin variables. You have `0.0.3` installed. Latest version for Matrix is `0.2.5`

**Comment by drinfernoo** [comment]
This same issue is occuring with Skin Variables 0.2.5.

**Comment by jurialmunkey** [comment]
@drinfernoo - Did you mean to reply on the other issue and not this one? Because this piece of code doesn't even exist in 0.2.5 so it isn't possible for this same error to occur.

**Comment by drinfernoo** [comment]
It seems this is also related: https://github.com/jurialmunkey/skin.arctic.horizon/issues/358#issuecomment-786947068

Updating Skin Variables solved both issues for me.

**Comment by DFDC** [comment]
That seems to be the case here, too. The latest version wasn't pulled from your repository.

But now that I've installed it I'm getting a popup that says that Skin Variables is not compatible with this version of Kodi. Running on a Shield TV on Kodi from the Play Store. Gonna try a reboot and will turn on logging.

**Comment by DFDC** [comment]
Log attached with mentioned behavior. Also want to note that if I go into the Arctic Horizon Dependencies setting it shows that it will upgrade from your 0.2.5 to the official repo's 0.0.3.

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6053409/kodi.log)

**Comment by jurialmunkey** [comment]
@DFDC - You need to enable updates from Any Repository in Kodi Settings

`System Settings > Addons > Update official add-ons from > Any repositories`

![Screenshot 2021-02-27 103814](https://user-images.githubusercontent.com/4618719/109366843-9277c280-78e8-11eb-8667-a8f250b1c26f.jpg)

**Comment by Soulplayer** [comment]
I enabled this setting but after a restart it keeps downloading the latest version from the official repo. This then causes the pop-up that the addons are not compatible with Kodi 19...

**Comment by jurialmunkey** [comment]
I think whatever version you downloaded originally, it will keep downloading from that source -- so you need to specifically go and download the version from my repo.

**Comment by Soulplayer** [comment]
I did that. It still keeps downloading from the official repo. 

Second bug: after installing the latest version, disabling auto update and rebooting. Kodi tells me the addon is nog compatible with Kodi matrix and disables it. 

Verstuurd vanaf mijn iPhone

**Comment by jurialmunkey** [comment]
These issues aren't skin related. These are Kodi setup issues.

**Comment by rj-d2** [comment]
sorry to reopen this,
i have the same problem on my shield tv, (working fine on ubuntu)

everything works great with skin variables 0.2.5 installed from repo, 
but after kodi restarts it says skin variables is incompatible with kodi and disables it,
which leaves me with skin variables 0.0.3

addon updates from "ANY Repo is enabled"

edit:
after installing skin variables 0.2.5 from github [https://github.com/jurialmunkey/script.skinvariables](url) it fixt itself,

**Comment by DFDC** [comment]
I had to uninstall the skin, installed skinvariables from your repository, and after a reboot the log shows that 0.2.5 is not compatible with 19.0 and shows that the official 0.0.3 is an upgrade to your version.

My settings are as you listed.

![image](https://user-images.githubusercontent.com/16169356/109397868-b0502200-78fe-11eb-8e65-4da1c2f678e8.png)

**Comment by DFDC** [comment]
> edit:
> after installing skin variables 0.2.5 from github [https://github.com/jurialmunkey/script.skinvariables](url) it fixt itself,

That does work to resolve the issue but it's because manually installed addons do not follow update channels so you won't get future updates.

**Comment by Soulplayer** [comment]
This also fixed it for me. The 0.2.5 version from the repo gives a Kodi error (not supported) but the 0.2.5 version from GitHub is okay. 

Verstuurd vanaf mijn iPhone

**Comment by Verequies** [comment]
I was able to fix this by uninstalling AH and Skin Variables, then deleting everything in my Kodi profile directory '/addons/packages/'. After which installing the two addons from the repo yielded no issues. It seems it was a cache issue caused when upgrading to Matrix.

**Comment by Soulplayer** [comment]
Perhaps a bit later. I’m not looking forward to redo my entire setup again for the menu’s and so forth. 

Verstuurd vanaf mijn iPhone

**Comment by Verequies** [comment]
No need to do that, saved settings aren't removed if you select to keep the settings during the uninstall process.

**Comment by Verequies** [comment]
Found a faster method. No need to uninstall anything now and Kodi can still be running. I have copied it here from the AH Kodi forum thread [here](https://forum.kodi.tv/showthread.php?tid=351756&pid=3019526#pid3019526).

- Delete any **script.skinvariables-nnn.zip** in **profile directory > addons > packages** 
- If Kodi is not running, start Kodi
- Install **Skin Variables** addon (currently v0.2.5) from **jurialmunkey's Alpha Repository**
  - You can ignore the message about it not being able to be uninstalled due to Arctic Horizon being enabled.
- Continue on as normal, no need to restart Kodi, but you can if you want to confirm that it works

**Comment by drinfernoo** [comment]
@Verequies Correct. Manually installing from @jurialmunkey's repository should fix it. This issue *is* closed, you know 😅

**Comment by Verequies** [comment]
@drinfernoo Yeah it should, but for some reason it reverts back to the one in the Kodi repo after upgrading to Matrix - has happened to every one of my setups ( more than 6 devices). I was just providing a fix here so people don't have to go reinstall everything, regardless of whether the issue was closed or not.

**Comment by drinfernoo** [comment]
@Verequies The workaround you've added is to... install it from his repo 😅

**Comment by Verequies** [comment]
@drinfernoo after deleting the cached items yes. Otherwise after upgrading to Matrix - at least for myself, a couple of people here and others on the AH thread - everytime Kodi restarts it would revert to the Kodi repo version. I would not have replied or commented if it wasn't a valid issue.

**Comment by tbmmbt** [comment]
> @drinfernoo after deleting the cached items yes. Otherwise after upgrading to Matrix - at least for myself, a couple of people here and others on the AH thread - everytime Kodi restarts it would revert to the Kodi repo version. I would not have replied or commented if it wasn't a valid issue.

100% to this and thank you @Verequies. I've spent the last few hours trying to fix this after my matrix update. As you say, I tried to install direct from Jurielmunkey's repo and it fixed it temporarily until I restarted and it kept rolling back to the old original Kodi repo version. I had to delete the cached zip as stated which wasn't the easiest job on a Mi box (thanks Solid Explorer!). Anyway have restarted it a few times now and seems to be finally fixed but @Verequies point is definitely valid for some users including me. Thanks to Jurielmunkey and Drinfernoo for your great work but this seems to definitely be an issue for some of us.

**Comment by drinfernoo** [comment]
By changing the setting to install from "any repositories" **first**, before installing from third-party repositories, you can sidestep the issue entirely, as the "wrong" dependencies will never be installed in the first place, and thus not cached into the `packages` folder.

**Comment by Verequies** [comment]
@drinfernoo yes but that is a new setting in Matrix if I am correct? So that doesn't help people upgrading necessarily. Anyhow I have that setting set and was still seeing the issue.

**Comment by drinfernoo** [comment]
@Verequies That is correct. I'm speaking of fresh installs, which is what is always recommended to handle discrepancies after a "dirty" upgrade.
