### ISSUE TITLE
[Feature Request] Single row sub menu widget

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#36]
Any chance you could a setting to adjust the number of rows a sub menu widget uses (default is 2)
Thanks 👍 
![submenu](https://user-images.githubusercontent.com/5837771/77117033-19f65980-6a29-11ea-8560-18ca88cab443.png)

**Comment by jurialmunkey** [comment]
No because it won't fill the vertical space otherwise and I want all widgets to occupy the same amount of vertical space.

If you have any ideas for what would display in the empty space of the other row, then please let me know.
