### ISSUE TITLE
[BUG] Parent Folder Items not showing anymore on latest v0.5.62

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon#360]
Okay, as you know when you have the "Show Parent Folder Items" option enabled, which is ON by default. You usually get a Back Button Icon when navigating Folders or Lists, and when you're navigating TV Shows with multiple Seasons you usually get a view of all the Poster Artwork for each Seasons together then you get other tabs for quick view of individual Seasons. So, after the last night update which I believe fixes the Kodi crashes when Stoping movies or shows. It now has stopped showing those season poster artworks when you first click on a tv show with multi seasons. I'll leave screenshots and a small video clip showing the issue happening. 

This is happening on all media content add-ons, for the purpose of the recorded clip I used Netflix Addon for example.

![image](https://user-images.githubusercontent.com/76958541/109391084-57bf5b80-78e3-11eb-8479-d90c541c9eac.png)
![image](https://user-images.githubusercontent.com/76958541/109391088-5db53c80-78e3-11eb-8df3-1b236626bc04.png)

**Small video clip showing issue more detailed:**

[Clip](https://imgur.com/a/Rrzw25o)

**Edited:** For reference, I even reinstalled Kodi and the skin from scratch and the issue still happening, matter fact these screenshots and clip are recorded after the reinstall of the skin. So, it's not a Kodi or Skin glitch that needed a quick reset/reinstall to be fixed.

Device: Nvidia Shield Pro 2019
Kodi build: 19.0

**Comment by jurialmunkey** [comment]
It had to be removed because referencing the parent folder in a dynamic container is what causes the playback crash in https://github.com/jurialmunkey/skin.arctic.horizon/issues/358

I'm not sure if the culprit is the Netflix plugin or Kodi itself, but there's nothing I can do about it in the skin. Kodi will start crashing again as soon as I add a container that references the parent folder for content. It is simply impossible to do in Matrix until whatever underlying bug is resolved.

**Comment by Nuklear92** [comment]
> It had to be removed because referencing the parent folder in a dynamic container is what causes the playback crash in https://github.com/jurialmunkey/skin.arctic.horizon/issues/358
> 
> 
> 
> I'm not sure if the culprit is the Netflix plugin or Kodi itself, but there's nothing I can do about it in the skin. Kodi will start crashing again as soon as I add a container that references the parent folder for content. It is simply impossible to do in Matrix until whatever underlying bug is resolved.

Oh, wow. I didn't knew that was one of the cause of the problem. Thanks for the response, I hope it can make it's way back sometime in the future.
