### ISSUE TITLE
BUG - MATRIX - Catch Up TV & More Addon

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon#361]
Running AH 0.5.62 on Kodi19 stable, on Windows 10. When using the Catch Up TV & More addon from the Kodi repo, the addon only displays a blank screen, as per attached screenshot.

![screenshot00003](https://user-images.githubusercontent.com/67786207/109410940-6581e900-7996-11eb-8e11-b393bf98d9df.png)

Log file attached 
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6056373/kodi.log)

When using Estuary, the CUTV addon starts normally.

![screenshot00010](https://user-images.githubusercontent.com/67786207/109423517-9fbfaa80-79d7-11eb-86d0-8019a4dc79ad.png)

Please let me know if you need any further information.

**Comment by alKODIque** [comment]
@berkhornet @jurialmunkey 
I think it was not an issue due to the skin since CodeQuick was updated, I do not have this issue anymore.

**Comment by berkhornet** [comment]
@jurialmunkey. Agrred, I've just update to CodeQuick 1.0.2+matrix.1 and the Catch Up TV & More addon starts correctly. I will close the issue.
