### ISSUE TITLE
[BUG][MATRIX] "Exit" does not work

### ISSUE THREAD

**Issue by tadly** [jurialmunkey/skin.arctic.horizon#363]
Power menu -> Exit doesn't seem to work

From the log:
```
...
Keymapping error: no such action 'xbmc.quit()' defined
...
```

**Comment by jurialmunkey** [comment]
This is a skinshortcuts issue. You need to remove the `xbmc.` part of the command from the action (you can configure power menu in Lists and Other section of skin settings).

Basically the xbmc prefix was removed from all actions in Matrix, so if you migrated from Leia then any shortcuts with this prefix will now not work. If this is a fresh install then worth reporting to whoever maintains skinshortcuts now.

**Comment by tadly** [comment]
I did copy skinshortcuts over so this must be the problem. Thanks didn't think that far :)
