### ISSUE TITLE
[Request] Revert PVR design to old look please

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/skin.arctic.horizon#366]
I know in these images it doesn't look like much difference but u can kinda tell if u zoom in. "Though if u have to zoom in then its not that a big deal," I know. But when im actually inside Kodi in arctic horizon its a lot more noticeable if that makes any sense. Anyways, I really like the PVR image u presented for Arctic Horizon as shown here
https://i.imgur.com/XFyCrcs.jpg

This is what it currently looks like (well last I played with AH)
https://i.imgur.com/c8Quo2D.png

The non rectangular shape just really irks me visually I think it does not look nice at all and the previous version looked much better. It especially feels out of order with how everything else in Arctic Horizon looks so clean and great. Sorry if I am being rude I dont mean to come across like that, but regardless I really hope you consider reverting it to the previous style!

**Comment by jurialmunkey** [comment]
I'm not sure what you're quite referring to here? The rounded corners are in both images - I'm not quite sure what you're claiming has changed.

**Comment by unkn0wn234** [comment]
It's very nitpicky and honestly not as noticeable when I took the screenshot, I haven't used Arctic Horizon in a while though so I cant take more screenshots to compare, I plan on coming back to it when most of my 3rd party addons come to K19 and will use AH in 19. But basically they are both rounded but if u zoom in its a lot more rounded in the screenshot I sent. The corners being more rounded like that just looks really weird/out of place to me compared to the original where it is rounded but it's a very small amount and still looks rectangular a bit. 

I know its an odd request lol but would be much appreciated if you did, if not well I respect your decision regardless.

https://imgur.com/a/DV3IKCA

**Comment by unkn0wn234** [comment]
Oh i do have a question though in the initial screenshots where my screen says TV Channels how did u guys yours to have those icons for search, and back to home, etc?

**Comment by drinfernoo** [comment]
@unkn0wn234 That was an early concept design for the skin that got abandoned before release.

**Comment by jurialmunkey** [comment]
> The corners being more rounded like that just looks really weird/out of place to me compared to the original where it is rounded but it's a very small amount and still looks rectangular a bit.

Ah, yes the rounding on corners in the released version was slightly increased to 8px from earlier versions (which from memory I think were either 5px or 6px rounding). However, this is a consistent rounding value across all the textures in the skin, so it won't be changed back to 5px in one specific spot as then the skin won't be consistent anymore. You could do a textures mod and modify all the textures to have a 5px rounding but it isn't something that I will do myself.

**Comment by unkn0wn234** [comment]
> > The corners being more rounded like that just looks really weird/out of place to me compared to the original where it is rounded but it's a very small amount and still looks rectangular a bit.
> 
> Ah, yes the rounding on corners in the released version was slightly increased to 8px from earlier versions (which from memory I think were either 5px or 6px rounding). However, this is a consistent rounding value across all the textures in the skin, so it won't be changed back to 5px in one specific spot as then the skin won't be consistent anymore. You could do a textures mod and modify all the textures to have a 5px rounding but it isn't something that I will do myself.

Ah I see thanks doc and jurial for explaining. I do have a question though, so regarding the 5px thing would I just change one value somewhere and it affects everything else? Or would I have to change it in multiple places? And in the second case does that mean I can just change the rounding value for the PVR section alone without affecting the rest? Bc I wouldn’t mind it not being consistent with the rest of the skin.

**Comment by jurialmunkey** [comment]
> I do have a question though, so regarding the 5px thing would I just change one value somewhere and it affects everything else? Or would I have to change it in multiple places? 

Nope. I wish it were that simple. You need to create new texture png images with the desired rounding on the corners.

Most parts of the skin use this rounded png texture as the base:
https://raw.githubusercontent.com/jurialmunkey/skin.arctic.horizon/matrix/media/common/box.png

And this texture as the selection gradient overlay:
https://github.com/jurialmunkey/skin.arctic.horizon/blob/matrix/media/common/box-gradient-vertical.png

(FYI - Those images are white and use transparency so in web browser they will look like a white square due to white background - Need to open them in an image editor to see how they work properly).

>  And in the second case does that mean I can just change the rounding value for the PVR section alone without affecting the rest? 

Nope because the skin shares textures across multiple windows. If you wanted to change it in only one place you'd need to create separate textures and then modify the xml for the PVR windows to use those textures instead.
