### ISSUE TITLE
Kodi Crashes When Using Predictive Search

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/skin.arctic.horizon#367]
Kodi crashes everytime I select something from the predictive search option when searching within an add-on.

My setup

Clean reset Nvidia Shield 2017 Pro
Clean Kodi 19 stable install

Add-on being used is iPlayer beta

https://github.com/vonH/plugin.video.iplayerwww/archive/4.0.0beta2.zip

Steps to reproduce

Setup add-on to be listed in the main home screen menu. (I'm using s vertical layout)

Use the submenu option to create a IPlayer Search option

Select the submenu search option from the iPlayer home screen icon

Keyboard pops up

Start to type

Select any predictive result that is displayed

When this is selected, Kodi crashes

Selecting 'Done' without using the predictive option works ok

**Comment by jurialmunkey** [comment]
Not a skin issue. That's an issue with `plugin.program.autocompletion`
https://github.com/sualfred/plugin.program.autocompletion

**Comment by drinfernoo** [comment]
There is a working version here: https://github.com/DaedalusBLN/plugin.program.autocompletion

**Comment by ghost** [comment]
> There is a working version here: https://github.com/DaedalusBLN/plugin.program.autocompletion

Thanks!! 😊, getting an install error using code downloaded as a zip. Should I be doing something with the zip before attempting an install.

Thanks for helping out.

**Comment by drinfernoo** [comment]
@spidasingh I hadn't realized that version isn't compatible with Matrix... But it does work in Leia 😅
