### ISSUE TITLE
Bug: Play Button In Full Screen Information Window Doesn't Work

### ISSUE THREAD

**Issue by jhs39** [jurialmunkey/skin.arctic.horizon#369]
One of the available options as the default action when clicking on a video item is to open the full-screen information window instead of automatically playing the video.  The same information window can also be accessed from the context menu.  Videos cannot be played using the Play Button that's inside the information window.  Clicking the Play Button always yields a Playback Failed pop-up message.  Directly playing the video as the default action or backing out of the information window and then selecting Play in the context menu both work properly and play the same videos with no problems.

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by Blurayx** [comment]
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6096651/kodi.log)

**Comment by jhs39** [comment]
Not being as computer proficient as I should be I will look for instructions for creating a debug log in Kodi (I'm using the Matrix version on Nvidia Shield TV Pro (2019)).  Is there any way built into your skin to generate a debug log and update it to you or do I need to create the debug log and then get it to my computer so I can upload it through Github?  I'm sure that's a noob question but, as I said, even though I have been using computers since the 1980's I have never done any programming or coding and my technical knowledge is limited.

**Comment by jhs39** [comment]
I needed to look up instructions for how to create a debug log in Kodi.  I think I've found them so I will create a log and upload it through GitHub as soon as I have it.  Thanks.

**Comment by jhs39** [comment]
Here is the address for the logfile:

https://paste.kodi.tv/emotasagok

**Comment by jurialmunkey** [comment]
Here's your issue:
`plugin.video.themoviedb.helper v2.4.36 installed`

That's a very old version of TMDbH. Minimum required version for the skin is 4.2.3
https://github.com/jurialmunkey/skin.arctic.horizon/blob/matrix/addon.xml#L7

Install latest version of TMDbH from my repo or github.

**Comment by jurialmunkey** [comment]
See discussion from here as to why you were able to install the skin despite not meeting dependency version:
https://github.com/jurialmunkey/skin.arctic.horizon/issues/359#issuecomment-786987739

This Kodi bug allowing installs without meeting version requirements will be fixed in a future Kodi update so that it is no longer possible.

**Comment by jhs39** [comment]
That's strange.  I show my version of TMDbH as version 4.2.23 from jurialmunkey.  Did this get updated somehow?  I installed a new version of your skin today from the zip file--would that have updated the plug-in or would it have auto-updated since I have your repository installed?
