### ISSUE TITLE
Vertical Scrollbars

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#37]
In list views (like root add-on menus), it's often nice to have a vertical scrollbar... but AH doesn't seem to. Is this by design, or an oversight?

**Comment by jurialmunkey** [comment]
Yeah oversight. I noticed the other day that it needed to be added.

**Comment by jurialmunkey** [comment]
Okay fixed now for lists. Thanks for the prompt as I would have forgot to fix it again otherwise!

---
Relevant Commit: 
https://github.com/jurialmunkey/skin.arctic.horizon/commit/ccd287832179388ccc44fc98f8f010b3810d48c9
