### ISSUE TITLE
[Question] Matrix-series Return/End

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#370]
Series Return/End missing. Is there a setting I need to enable in the matrix or a bug?

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6096654/kodi.log)

<img width="1666" alt="Screenshot 2021-03-07 at 05 55 19" src="https://user-images.githubusercontent.com/2873112/110230872-e186ae80-7f0b-11eb-8641-6299a5fe5858.png">

Thanks

**Comment by jurialmunkey** [comment]
Working for me.

Make sure you have use online information enabled in ratings
`Skin Settings > Interface > Additional Ratings > Use online information`

**Comment by Blurayx** [comment]
Ah, working now. is it normally turn off by default because I've never needed to enable it with a fresh install?
Thank you

**Comment by jurialmunkey** [comment]
> is it normally turn off by default because I've never needed to enable it with a fresh install?

Originally it was on by default but it has been off by default for quite some time. On a fresh install, you should get a prompt for the skin setup wizard which asks if you want to turn online ratings on. I should probably change the text slightly to read `Online ratings and additional info` to make it a bit clearer that it isn't only ratings.

![Honeyview_screenshot00017](https://user-images.githubusercontent.com/4618719/110241267-fa42a300-7fa3-11eb-9a36-3eba5da3c5e5.jpg)

**Comment by Blurayx** [comment]
Thanks for letting me know 😀
