### ISSUE TITLE
[BUG] Versions button does not work

### ISSUE THREAD

**Issue by peat80** [jurialmunkey/skin.arctic.horizon#371]
Long pressing "ok" on an addon > then choose "infoC > then choose" versions" it should open a window which shows available versions from installed repos to choose. Works on Estuary, on Arctic Horizon it just throws one to the addonmanager.

**Comment by jurialmunkey** [comment]
Oops missed that button ID change. Should be fixed now.

**Comment by peat80** [comment]
Works fine now. Thank you. 😀👍
