### ISSUE TITLE
Skin Variables Error

### ISSUE THREAD

**Issue by Nadonate** [jurialmunkey/skin.arctic.horizon#374]
Hi,
I'm getting a "skin variables error, please see log" error on a fresh matrix install.

**OS** - Ubuntu 20
**Kodi** - Matrix 19

[kodi.log](https://drive.google.com/file/d/1oA6X1hP0lFUiAhhGw38mrOZ6oHYUbOtI/view?usp=sharing)

Troubleshooting steps I've tried:

- Reinstall skinvariables 
- Resintall ArcticHorizon

**Comment by jurialmunkey** [comment]
Old version of skin variables installed v0.0.3 when skin requires at least v0.2.3

Duplicate of #359 
See this comment and further for solutions: https://github.com/jurialmunkey/skin.arctic.horizon/issues/359#issuecomment-786987739
