### ISSUE TITLE
[Req] Icon/Poster view for media

### ISSUE THREAD

**Issue by jhs39** [jurialmunkey/skin.arctic.horizon#378]
I wanted to request an additional icon/poster grid view that would allow media to be viewed as rows and columns of posters that could be scrolled vertically.  This would make it much easier to quickly scroll through large media libraries while maintaining visual appeal.  I have come across this type of view in a couple of different places but it doesn't seem to be available as one of the available choices in the vast majority of the skin unless I'm missing the setting that adds this to the list of views that are available by default. The two-row poster view is what I'm currently using but since I have a large library scrolling through items is very time consuming.

**Comment by jurialmunkey** [comment]
Use the single row poster and enable wall replaces scrollbar in skin settings. Pressing down from the single row will now open a wall view to scroll through items. 

With the exception of list, all standard views are horizontal in line with the name "Horizon"

**Comment by jhs39** [comment]
Thanks.
