### ISSUE TITLE
[Bug?] Actor information

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#383]
info for TV & Movies not working correctly 

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6135172/kodi.log)

Matrix

https://user-images.githubusercontent.com/2873112/111038021-b675f080-841e-11eb-8b09-b0f40c586f52.mp4

Thanks

**Comment by drinfernoo** [comment]
What's not working?

**Comment by Blurayx** [comment]
The actor information

**Comment by jurialmunkey** [comment]
You need to turn on online info for the info dialog lists in skin settings under lists and other.

Note that there are two "use online info" toggles in skin settings - one in the dialog where you enable ratings and one in the dialog where you enable info lists.

**Comment by Blurayx** [comment]
working now. Thanks😀
