### ISSUE TITLE
[Bug] No Context Menu on Episodes

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#39]
It doesn't appear that I'm able to pull up a context menu on episodes inside TMDbHelper (or other places), unless I'm using "Browse" as the default action.

**Comment by drinfernoo** [comment]
In the combined seasons/episodes view, if that wasn't clear :+1:

**Comment by jurialmunkey** [comment]
It's a Kodi limitation. Context menu doesn't work for dynamic content (i.e. widget lists) inside the library. It's really annoying - but at least we have context menu for widgets outside of the library (prior to Krypton you couldn't have context menus for widgets even).

**Comment by drinfernoo** [comment]
I figured out the "workaround" isnto just enter the season 👍
