### ISSUE TITLE
[Request] Display ratings on homescreen with widgets

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon#392]
![Inkednameratings_LI](https://user-images.githubusercontent.com/76912707/111881741-df136280-89a9-11eb-82e5-cd3f4a643135.jpg)

Would it be possible to display ratings on the homescreen? (I have circled where i would like the ratings to be in the picture I uploaded). I'd imagine this wouldn't be too difficult for you to implement and would make a big difference. 
 
Thanks a lot for your time and work

**Comment by kodiultimate** [comment]
This option is already there

**Comment by drinfernoo** [comment]
@kodiultimate I don't believe so...

**Comment by kodiultimate** [comment]
> @kodiultimate I don't believe so...

Ok, I had a look now and ratings are there but only when 'Display Info' is set to True on each widget, but that will come with whole movie description, thumbnail and ratings.

![screenshot00000l](https://user-images.githubusercontent.com/32402420/112433677-7d9d1c00-8d3a-11eb-8cc9-401a6e8e6fcc.png)

**Comment by rizreflects** [comment]
@kodiultimate Cheers for looking that up, althought I was already aware of this.  I was talking about adding ratings without setting show info to true.

**Comment by unkn0wn234** [comment]
> @kodiultimate Cheers for looking that up, althought I was already aware of this. I was talking about adding ratings without setting show info to true.

This might be possible w some edits but not sure how you'd go about doing it, I could give it a shot as I did edit that Widget Line to include Title and Tagline myself thanks to jurials help

**Comment by rizreflects** [comment]
> > @kodiultimate Cheers for looking that up, althought I was already aware of this. I was talking about adding ratings without setting show info to true.
> 
> This might be possible w some edits but not sure how you'd go about doing it, I could give it a shot as I did edit that Widget Line to include Title and Tagline myself thanks to jurials help

If you could do that I'd be extremely grateful. It's the only thing missing for me atm.

**Comment by jurialmunkey** [comment]
FYI I've thought about this request and I'm not going to add this feature to the skin because the length of the movie title will cause the position of the ratings to shift around. Having elements change their position on screen constantly is poor ui design and is fatiguing on the eyes.
