### ISSUE TITLE
[Minor Bug] icons missing

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#394]
icons missing when creating home widgets.
<img width="1368" alt="2" src="https://user-images.githubusercontent.com/2873112/112142647-c2a43f80-8bce-11eb-95a8-a7b50a7bc9a9.png">

icons are still generated on the home screen
<img width="1502" alt="Screenshot 2021-03-23 at 11 44 07" src="https://user-images.githubusercontent.com/2873112/112141882-d13e2700-8bcd-11eb-8877-c4f2535ca4bf.png">

No issues adding the icons manualy
<img width="1368" alt="Screenshot 2021-03-23 at 11 52 58" src="https://user-images.githubusercontent.com/2873112/112142380-6c370100-8bce-11eb-90a8-38b238d9a5cf.png">

Thanks

**Comment by jurialmunkey** [comment]
Skinshortcuts issue - not much can be done about it from the skin side of things.
