### ISSUE TITLE
Minor_Bug_Missing_Icons&Posters/Images

### ISSUE THREAD

**Issue by d4g79** [jurialmunkey/skin.arctic.horizon#397]
There are some minor image issues i have found in Matrix version of Horizon. See below the before Matrix in Lei and after Matrix.

Lei Skin Images Horizon.

https://www.dropbox.com/s/83vnyjejr5yrfej/IMG_2622.jpg?dl=0
https://www.dropbox.com/s/4oi5odvcsjtnqaq/IMG_2621.jpg?dl=0

After Matrix Skin Images Horizon

https://www.dropbox.com/s/lybieh6eqpjr265/IMG_2618.jpg?dl=0
https://www.dropbox.com/s/wnhyw40wt2grlxb/IMG_2619.jpg?dl=0
https://www.dropbox.com/s/q8fezyofjax7d9k/IMG_2620.jpg?dl=0

Thanks in advance.

**Comment by jurialmunkey** [comment]
Your first and last matrix images are issues with the skinshortcuts addon.

The middle one is a removed feature due to causing a crash in matrix and isn't possible to reintroduce. The only "solution" is to disable parent folder items in kodi settings so that the ".." item isn't displayed.
