### ISSUE TITLE
[Bug?] Artwork Dump options menu

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#403]
Not sure if it's a skin or add-on issue. Artwork Dump randomly disappear from the options menu
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6252019/kodi.log)
[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6252020/kodi.old.log)

![Screenshot 2021-04-03 at 06 38 47](https://user-images.githubusercontent.com/2873112/113469876-ff7efa80-9448-11eb-884b-c8f91afc721e.jpeg)

Thanks

**Comment by jurialmunkey** [comment]
I don't think I ever had an option for artwork dump there. Is it even something that requires skin integration?

**Comment by Blurayx** [comment]
It was there before. I was using it to download artwork to my folders. It worked like Artwork Beef.

**Comment by jurialmunkey** [comment]
I've never had support for Artwork Dump. I even went and checked my commit history just to make double sure and there is no mention of it ever. I'd never even heard of that addon until you had mentioned it, and I definitely never added support for it.

Are you sure you aren't getting confused with Artwork _Beef_ and just misremembering Artwork _Dump_ options being there? There are options for Artwork _Beef_ in that menu which only display if you have Artwork Beef installed, so if you recently uninstalled/disabled Artwork Beef then you would no longer see those options (they only work with Artwork Beef anyway though).

EDIT: Also, I just checked Artwork Dump and it doesn't provide any skin integration options, so it isn't possible to include an option in the skin. So closing this issue as it was never in the skin and isn't possible to include.

**Comment by jurialmunkey** [comment]
The screenshot below shows a git log search where you can see that I've never had any mention of artwork dump in the skin. The first search finds two commits mentioning "script.artwork.beef" whereas the second search shows that there are no commits mentioning "script.artwork.dump". If I had ever had included artwork dump then it would show in the commit log.

![image](https://user-images.githubusercontent.com/4618719/114295597-96068800-9ae9-11eb-9b87-c80ae6f98942.png)
