### ISSUE TITLE
[INFO] show search button in home screen  main menu

### ISSUE THREAD

**Issue by fatshotty** [jurialmunkey/skin.arctic.horizon#408]
Hello,
is it possibile to show search button in home page main menu as per ArcticZephir2?
Attach screenshot for more explaining details
<img width="1091" alt="Análisis_a_Fondo___Skin_ARCTIC_ZEPHYR_2_-_YouTube_🔊" src="https://user-images.githubusercontent.com/238659/114375873-69a04980-9b85-11eb-84da-04c590e756c2.png">

**Comment by jurialmunkey** [comment]
You can customise the home menu in skin settings.
