### ISSUE TITLE
Context menu library not opening

### ISSUE THREAD

**Issue by justinkruit** [jurialmunkey/skin.arctic.horizon#411]
Whenever I hold a show episode in my library, I don't get a context menu. Items have been created using TMDB Helper, but my movies work fine. It also works fine in the default theme.

This probably goes together with the fact that shows without seasons it works, and that I also don't see a list of seasons when I open a show. The ".." tab is empty, while I remember it being filled with the seasons.

Log: https://paste.kodi.tv/ahazilimig

**Comment by drinfernoo** [comment]
You have to enter into the season first. When using the combined season/episode view, context menus won't open, due to a limitation on the skin engine.

**Comment by justinkruit** [comment]
Ahhh, thank you @drinfernoo . I didn't know that was technically a different view.

Thanks to this tip, I also just found out that this view causes webdav files to not play, which I originally reported in #406
