### ISSUE TITLE
[Maybe BUG] Allow "Play Using" in widgets

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#415]
(Sorry not tested on another skin)

I have external player VLC enabled in userdata/playercorefactory.xml. I use VLC for watching +50GB files.

When I'm in addons or in TmdbPlayer I have "Play Using" in the context menu.  But this remains absent in widgets.

Is there a toggle in the skin for that which you can flip ?

**Comment by derrgoo** [comment]
This is something I have wondered about as well. But no skins have this added. Can only use it in a list form that I have seen. Would be cool to add.

**Comment by jurialmunkey** [comment]
Skins don't control the items in the context menu - the skin only defines how it looks not what's in it. Kodi determines what items display.
