### ISSUE TITLE
kodi crash

### ISSUE THREAD

**Issue by shahaf1122** [jurialmunkey/skin.arctic.horizon#417]
HI,
kodi keep crashing using FEN.
what I tried:
I did a clean install of kodi.
I install the skin.arctic.horizon and i remove all the widgets and shortcut from home screen.
I just go to to tv series and play a episode and when i press stop the kodi say busy and crash.
I checked with other addons like shadow and seren and they nor crashing...

**Comment by jurialmunkey** [comment]
Sounds like an issue with the addon not the skin.
