### ISSUE TITLE
[Feature] Up Next support.

### ISSUE THREAD

**Issue by termnl0** [jurialmunkey/skin.arctic.horizon#42]
Would it be possible to add support to Up Next add-on? You know, to match the theme of the skin.

Great skin, btw.

**Comment by jurialmunkey** [comment]
I was literally working on this right now just before I saw this comment!

It's been added in v0.1.31

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/d0c94fa3337f8bfd8bfdd7e5654a264f4a6ecabe
