### ISSUE TITLE
Numeric star rating setting missing in Matrix version

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon#421]
Hi jurialmunkey,

First of all I really appreciate the great work that you're doing and would like to thank you for the same. I'd like to inform you that the numeric star rating setting that was earlier available in the Arctic Horizon Leia version is no longer present in the Matrix version. Hence, my request is that if you could add back the same. Thanks in advance!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Yes it is there.
`Skin Settings > Interface > Additional Ratings > Prefer numeric star rating`

![screenshot00089](https://user-images.githubusercontent.com/4618719/141039090-277e44b2-dd72-4c88-ade6-25ac47881808.png)

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you so much! Found it.

Thanks and Regards,
ShibajiCh.
