### ISSUE TITLE
Posters cutoff in 21:9 

### ISSUE THREAD

**Issue by MatthewJPretty** [jurialmunkey/skin.arctic.horizon#425]
Posters cutoff in 21:9

![kodi_2021-07-09_00-50-22](https://user-images.githubusercontent.com/30120884/125003938-4421bf80-e050-11eb-9cd1-8173c5ce9640.jpg)

**Comment by drinfernoo** [comment]
Most everything is a bit funky outside of 16:9 😅

**Comment by jurialmunkey** [comment]
Skin only supports 16:9 sorry.
