### ISSUE TITLE
Content type and available view types

### ISSUE THREAD

**Issue by 123Venom** [jurialmunkey/skin.arctic.horizon#427]
When our listItems are `folders` addons are setting the content type to either `addons` or `files`.  All skins seems to handle these a bit different but I'm leaning towards `files` being the preferred content type set to by the addon.  Problem came in that AH only allows `landscape` view of these listItems and therefore the addons setting of icon, poster, or thumb is not used.  Is it possible to add a `poster` view type when the content type is set to `files` by an addon?  In AH it honestly looks better if the addon sets the content type to `addons`, because more view types become available...but...then Estuary has it's set of hiccups using `addons` as a content type.

**Comment by drinfernoo** [comment]
Using `videos` (I think) provides the most options, but it might be `movies`, `tvshows` or even `episodes`, I can't remember.

**Comment by 123Venom** [comment]
Interesting idea and not seen an addon set the content type to `videos` when they're folder items.  I decided to test it.  We get `Landscape Row`, `Landscape Wall`, and `Landscape List`. ya I don't think an addon setting content type to `videos` for folders is a good idea there lol...still all landscape only artwork used.  All addons I've reviewed are either using `addons` or `files` for folder type items.  I'm still back to thinking AH would be nice to add another view type when content is set to `files` so the addon poster/thumb could be shown vs. landscape.

**Comment by jurialmunkey** [comment]
Why set any content type at all for folders?

Navigation folders are not addons or files or videos...

**Comment by drinfernoo** [comment]
@jurialmunkey What view types are available if no content type is set?

**Comment by jurialmunkey** [comment]
> @jurialmunkey What view types are available if no content type is set?

Square list and Tags. But that's an intentional design choice I made in the skin.

Addons should set the correct content type as per the content, not as a hack to attempt to trick skins into providing certain viewtypes. If there's a viewtype that someone thinks should be available for a certain content type, then that should be discussed with the skin author and requested to be added to the skin.

**Comment by 123Venom** [comment]
> 
> 
> Why set any content type at all for folders?
> 
> Navigation folders are not addons or files or videos...

Seems setting content to `''` is far better @jurialmunkey, thank you for pointing this out.  TBH TMMDb Helper is about the only addon I found doing this...most set it and apparently chose wrong...lol.  Even Estuary now allow addons to show icons they set but ignore it if content type is set. Very nice!!!  appreciate it.
