### ISSUE TITLE
TMDBHelper people search 

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon#434]
I have the DefaultSearch-TMDBPeople set in AH search list and when I search an actor it pulls up a list of actors like it is supposed to but when I click on the actor, I get the popup with "Cast in movies, Cast in TV shows, Crew in movies, Crew in TV shows, Images" but when I select one of the options, nothing happens. When I go in TMDBhelper and search it works properly. Am I doing something wrong? Is there a fix for this?

**Comment by derrgoo** [comment]
This is for arctic horizon you may want to post tmdb on its own. Yes he is the author of both but maybe you might get a response.

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/557
