### ISSUE TITLE
Context menu from landscape.integrated viewtype

### ISSUE THREAD

**Issue by celiofk** [jurialmunkey/skin.arctic.horizon#436]
Hi,
I have a widget for TMDBH TV series Trakt collection.
When I choose one item to show, it opens a window in landscape.integrated viewtype with season buttons and a list of episodes. If I call context menu for an episode, nothing happens. Is this the default behavior?
Changing viewtype to another one available and context menu comes out.

**Comment by jurialmunkey** [comment]
It's a kodi limitation. Nothing can be done about it.

If you search the closed issues you can see it's been covered multiple times before
https://github.com/jurialmunkey/skin.arctic.horizon/issues?q=is%3Aissue+is%3Aclosed+context

https://github.com/jurialmunkey/skin.arctic.horizon/issues/39 https://github.com/jurialmunkey/skin.arctic.horizon/issues/228 https://github.com/jurialmunkey/skin.arctic.horizon/issues/300 https://github.com/jurialmunkey/skin.arctic.horizon/issues/411

**Comment by celiofk** [comment]
Thanks and sorry for not searching properly.
