### ISSUE TITLE
[Bug] UpNext script

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#44]
![Screenshot_20200322-005548](https://user-images.githubusercontent.com/58227846/77239322-db53d100-6bd9-11ea-9fde-5acd286993c0.png)
Hi @jurialmunkey my system language is spanish, maybe is the reason i can't see that but seems $LOCALIZE[31227] don't work for me, in AZ2 you have "upnext strings" in the label of "Object_Info_Title". Why you don't use it here?

**Comment by jurialmunkey** [comment]
Because the up next strings force the highlight colour to be pink. I need to be able to edit it to match the actual highlight colour in the skin.

Have you added a translation strings.po to the skin? You're probably missing that string from your localization.

**Comment by taoxtrece** [comment]
Not for now but can made it if you need it

**Comment by jurialmunkey** [comment]
Well it works fine for me if I switch to Spanish

![Honeyview_screenshot651](https://user-images.githubusercontent.com/4618719/77240004-19caa980-6c35-11ea-8511-f21755a70008.jpg)

**Comment by drinfernoo** [comment]
@jurialmunkey As mentioned in the AZ2 forum thread, it appears that localization in the test dialog is somehow different than the actual dialog in use: https://forum.kodi.tv/showthread.php?tid=339791&pid=2932521#pid2932521

I don't know that that's what's happening here, but I thought I'd point it out.

**Comment by taoxtrece** [comment]
Yep can be the reason with plus ten versions installed from the version 0.1.9 lol tomorrow i try with a clean setup

@drinfernoo in the last thread i sent the correct files to @jurialmunkey  ;)

**Comment by jurialmunkey** [comment]
Still works when playing:

![Honeyview_screenshot653](https://user-images.githubusercontent.com/4618719/77240501-7b414700-6c3a-11ea-9984-0241b779c9d3.jpg)

**Comment by taoxtrece** [comment]
Works with a clean install, but in english, im going to made a translation, when you have the final strings.po i will made another one no problem
