### ISSUE TITLE
No Preview Pictures in Youtube Addon (Landscape Row + Landscape List)

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#441]
The preview pictures of videos don't show up in the youtube addon when landscape row oder landscape list is selected. 
 There's only the white youtube icon on red background. With landscape wall it works well.
Not sure if this is a problem with the skin or with the youtube addon but with default estuary skin it works so I would consider it's a skin issue.

I use version 0.5.71 on matrix

EDIT: Maybe this commit should fix the issues:
https://github.com/jurialmunkey/skin.arctic.horizon/commit/8b09d6c1e0de96345860b7117c1d00ca67d61c21

but installing latest version from zip file didn't help

**Comment by vermope** [comment]
Experiencing same behavior.

**Comment by jurialmunkey** [comment]
Fix added in 0.5.72

I forgot that Kodi still doesn't set `ListItem.ActualIcon` properly for plugins and just duplicates `ListItem.Icon` to it instead (which YouTube sets as the thumb rather than the icon).

**Comment by vermope** [comment]
@jurialmunkey Great, thank you for the fix!
