### ISSUE TITLE
[Feature Request] Ratings on Screensaver

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#45]
Since I know you're running the skin side of it... I'd love some ratings on Arctic Mirage 👍

**Comment by jurialmunkey** [comment]
Added.

**Comment by drinfernoo** [comment]
What's the difference between the fullscreen widget and this?

**Comment by jurialmunkey** [comment]
> 
> 
> What's the difference between the fullscreen widget and this?

They both use the same include for info. Main difference is that the screensaver has the pan and zoom effect. Then there's the showcase screensaver which has recommended items underneath (can toggle the two different modes in Miscellaneous Skin Settings).
