### ISSUE TITLE
Search paths page missing

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon#455]
I'm not sure if this is the right place to ask but the page with helpful search paths has been removed. Is there a way to get it back? 

https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36#issuecomment-489337417

**Comment by jurialmunkey** [comment]
Here you go - https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/104
