### ISSUE TITLE
Problem with profiles

### ISSUE THREAD

**Issue by Galicia86** [jurialmunkey/skin.arctic.horizon#466]
There is a problem when changing profiles... when I press disconnect it goes to the Master User instead of proposing the available profiles. The same problem with Adroid TV. 

https://user-images.githubusercontent.com/104492321/173570468-3a96d556-bf00-4bde-ab4c-a335efd3e1d5.MOV

https://user-images.githubusercontent.com/104492321/173570548-36029627-c3fa-4459-8ec4-f3f53e46b5e9.MOV

**Comment by jurialmunkey** [comment]
Wrong repo. This is Arctic Horizon 1.

**Comment by jurialmunkey** [comment]
Arctic Horizon 2 is here : https://github.com/jurialmunkey/skin.arctic.horizon.2/issues

**Comment by Galicia86** [comment]
Ok excuse
