### ISSUE TITLE
Bug report with Tmdb helper 4.11

### ISSUE THREAD

**Issue by Djej30** [jurialmunkey/skin.arctic.horizon#468]
Hello,
I installed the "Artic horizon" skin (which is magnificent) and I want to use "Tmdb helper" and its players to launch direct searches.
The problem is that I launch a first search which works very well, but if I launch a second one directly, it sends me back to the previous result (as if the player had not typed anything).
I used the player configurator with "keyboard_dialog.json"
This bug does not appear with the Estuary skin.
Do you have an idea?

**Comment by jurialmunkey** [comment]
Arctic Horizon 1 is not being developed any more. I have moved on to Arctic Horizon 2.
