### ISSUE TITLE
[Bug] Wrong "End"-Time after starting any video file

### ISSUE THREAD

**Issue by svb91** [jurialmunkey/skin.arctic.horizon#51]
After starting any episode of a TV show or movie there is a label on the top right corner which shows "Starts xx:xx - Ends xx:xx" But both times are identical

**Comment by jurialmunkey** [comment]
Can you get me a screenshot? There isn't anything in the skin that shows "Starts xx:xx - Ends xx:xx".

There is a now playing indicator in the top right of the library/home views which shows "Time xx:xx - Ends xx:xx", but the times aren't identical:
![Honeyview_screenshot656](https://user-images.githubusercontent.com/4618719/77309104-2d1e6780-6d50-11ea-84cc-8bca4eedddb9.jpg)

**Comment by svb91** [comment]
![error](https://user-images.githubusercontent.com/36643963/77310775-2ddadd80-6cff-11ea-9902-91f396d9b76a.jpg)

Perhaps an Issue with tje time-format? I have the german language active with 24h-time-format.

**Comment by jurialmunkey** [comment]
I doubt it is a time format issue. It is odd though - I'm not sure why Kodi would be filling that label with the current time. I'm definitely using the correct end time label, so I'm not sure why it isn't working properly.

Only thing I can do from the skin side of things is add an extra check to make sure that end time isn't the same as current time (and if they are then I just hide the end time to prevent duplication).

**Comment by Goldsucher** [comment]
same here, but with AZ2 it is working

**Comment by svb91** [comment]
Yep, tried it with AZ2 - no issue at all :-)

**Comment by drinfernoo** [comment]
I have noticed it being the same time for a second *right* when something starts, but once it's playing the time is accurate.

**Comment by jurialmunkey** [comment]
@Goldsucher @svb91 - That label is not in the Now Playing indicator in AZ2? So how are you testing it? If you're talking about in FullscreenVideo, that's an entirely different window....
