### ISSUE TITLE
[Bug] No clock / weather information in top-right corner when playing

### ISSUE THREAD

**Issue by svb91** [jurialmunkey/skin.arctic.horizon#52]
Usually there is the current time and weather information shown in the top-right corner of each page.
When watching TV and pressing back to see the channel list the information is hidden until stop playing completely.

**Comment by jurialmunkey** [comment]
The now playing indicator shows the current time along with the end time:

![Honeyview_screenshot656](https://user-images.githubusercontent.com/4618719/77309355-9e5e1a80-6d50-11ea-9c47-ffb3d794c93e.jpg)

**Comment by svb91** [comment]
That is correct, but when I stream any TV show there is nothing in this corner (of course no end time, because the data does not contain such information)

I would expect in the PVR section the default "Clock | Temperation" when I press back to see the EPG, but it is empty until I stop streaming.

![error_pvr](https://user-images.githubusercontent.com/36643963/77311116-d25d1f80-6cff-11ea-9025-3c1e1f238c6b.jpg)

**Comment by jurialmunkey** [comment]
Ah okay, I see what you mean - it is missing from PVR Channels and Guide sections. Should be fixed now.
