### ISSUE TITLE
[Feature] Show Episode/Season in TV Channels/EPG view (like in Live-TV OSD)

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#54]
This information is only visible in Live-TV OSD. Would be great to have it in TV Channels/EPG/Information view

![IMG_0311](https://user-images.githubusercontent.com/7906131/77370940-53e59980-6d62-11ea-902a-07c5ef3133d9.JPG)

thanks!

**Comment by jurialmunkey** [comment]
I think it should be fixed now. Can you test and confirm?
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.39

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/b69adaf43976aca0e8dc549ad471548a706e3472

**Comment by Goldsucher** [comment]
Sorry I think that didn't work. Now it's completely gone:

![IMG_0313](https://user-images.githubusercontent.com/7906131/77380183-c9f5fa80-6d7a-11ea-9732-07a31cdb5478.JPG)
it should be there before "Folge 6" (I compared it with Estuary)

![IMG_0314](https://user-images.githubusercontent.com/7906131/77380259-f873d580-6d7a-11ea-97ed-2765ebfa07af.JPG)



But now, there is IMDb rating, what I like too 😄 (but without stars, I think that's a font problem):

![IMG_0315](https://user-images.githubusercontent.com/7906131/77380334-1ccfb200-6d7b-11ea-8ff0-22956f18a2c2.JPG)

**Comment by jurialmunkey** [comment]
I didn't change the info above the seekbar, so if it's missing there then something is missing from your EPG.

**Comment by Goldsucher** [comment]
okay strange. But the information is definitely available (I can see it in my tvheadend backend and it works on estuary).

**Comment by jurialmunkey** [comment]
Do you know what the listitem info label is for this data? I don't have this type of data available in my PVR, so it is very difficult for me to test or know which label is the issue.

**Comment by Goldsucher** [comment]
this is an example of a tv show epg entry, does this help you?

```xml
<programme start="20200325015202 +0000" stop="20200325021217 +0000" channel="ProSieben">
  <title lang="de">2 Broke Girls</title>
  <sub-title lang="de">Candy-Andy ist kein Dandy</sub-title>
  <desc lang="de">(US) 2012 • IMDb: ★★★☆☆
Caroline hat ein Date mit Andy - doch nichts passiert zwischen den beiden. Max ist dennoch überzeugt, dass er in ihre Freundin verliebt ist und schlägt vor, das zweite Date abzuwarten. Doch Andy macht wieder keine Annäherungsversuche. Indes lernen die beiden im Diner zwei Amish-Jungs kennen. Max und Caroline überreden sie, einen Stall für Chestnut zu bauen. Ihre neuen Bekannten sind nicht nur außergewöhnlich naiv, sondern auch sehr attraktiv - das fällt nicht nur Max sofort auf.
</desc>
  <credits>
    <director>Thomas Kail</director>
    <actor>Kat Dennings</actor>
    <actor>Beth Behrs</actor>
    <actor>Garrett Morris</actor>
    <actor>Matthew Moy</actor>
    <actor>Jonathan Kite</actor>
    <actor>Jennifer Coolidge</actor>
    <actor>Ryan Hansen</actor>
    <actor>Brandon Jones</actor>
    <actor>Jack DePew</actor>
    <actor>Barry Finkel</actor>
  </credits>
  <date>2012</date>
  <country>US</country>
  <category lang="de">Soap / Melodrama / Folkloric</category>
  <episode-num system="xmltv_ns">1 . 6 . </episode-num>
<star-rating system="IMDb">
  <value>6.7/10</value>
  </star-rating>
  <icon src="https://m.media-amazon.com/images/M/MV5BMTYxMDA3Mzg5NV5BMl5BanBnXkFtZTgwNDIxOTcwMDI@.jpg"/>
  <imdb url="https://www.imdb.com/title/tt1845307/"/>
  </programme>
```

**Comment by jurialmunkey** [comment]
Can you get me some screenshots from Estuary showing the info that is missing from AH? I should be able to work backwards using the screenshots and the above info you gave me.

**Comment by Goldsucher** [comment]
sure, here it is how it looks like in Estuary:

![IMG_0323](https://user-images.githubusercontent.com/7906131/77495543-35a69900-6e49-11ea-90ad-e1200fd8448e.JPG)
![IMG_0324](https://user-images.githubusercontent.com/7906131/77495546-393a2000-6e49-11ea-92ff-4ecc7ac719dc.JPG)


the dev of the epg grabber said, the imdb ratings work on arial-based fonts, but it's also possible to grab the rates from the pvr parameters and place it somewhere in the skin

**Comment by jurialmunkey** [comment]
It's the S2E7 section that is missing right?

**Comment by Goldsucher** [comment]
yes thats right. Thanks for your investigation 😊

**Comment by jurialmunkey** [comment]
Ah I think it is just a standard season/episode label. I think you might've stopped getting it because the item you were playing had *more* info which was triggering a different set of info to show

Can you test latest version, I think it should fix it
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.47

--- 
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/986d43e2eaee4575cd3642a60c98cc68ca31769e

**Comment by Goldsucher** [comment]
yes, now it's there. Thanks a lot! 🍻

**Comment by jurialmunkey** [comment]
Excellent! Thanks for your help!
