### ISSUE TITLE
[Bug] Skin Search Keyboard Displays Twice

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#60]
Any time I use the built-in skin search, the keyboard dialog is displayed twice.

**Comment by jurialmunkey** [comment]
Can confirm. Not quite sure why yet. I'm looking into it.

**Comment by jurialmunkey** [comment]
Okay should be fixed now.

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/59588815890c2b251c6928b8b606bf4f97c7af8c
