### ISSUE TITLE
[Feature] display resolution when browsing content

### ISSUE THREAD

**Issue by prydda** [jurialmunkey/skin.arctic.horizon#62]
Display a 4k/1080/720p indicator next to tmdb while browsing

**Comment by jurialmunkey** [comment]
I don't understand what you mean by "next to tmdb".

And why do you need resolution displayed? What is rationale for this request?

**Comment by prydda** [comment]
Like this, display resolution of current content here, 

Sometimes there is duplicates of a movie 1080 and 4k, nice to know which res it is while scrolling   

![bild](https://user-images.githubusercontent.com/2561787/77514952-05c2ba00-6e78-11ea-829b-77694ad18692.png)

**Comment by jurialmunkey** [comment]
Why would you keep a lower resolution copy if you have a higher resolution?

**Comment by svb91** [comment]
I would also like to see an indicator of the resolution (and no, I do not have multiple copies of a single movie) :-)

**Comment by jurialmunkey** [comment]
> 
> 
> I would also like to see an indicator of the resolution (and no, I do not have multiple copies of a single movie) :-)

But for what reason? Why do you need/want to see this information whilst browsing?

**Comment by svb91** [comment]
In my eyes it is not a "needed" function, more a gimmick because it is already known from PLEX or other skins.

**Comment by drinfernoo** [comment]
@jurialmunkey I'll admit, I get where you're coming from and wouldn't argue if it never happened, but it would be nice to have somewhere in the skin that displays various codec flags.

It's often useful to be able to quickly distinguish between different versions of a file (3D vs 2D, SDR vs HDR, etc...), or to have a subtle reminder while browsing, in case your library is made up of mixed-quality content.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I'll admit, I get where you're coming from and wouldn't argue if it never happened, but it would be nice to have somewhere in the skin that displays various codec flags.
> 
> It's often useful to be able to quickly distinguish between different versions of a file (3D vs 2D, SDR vs HDR, etc...), or to have a subtle reminder while browsing, in case your library is made up of mixed-quality content.

You can see codec info in the info dialog when highlighting overview/manage.

The 2D/3D, SDR/HDR, and aspectratio distinguishing actually makes sense because you often need to do something for those (e.g. get your 3d glasses or adjust the player used). I wouldn't be opposed to finding a way to display that information (as long as it doesn't get cluttered!).

It's just that HD/SD has no real use other than appeasing the people who seem to want to try to smash every single possible piece of information on screen for some reason. If only playing HD content is important - create a smart playlist or node that only shows HD content.

I have a lot of old content that I previously ripped from DVDs in SD (way back when I had xbmc on an xbox running through a CRT tv). That can be annoying to watch on the big TV, so I simply have a separate library node setup which only contains HD content by using a rule that resolution must be above 719.

**Comment by jweinreich** [comment]
Having an indicator icon, like 4K, keeps it compact and sleek.
Also, audio quality, 2.0 or 5.1 would be nice.
This is useful if say, you invite friends over, you'd prioritize showing off your 4K 5.1.2 setup wouldn't we all?? :P
Of course if this means too much clutter (or unnecessary resource hog) that's for JM to decide.

**Comment by jurialmunkey** [comment]
> 
> 
> Having an indicator icon, like 4K, keeps it compact and sleek.
> Also, audio quality, 2.0 or 5.1 would be nice.
> This is useful if say, you invite friends over, you'd prioritize showing off your 4K 5.1.2 setup wouldn't we all?? :P
> Of course if this means too much clutter (or unnecessary resource hog) that's for JM to decide.

Why don't you use a smart playlist or a library node for that purpose? That's what I do. 

This is the smart playlist I use for HD Movies:

![Honeyview_screenshot668](https://user-images.githubusercontent.com/4618719/77596646-b56b5b00-6f50-11ea-985f-78dca781b58c.jpg)

**Comment by prydda** [comment]
my box/tv in bedroom cannot play 4k, I "need" a 1080p version when searching for a movie I'll have 2 versions and then need to click it scroll to overview to see which version it is. A small icon with the source version - that wouldn't clutter the view? 
And yeah, real problems here right?

**Comment by jurialmunkey** [comment]
> 
> 
> my box/tv in bedroom cannot play 4k, I "need" a 1080p version when searching for a movie I'll have 2 versions and then need to click it scroll to overview to see which version it is. A small icon with the source version - that wouldn't clutter the view?
> And yeah, real problems here right?

So why don't you use a library node with a resolution rule so that you only see content that you actually can play...

I'm still yet to hear of something where seeing the resolution wouldn't be better solved by using library nodes to categorise your library properly.

**Comment by drinfernoo** [comment]
@jurialmunkey I think the biggest reason is that not everyone uses library content, and those that do don't necessarily have enough "one-off" items to warrant an entire node, but still need a way to be easily distinguished from alternative versions of the same item.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I think the biggest reason is that not everyone uses library content, and those that do don't necessarily have enough "one-off" items to warrant an entire node, but still need a way to be easily distinguished from alternative versions of the same item.

All the addons that I've come across that have multiple sources will group those sources together as one item and then present a dialog or list to select the source/quality when you click play.
