### ISSUE TITLE
[Feature] Spanish Translation

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#64]
Hi @jurialmunkey here is the spanish translation for the version 0.1.40b
[resource.language.es_es.zip](https://github.com/jurialmunkey/skin.arctic.horizon/files/4377777/resource.language.es_es.zip)

**Comment by jurialmunkey** [comment]
A lot of these labels are going to be removed so there is no point translating yet.

**Comment by taoxtrece** [comment]
I know, no problem i can update in anytime👍

**Comment by taoxtrece** [comment]
Updated for 1.0.69

**Comment by taoxtrece** [comment]
Updated for 0.1.74, @jurialmunkey can add more strings? from Custom_1119_EnableInfoLists, Custom_1141_Showcase, Includes_Dialog, Includes_DialogVideoInfo, Includes_Home, Includes_Items and Includes_OSD
