### ISSUE TITLE
[Bug] Autocomplete Suggestions Transparent

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#65]
I've noticed this a few times here and there, but mainly when using skin search:

![](https://i.imgur.com/Iv0CIk2.png)

**Comment by jurialmunkey** [comment]
How did you get autocompletion to work? I haven't had it working since it was marked as broken in the kodi repo -- I think it has been reinstated but it still doesn't work for me.

**Comment by drinfernoo** [comment]
I know that in Leia, there's been [some issues reported](https://github.com/phil65/plugin.program.autocompletion/issues/12)... but I didn't realize it had been marked broken.

With the notable exception of having the above linked behavior on some of the earlier Leia releases, I've had it working the "whole time".

As an aside, since it isn't a required dependency of AH, it always prompts me to install it the first time I open the keyboard after installing the skin fresh, which is a bit annoying 😅

**Comment by jurialmunkey** [comment]
> As an aside, since it isn't a required dependency of AH, it always prompts me to install it the first time I open the keyboard after installing the skin fresh, which is a bit annoying 😅

Yeah I removed it as a dependency because it was marked as broken which would stop the skin from installing. If it isn't broken anymore then I might re-add it as a dependency (assuming I can get it to work now!).

**Comment by jurialmunkey** [comment]
Hahaha I just did a clean reinstall of my Addons db... I'm fairly certain it has been working the whole time and I just couldn't see it because the backing panel wasn't there 🤦‍♂ 

Should be fixed now.

**Comment by drinfernoo** [comment]
Should it be made into a required dependency?

**Comment by jurialmunkey** [comment]
Yeah probably.

**Comment by drinfernoo** [comment]
@jurialmunkey, what if TMDbHelper eventually integrated this functionality?

With proper skin support, it could potentially even provide *different* suggestions, like search history or recommendations... What do you think?
