### ISSUE TITLE
[Feature] Forced Menu Position

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#67]
As the title says 😁

**Comment by jurialmunkey** [comment]
I'm guessing that this setting should only apply on startup? Or is the intent that it resets position each time home is opened?

**Comment by drinfernoo** [comment]
Hmm, good question. I could see it possibly getting annoying if it did every time you return to home... But I also can't remember how it used to work it Aura 😅

**Comment by jurialmunkey** [comment]
I actually don't think this is going to be possible without causing other bugs.
