### ISSUE TITLE
Date and Empty rating stars remain on screen when Full screen widget is disabled

### ISSUE THREAD

**Issue by jweinreich** [jurialmunkey/skin.arctic.horizon#68]
Disabled Full screen widget, go to widgetless menu (search for example).
No fallback picture is set.
Photo attached.

![20200325_103036](https://user-images.githubusercontent.com/6373803/77542172-85ef1c80-6e84-11ea-9231-4e994222b1b9.jpg)

**Comment by drinfernoo** [comment]
What do you want to be there of you've disabled everything that could be?

**Comment by jweinreich** [comment]
Well nothing besides the Search title and time?
It's just weird that the rating stars remain there empty.

**Comment by jurialmunkey** [comment]
How are you disabling the fullscreen widget? You shouldn't be able to disable it.

**Comment by drinfernoo** [comment]
@jurialmunkey You can set the path to "None", and nothing will show, regardless of library content, as far as I can tell.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey You can set the path to "None", and nothing will show, regardless of library content, as far as I can tell.

No it should fallback to RandomMovies playlist if None
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/1080i/Includes_Defs.xml#L3-L6

Either way, the empty info should be fixed now.

**Comment by drinfernoo** [comment]
Ah, I see... I had to add stuff to my library to see 😅 Could we maybe have it default to RandomMovies, but be settable to None, in order to have a blank page even with library items present?

**Comment by jurialmunkey** [comment]
I've got a plan to have the possibility of choosing an image (or folder of images) as an alternate option.
