### ISSUE TITLE
Duplication of TV guide (and livetv osd) programme synopsis 

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon#69]
Hi. As of the latest update, programme synopsis is duplicated in TV guide (I’m using OTA tuners via tvheadend in the UK). Synopsis is also duplicated in livetv osd, but this has been present since AH was released. Thanks.

**Comment by Tee77** [comment]
![EC1D7567-9C70-4C00-B4BE-D4C7AD18A96B](https://user-images.githubusercontent.com/62660160/77555160-dbd8ba00-6eae-11ea-8c6e-54d814f5b613.jpeg)

**Comment by jurialmunkey** [comment]
Your PVR is incorrectly putting the Plot into the EPGEventTitle field.

Can you test v0.1.50b? 
I've added a check to hide that label if it matches plot.

**Comment by Tee77** [comment]
Awesome, that’s done the trick with TV guide. Osd info is still duplicated but not sure if anything can be done about that. Also, just an observation...the guide feels a little squashed compared to how it was. No biggie tho. Thank again mate.

**Comment by Tee77** [comment]
In case this helps. 
![B8D6F73D-2C86-42F7-B39B-317A933490D2](https://user-images.githubusercontent.com/62660160/77597512-09495600-6ef7-11ea-82be-f8202bbe3bd7.jpeg)

**Comment by jurialmunkey** [comment]
Yeah I need to fix it to use the same info line data. Once I do that it should resolve the issue.

**Comment by sammy2142** [comment]
The latest master of tvheadend also fixes this
