### ISSUE TITLE
[Bug/Feature Request] Close Showcase on Playback

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#70]
Is it possible to have the showcase view be closed when we actually launch playback from it? That way, when playback ends, we're not still in the "screensaver" 😅

Also, both buttons on the showcase seem to do the same thing, opening information 🤔

**Comment by jurialmunkey** [comment]
Do you have Show Information as your default select action?

**Comment by drinfernoo** [comment]
No, I use Play/Open in TMDbHelper, and Play in Kodi. Looking at the skin files, I see that both buttons have `<onclick>Action(Info)</onclick>`... but I'm not sure what would be appropriate for the Play button 😅

**Comment by jurialmunkey** [comment]
Yep I'm an idiot 😅 
Should be fixed...
