### ISSUE TITLE
[Feature] Other Layout for TV-Channels view

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#71]
In my opinion TV-Channels-view and EPG-View are almost the same. What do you think of the idea to change the layout for TV-Channels View? 
Maybe with an Estuary approach with description and picture:

https://i.ibb.co/Kj5c233/IMG-0327.jpg

**Comment by jurialmunkey** [comment]
Ah I meant to have the PVR Channels and PVR Epg info options to be separate, so it was possible to enable info in one and have the other act as a more general overview.  I've separated the options in the most recent version.

Whilst the Estuary approach is quite good, it doesn't work within the style guidelines in AH.
