### ISSUE TITLE
[Bug] Submenu Item missing

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#73]
I've created a submenu item for musicvideos but it doesn't appear. Don't know why, every other submenu item is working.

![screenshot000](https://user-images.githubusercontent.com/7906131/77595888-b5407080-6efa-11ea-8741-4803ab340fcc.png)
![screenshot001](https://user-images.githubusercontent.com/7906131/77595892-b70a3400-6efa-11ea-8e2b-db2807d190cd.png)

**Comment by drinfernoo** [comment]
Do you have music videos in your library?

**Comment by Goldsucher** [comment]
okay sorry, the scraper didn't work. Now it is there 🤦‍♂
