### ISSUE TITLE
[Bug] Settings Widget Inconsistency

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#74]
The Settings widget looks like this:
![image](https://user-images.githubusercontent.com/2319508/77672265-ebefa880-6f45-11ea-8be3-2d1e83092204.png)
while the Settings window looks like this:
![image](https://user-images.githubusercontent.com/2319508/77672311-fc078800-6f45-11ea-8071-152e091f2ca4.png)

Also, could these be changed up so they respect the "Panels behind item text" setting?

**Comment by jurialmunkey** [comment]
The settings labels should be fixed now.

I did try having those views match panels behind item text setting but I think it looks weird (see screenshots). I think that view is too wide and too short to work like that. For the setting to work, it'd probably need to have a square aspect, which would need a lot of changes.

![Honeyview_screenshot674](https://user-images.githubusercontent.com/4618719/77700195-d0e56d00-7007-11ea-879a-0ea26572d176.jpg)

![Honeyview_screenshot675](https://user-images.githubusercontent.com/4618719/77700193-cfb44000-7007-11ea-8e45-7e1ff27868f7.jpg)
