### ISSUE TITLE
Submenu hub buttons won't scroll

### ISSUE THREAD

**Issue by jweinreich** [jurialmunkey/skin.arctic.horizon#76]
Title says it.
Place a bunch of submenu buttons and navigate to the right. 
Photo attached.
Also you can notice the first button backdrop is glitched, maybe too long text?

![20200326_193459](https://user-images.githubusercontent.com/6373803/77703438-93e29180-6f99-11ea-86d3-dd8b5c4334fb.jpg)

**Comment by jurialmunkey** [comment]
I've already addressed this issue. You need to disable the following setting:
`Skin Settings > Home > Autowidth hub buttons`

If you want to use auto width buttons, then you must reduce the number of items in your submenu or reduce the length of the labels so that they all fit on one screen.
