### ISSUE TITLE
[Question]Info

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#78]
Hi jurialmunkey,
When adding new features, would it be possible to indicate where the new features can be located?
Thanks

**Comment by jurialmunkey** [comment]
I'm hoping to make a Wiki eventually.

If I add comments to the change log it will get quite cluttered. I'll try to make comments on the relevant issue about where the feature is located.

**Comment by Blurayx** [comment]
perfect \0/

**Comment by drinfernoo** [comment]
@jurialmunkey I would just drop them in the commit message?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I would just drop them in the commit message?

Yeah but I'm lazy...

Plus I usually type out a commit message almost automatically without thinking.
