### ISSUE TITLE
[Bug] Weird Label Fading In on Skin Settings

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#79]
![image](https://user-images.githubusercontent.com/2319508/77826171-0acb7780-70cb-11ea-960e-25f62174f129.png)

This strange label fades in and out briefly whenever I open Skin Settings 😉

**Comment by jurialmunkey** [comment]
I think it should be fixed now. Can you test and confirm

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/0a48b013fba47cbf7b8e7a20c44ee9e1d50fad77
