### ISSUE TITLE
[Feature] Search lists - TMDBHelper default options

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#8]
Add default options for search function.

Perhaps even the possibility of a dedicated TMDbHelper search screen that can implement various discover filters.

**Comment by drinfernoo** [comment]
Considering we have the Discover screen working (very nicely, I might add 😉), do these just need to be added to the right Skin Shortcuts file?

**Comment by jurialmunkey** [comment]
Yeah they just need to be setup in skinshortcuts overrides file.
