### ISSUE TITLE
[Bug] Lock main menu position & widgets issue

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#80]
With lock main menu position on and selecting a movie through a widget - the side menu is still visible in the background:
![lock-homemenu](https://user-images.githubusercontent.com/5837771/77826221-02446280-7106-11ea-9dee-39b6ad3f3162.png)

**Comment by jurialmunkey** [comment]
Ah, I forgot to push the fix for this issue. Should be working properly now.
