### ISSUE TITLE
[Bug] focus jumps 

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#81]
see Video:

http://public.beuth-hochschule.de/~s67977/focus.mp4

device is Nvidia SHIELD

**Comment by jurialmunkey** [comment]
I know about this issue, there just isn't much I'm able to do about it. In Kodi, button controls don't allow for layering textures (which is needed to achieve the gradient effect). 

To get the effect I need a separate image control that is positioned depending on which control is focused - but sometimes Kodi lags in setting the position value.
