### ISSUE TITLE
[Bug] Button styling

### ISSUE THREAD

**Issue by svb91** [jurialmunkey/skin.arctic.horizon#82]
First inactive Button shows wrong behaviour since one of the last updated.
![button](https://user-images.githubusercontent.com/36643963/77848064-4a28bf80-71c2-11ea-93ae-08761c6c16f5.png)

**Comment by jurialmunkey** [comment]
It's a Kodi bug with auto width buttons based on labels from a list - not much I can do about it other than suggest that you disable the autowidth option if you're having issues with it.
`Skin Settings > Home > Autowidth hub buttons`
