### ISSUE TITLE
[Feature] Home screen: The Movie DB Next Aired widget

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#83]
Would it be possible to add fallback artwork option for The Movie DB  widgets Basically use the poster or fanart I have selected from my library/thetvdb because tvdb is more up to date, also my library poster will match my home screen widgets and solves the issue of missing artwork from  The Movie DB. I hope this makes sense

Home screen Widget
<a href="https://imgur.com/47J0gz6"><img src="https://i.imgur.com/47J0gz6.png" title="source: imgur.com" /></a>

Library
<a href="https://imgur.com/oZ06t8G"><img src="https://i.imgur.com/oZ06t8G.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
I've added this issue to the TMDbHelper github as it relates to the plugin not the skin.
---
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/142
