### ISSUE TITLE
[Feature] Dark Theme

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#84]
Would it be possible to add a Dark Theme option apart from the side panel I like the white theme but navigating through menus can be overly bright on a large screen.

White theme panel only option in Dark Mode
<a href="https://imgur.com/CIuzHEw"><img src="https://i.imgur.com/CIuzHEw.png" title="source: imgur.com" /></a>

overly bright on a large screen
<a href="https://imgur.com/AvGVYO1"><img src="https://i.imgur.com/AvGVYO1.png" title="source: imgur.com" /></a>

Thanks

**Comment by prydda** [comment]
@Blurayx 

Already an option: 
![bild](https://user-images.githubusercontent.com/2561787/77852592-be259080-71df-11ea-996d-890cd953a9d1.png)

**Comment by Blurayx** [comment]
Dark mode but the  panel stays white😀

**Comment by jurialmunkey** [comment]
I'll have a look, shouldn't be too difficult to add.

**Comment by Blurayx** [comment]
Thanks 😃

**Comment by jurialmunkey** [comment]
`Skin Settings > Colours > Invert home menu colours`

Added v0.1.80
---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/86b940b77fcc315729149ccb932d1dea841204cf
