### ISSUE TITLE
[Bug] Hubs with no Submenu Items Can't Focus

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#85]
While it may seem like an edge case, apparently if you remove all the submenu items from a main menu item, and open the hub... you can't focus anything!

**Comment by jurialmunkey** [comment]
I mean, what should it do? You need submenu items for a submenu...

**Comment by drinfernoo** [comment]
I suppose I'm imagining a hub with the "fallback" Hub Widget only. It does seem silly to add this on purpose, but I did try it and was confused 😅

**Comment by jurialmunkey** [comment]
> 
> 
> I suppose I'm imagining a hub with the "fallback" Hub Widget only. It does seem silly to add this on purpose, but I did try it and was confused 😅

Yeah I'm not sure I see the purpose of doing that - wouldn't it be better to just add a shortcut to open directly whatever plugin/library path that you want to use?

**Comment by drinfernoo** [comment]
Yeah, I guess so 🤦🏻‍♀️ Carry on!
