### ISSUE TITLE
[Bug] Add-ons' "Settings" button shows no menu/option.

### ISSUE THREAD

**Issue by termnl0** [jurialmunkey/skin.arctic.horizon#86]
Installed latest version: 0.1.64.
Tried rebooting twice, still not working.

Edit: Up Next is affected too. It's setting pop-up menu shows a "No categories available" message. Can't configure it.

**Comment by drinfernoo** [comment]
What add-ons are you experiencing this with? That sounds more like an add-on issue, as I'm unable to replicate it with any add-ons I'm using.

**Comment by termnl0** [comment]
> What add-ons are you experiencing this with? That sounds more like an add-on issue, as I'm unable to replicate it with any add-ons I'm using.

The issue is occuring in Up Next add-on.

**Comment by jurialmunkey** [comment]
I can't replicate this issue either - unless I'm misunderstanding what the problem is.

Can you get me some screenshots demonstrating the issue and how to replicate.

**Comment by drinfernoo** [comment]
@termnl0 Try reinstalling Up Next. Usually this type of thing happens when the add-ons' `settings.xml` gets corrupted or something else weird.

**Comment by termnl0** [comment]
Here's the screenshot:

**Comment by drinfernoo** [comment]
What version of Kodi and on what platform?

**Comment by termnl0** [comment]
> What version of Kodi and on what platform?

I'm currently in Leia v18.6. 
Edit: Sorry for the trouble, it's fixed now. All I had to do is reinstall Kodi again and delete my userdata in AppData folder.
