### ISSUE TITLE
[Feature] Currently recording PVR

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#87]
Is it possible to show a status icon on video files that haven't finished recording (Like the red dot on the default skin) and perhaps a widget to show currently recording?
thanks

![recent_recordings_esturary](https://user-images.githubusercontent.com/5837771/77858708-099a6780-71fd-11ea-8720-53c6ca3dc5eb.png)

![Currently_recording](https://user-images.githubusercontent.com/5837771/77858695-f5ef0100-71fc-11ea-84cf-21a7593cddc4.png)

Also there is a minor bug when opening the pvr sub menu on first startup. The guide button gets cut off when you move the cursor. Going back to the home menu and reopening it fixes it. 
Edit: Disabling auto-width hub buttons fixes it
![Guide button short](https://user-images.githubusercontent.com/5837771/77859021-dbb62280-71fe-11ea-9d09-0ebdbbca6062.png)

**Comment by jurialmunkey** [comment]
Should be all fixed now.

Recording indicator added.

You can add a now recording widget by adding `Default Widgets > PVR > Timers`
