### ISSUE TITLE
[Issue] NextPVR recording folder display issue

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#88]
It looks like the nextpvr backend uses some kind of nested folder display which doesn't look very nice currently with each item taking 2 clicks to display any information.

![NextPVRRecordingFolder](https://user-images.githubusercontent.com/5837771/77860578-022c8b80-7208-11ea-85b6-9218d95ccc14.png)

![NextPVRRecordingFolder2](https://user-images.githubusercontent.com/5837771/77860586-09539980-7208-11ea-8dbd-73d9d98fa396.png)

![NextPVRRecordingFolder3](https://user-images.githubusercontent.com/5837771/77860591-0c4e8a00-7208-11ea-8013-d2fa6d6c9488.png)

The poster size for recordings also seem a little small for some reason?
![recording_poster_size](https://user-images.githubusercontent.com/5837771/77860744-b7f7da00-7208-11ea-9d66-d5dbd06757e0.png)

**Comment by jurialmunkey** [comment]
I can't do anything about the nesting - that's to do with the PVR addon.
You can toggle between list and landscape views for recordings using the options menu.

**Comment by sammy2142** [comment]
Ok thanks for the reply - I will probably give tvheadend a try tomorrow

**Comment by jurialmunkey** [comment]
BTW the posters are shrunken because usually PVR addons put the channel logo in the Icon, so the assumption is that the artwork will be a logo (and thus needs padding from the edges to look right).

**Comment by sammy2142** [comment]
Hi
This is my first tuner with Kodi so I must admit I'm not sure of the norm - i've only run Nextpvr so far.
nextpvr can search tvdb and the moviedb and provide poster artwork if available for the client (it never displays the channel logo on recordings ).
I believe tvheadend can also show posters if available and falls back to the channel logo if not (I think using zap2itxml and maybe others),
It looks like the zuki.pvr.hdhomerundvr also supports poster artwork.

As for the nested folders in nextpvr - It looks like they have fixed this issue in the next release (they are currently doing a rewrite of nextpvr and making it multiplatform instead of Windows only) but they seem to be focusing on compatibility for the next kodi iteration (kodi Matrix). 

I'm gonna have a play with tvheadend since that seems to be the most popular backend at the moment. 

Thanks again for the great skin!
