### ISSUE TITLE
Wrong art type on movies submenu hub random movie widget

### ISSUE THREAD

**Issue by jweinreich** [jurialmunkey/skin.arctic.horizon#91]
Hello JM, a heads up:

Enable submenu hub.
Set global Hub Widget to Random Movie (Library list)
Set Hub Widget - Aspect to Banner

You get wrong art type, as seen here:

![20200329_202954](https://user-images.githubusercontent.com/6373803/77864228-d3111c80-71fd-11ea-8af6-8e4adfe2a366.jpg)

TV Shows submenu works properly using same method:

![20200329_203011 (1)](https://user-images.githubusercontent.com/6373803/77864132-5716d480-71fd-11ea-885e-af96fd3d599d.jpg)

**Comment by jurialmunkey** [comment]
Do you have banner artwork for that item?

**Comment by jweinreich** [comment]
Yes, i noticed banner fanart shows properly for TMDBH widgets but not default widgets?

Already double checked OMDB and FANART.TV api keys.

I set these widgets as an example on the Movies main screen (not hub):

![20200330_190149](https://user-images.githubusercontent.com/6373803/77967881-6c066d00-72bc-11ea-9be1-98e265d5467e.jpg)

![20200330_190207](https://user-images.githubusercontent.com/6373803/77967888-6e68c700-72bc-11ea-8250-00d8a04db2f7.jpg)

![20200330_190224](https://user-images.githubusercontent.com/6373803/77967892-70328a80-72bc-11ea-9113-bd534672c620.jpg)

Results in:

![20200330_190053](https://user-images.githubusercontent.com/6373803/77967915-7d4f7980-72bc-11ea-90c3-1a477ebfc735.jpg)


![20200330_190112](https://user-images.githubusercontent.com/6373803/77967920-84768780-72bc-11ea-8a00-42c0a453a31b.jpg)


So default widgets for movies are bad, TMDBH widget for movies is good, default widget for tv shows is good too?

**Comment by drinfernoo** [comment]
This means the movies in your library don't have banner art.

**Comment by jweinreich** [comment]
> This means the movies in your library don't have banner art.

Thank you. Installed artwork beef and got it sorted out.
The fact some type of media already gets the banner artwork while other type wouldn't made it all more confusing.

**Comment by drinfernoo** [comment]
Well, TMDbHelper grabs the artwork for you, but only attaches it to its own items, not ones in your library.

**Comment by jweinreich** [comment]
Yeah, tho it's weird proper artwork shows for tv shows library items, but not movies.
Oh well.

**Comment by jurialmunkey** [comment]
> 
> 
> Yeah, tho it's weird proper artwork shows for tv shows library items, but not movies.
> Oh well.

It's because Banner was historically the default artwork type for tvshows from back in the XBMC/XBOX days (i.e. prior to Frodo when the ability to have additional artwork types was added).

So tvshow scrapers typically add banner to tvshows for legacy reasons.
