### ISSUE TITLE
[Feature Request] Unwatched Count on Season Button

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#92]
In the standard season/episode view... would it be super weird to have an unwatched count on the season? I think that's what I miss most about a dedicated seasons view (and artwork, I guess 😅)...

**Comment by jurialmunkey** [comment]
I'm not quite sure where to show it. It would look weird on the corner I think. I'm not opposed to show the info, just not sure how to display it really.

It does show in the info line below title how many episodes have been watched.

Also, now there's an option Skin Settings > Library to disable the integrated seasons view if you prefer to use posters.
