### ISSUE TITLE
[Bug] Submenu button focus colour

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#93]
AH 0.1.64 with edited fonts sizes and TmdbH 2.2.90

When a button is unfocused, the Icon is shown.

![screenshot009](https://user-images.githubusercontent.com/10348988/77895103-92a1b500-7276-11ea-8464-b796eee4a480.png)

When focused, the icon goes dark.

![screenshot010](https://user-images.githubusercontent.com/10348988/77895116-9a615980-7276-11ea-9823-c6e1eff90408.png)

These are my settings.

![screenshot011](https://user-images.githubusercontent.com/10348988/77895140-a0efd100-7276-11ea-8099-aee425265688.png)

And no matter what colour I give overlay (mostly used to put over backgrounds I assume), the issue remains.

Btw, these are just testing colours. with black as my main colour, the white icons on the seekbar disappear (go black) when focused.

Also I don't know if this is a real issue or just me, didn't want to create an issue for nothing.
I just read https://github.com/jurialmunkey/skin.arctic.horizon/issues/82. As you can see I have more buttons than fit on the screen.  If I enable "Autowidth hub buttons" then the focused button sometimes dissapears off screen to the right. You don't see which one is selected.

**Comment by jurialmunkey** [comment]
You need to set a monochrome icon that is included with the skin.

**Comment by DaisyF8** [comment]
I don't get it. Is there a toggle somewhere? How do you mean included in the skin?

**Comment by drinfernoo** [comment]
@DaisyF8 A number of icons are included with the skin, and are what are shown when you "Select Icon" in the Skin Shortcuts dialog.

**Comment by DaisyF8** [comment]
Aaaaaaaah... Never knew that. Thx @drinfernoo  . Twas also nice hearing you on YouTube :)
