### ISSUE TITLE
[Bug] Install icon Not Working 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#94]
Install icon nonresponsive 

<a href="https://imgur.com/DLKlRkB"><img src="https://i.imgur.com/DLKlRkB.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
It looks like those addons are already installed but they disabled. Install works fine for me if the addon isn't installed.

**Comment by Blurayx** [comment]
I'll monitor the situation. the other day I tried to update/install another app AH would no let me, I had to use AZ2 to install it.

Thanks
