### ISSUE TITLE
[Issue?] - Trailer not playing fullscreen first time

### ISSUE THREAD

**Issue by ricksrod** [jurialmunkey/skin.arctic.horizon#95]
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/4406044/kodi.log)

I am using the PlexKodiConnect addon to build my Kodi library and when I try to play a trailer for the first time it plays in full screen. If I exit and then select 'trailer' again it will play in the window mode.

I've attached a log file that shows this, I notice that the trailer source is from Plex, not sure if this is what is causing the issue?

I did play with some PKC settings the other day which seemed to resolve this but it started occurring after I had to rebuild my Shield.

**Comment by jurialmunkey** [comment]
I don't think that this is a skin issue. 
All the skin does is tell Kodi to play the trailer in the background by adding the "1" flag:
`<onclick>PlayMedia($INFO[ListItem.Trailer],False,1)</onclick>`

My guess is that there is something in PKC that overrides the play in background flag (or forces playback to be fullscreen).

Not really anything that can be done from the skin side if the play in background flag is not being respected.
