### ISSUE TITLE
[Feature] Exclude Menu Items From Infinite Scroll

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/skin.arctic.horizon#97]
Hello jurialmonkey! Loving the new skin, great job on it!

I have a minor feature request, not even sure if it’s possible though. 

I have a couple menu items that I personally would not like to be cycled through during the homescreen widget’s infinite scroll feature (not sure the official name tbh). 

An example of these menu items would be Addons, Settings, Search (only because I haven’t found a good widget for it). 

Maybe possible to add a toggle while setting it up in Skin Shortcuts, and when enabled - the infinite scroll just skips that menu item (and all widgets)?

Thanks again!

**Comment by jurialmunkey** [comment]
It would be a great feature to have, but I'm not sure if it would be possible.
I'm having enough trouble as it is now to get it all working correctly.

**Comment by Demonseeed** [comment]
No worries at all, drop this to the lowest on your priority list, if at all 😄

**Comment by jurialmunkey** [comment]
Now that you've mentioned it, I really want it though!  😉 

I've added a note about this idea to the other issue where I'm keeping track of widget scrolling issues - so I'll close this one just to keep things tidy.

**Comment by Demonseeed** [comment]
Sweet, I’m glad you like the idea too! 😄👌
