### ISSUE TITLE
Flattened series view (TMDb helper)

### ISSUE THREAD

**Issue by rijs43** [jurialmunkey/skin.arctic.horizon#98]
When series are flattened through TMDb helper settings, and press browse for a certain serie it is not possible to see which poster view is representing which season in AH. I have to click the poster for the serie to see which season I am entering..

**Comment by jurialmunkey** [comment]
It's not possible to fix this issue. It's related to a Kodi bug where the folderpath for plugin:// paths is cleared inside the info dialog if the item is also in the library.
