### ISSUE TITLE
[Enhancement] Skin Shortcuts - Genre Aspect

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/skin.arctic.horizon#99]
Hi Jurialmunkey!

I have another potential request, though I question whether it is appropriate to ask for this to be done at the skin level vs the addon level. If this is not within the scope of the skin, please feel free to let me know. 

When setting a Skin Shortcut widget to an addon’s Genre’s section - most addons do no include icons for each genre. While the widget functionally works fine, generally it looks bad. See the screenshot below:
![966B3DE5-59F1-4A78-9C0D-FFC8F95729C0](https://user-images.githubusercontent.com/29167580/78198492-95023b80-743d-11ea-976c-7292e1624dde.jpeg)

What I ask is akin to how the skin AuraMod got around this. There is a Aspect you can choose from while creating your widgets called “Genre.”

When this is chosen, it is poster-aspect, but applies a generic icon that matches the skin over each of the genre options. 

Thank you!

Edit: Instead of an actual icon representing the genre, maybe have the Genre aspect display the label of the item. This would help specifically with anime-related addons, who tend to have genres vastly different than the norm.

**Comment by jurialmunkey** [comment]
If the addon correctly sets ListItem.DBType to `genre` then the genre icons are automatically displayed. For instance, here is TMDbHelper genres displaying the skin icons and using icon aspect (poster/square/landscape will also work - I just prefer the icon aspect for genres).

![Honeyview_screenshot714](https://user-images.githubusercontent.com/4618719/78207105-7149fe80-74ec-11ea-809f-4a64f3052a6e.jpg)

**Comment by Demonseeed** [comment]
Perfect, thank you!

**Comment by jurialmunkey** [comment]
Basically, if the addon isn't showing genre icons then it hasn't set the correct DBType - so you would need to contact the addon author to get them to make the change.

**Comment by Demonseeed** [comment]
Awesome, thank your explain in my what needs to be done. I will do that.

**Comment by unkn0wn234** [comment]
> Basically, if the addon isn't showing genre icons then it hasn't set the correct DBType - so you would need to contact the addon author to get them to make the change.

Hey jurial does the icon aspect not show 2 rows anymore it only shows 1 for me unless I’m missing something I was trying to use the genres widget as a separator between info widgets and non info widgets but there’s still one line at the top for info from the other info widget.

**Comment by jurialmunkey** [comment]
Yeah it is single line now so that it can be used as a submenu widget.

**Comment by unkn0wn234** [comment]
> Yeah it is single line now so that it can be used as a submenu widget.

Ah I see, i assume this wont be open to any further change?

**Comment by jurialmunkey** [comment]
Unfortunately not. That type of panel layout is quite difficult to manage properly in a group list and was really only possible when the widget system was much simpler

**Comment by unkn0wn234** [comment]
Ah okay well thanks for explaining anyway!
